### ISSUE TITLE
Save state problems in latest build 

### ISSUE THREAD

**Issue by brujo5** [hrydgard/ppsspp#10364]
What happens?
When i load a save state for first-time work good but when load save state for second time cause game freeze for few seconds.
Just look fps count 

![screenshot_20171206-233836](https://user-images.githubusercontent.com/4172898/33702036-01b65a04-dadf-11e7-9f2f-7fc6dc2052fe.jpg)

Tested in S6 with Vulkan

**Comment by brujo5** [comment]
Also some times after load save state  cause weird colours 

![screenshot_20171206-233822](https://user-images.githubusercontent.com/4172898/33702169-b963fdf0-dadf-11e7-9400-6fa88602902f.jpg)

**Comment by unknownbrackets** [comment]
Does this happen in Vulkan and OpenGL, or only in Vulkan?

-[Unknown]

**Comment by leopard20** [comment]
Yeah. I noticed this as well (PoP Revelations). 
For me it was vulkan. I can't run this game on OpenGL (black screen).

**Comment by brujo5** [comment]
@unknownbrackets 

The freeze after load save state for second time happen in both vulkan and opengl 

Here opengl 
![screenshot_20171207-083017](https://user-images.githubusercontent.com/4172898/33723190-393b6c2c-db29-11e7-9fd7-a180bac3aad7.jpg)

The weird colour only happen in Vulkan 
Here other examples 
![screenshot_20171207-082918](https://user-images.githubusercontent.com/4172898/33723224-5768a098-db29-11e7-88d2-2478bd374793.jpg)
![screenshot_20171207-082838](https://user-images.githubusercontent.com/4172898/33723248-69526294-db29-11e7-924d-8f8d6e182c8c.jpg)

**Comment by XendorX** [comment]
just don't use save states PPSSPP has memory  stick also using SS corrupts your save file

**Comment by leopard20** [comment]
@XendorX 
Not true with all games.

**Comment by unknownbrackets** [comment]
Have you found any other games this happens in?

-[Unknown]

**Comment by brujo5** [comment]
For me happens in all games

**Comment by LunaMoo** [comment]
Not sure if it's same thing, but I can reproduce the freeze at least on windows and it's caused by 60 fps limiter starting from the recent fix to it that is ~ https://github.com/hrydgard/ppsspp/commit/e11f67ed74646055b2df389a472627bd593f0a65 It doesn't always result in freeze through, for example in GOW(demo) it causes a temporary black screen instead of temporary freeze.

**Comment by unknownbrackets** [comment]
Okay, that's fixed by #10382, but not sure about the funky colors.  That bug would've had the "load state twice" behavior, though, but ought to have black screened...

-[Unknown]

**Comment by brujo5** [comment]
Still freeze for me if force 60fps for (gow)  is enabled 

Anyway this settings is for God of war games

**Comment by LunaMoo** [comment]
@brujo5 did you build a ppsspp with that branch merged or just tested latest version from buildbot? ~ The fix wasn't merged yet.

Works for me, thx [Unknown].

**Comment by brujo5** [comment]
Latest from builbot

**Comment by unknownbrackets** [comment]
Do any of these problems reproduce now?  The issue LunaMoo described has been fixed (sorry), but I'm not sure if it's related to the funky colors or not.

-[Unknown]

**Comment by brujo5** [comment]
Funky colour still occur. 
The way to fix that (temporary fix) is load save state few times until normal colour appear

**Comment by unknownbrackets** [comment]
Has anything improved with the funky color issue?

-[Unknown]

**Comment by unknownbrackets** [comment]
Does this still happen in Vulkan?

-[Unknown]

**Comment by brujo5** [comment]
nope, thanks
