### ISSUE TITLE
Occasional full screen black frames

### ISSUE THREAD

**Issue by Clyybber** [hrydgard/ppsspp#10395]
Since updating to 1.5.4-~~26~~23 the screen is turning black sometimes for a frame or so.
I tested it only on Patapon 2. It is especially noticable when viewing the evolution trees of the patapons. 

NVIDIA SHIELD TABLET K1
With latest update (7.0) and vulkan

**Comment by Clyybber** [comment]
I should mention that it happens only with unbuffered rendering.

**Comment by hrydgard** [comment]
In general you are better off not using unbuffered, but I guess this might be worth taking a look at. I'm gonna guess that the issue actually started happening in either 1.5.4-23 or 1.5.4-9 (well, -4, but 9's the next build), feel like downloading some builds and confirming which one?

**Comment by Clyybber** [comment]
Ah yes, it happened with -23. Sorry my bad.

**Comment by hrydgard** [comment]
Thanks.

**Comment by unknownbrackets** [comment]
We could just only do that in buffered rendering...

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, that might be the way to go.

**Comment by Clyybber** [comment]
Any progress?

**Comment by hrydgard** [comment]
@Clyybber  I think this was fixed some time ago? Try the latest builds.

**Comment by Clyybber** [comment]
Tested on the latest -521, still happens on both OpenGL and Vulkan.

**Comment by Clyybber** [comment]
Any progress on this? Still happens in the latest experimentals.

**Comment by unknownbrackets** [comment]
Does this work now in v1.5.4-657-g3c16f8437 and later builds?

-[Unknown]

**Comment by Clyybber** [comment]
Fixed, thank you!
