### ISSUE TITLE
Vulkan device lost error on closing PPSSPP

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#10646]
As below picture
![TIM截图20190928103518](https://user-images.githubusercontent.com/5364709/65810359-071e6d00-e1dc-11e9-8e5d-9a949ba1117f.png)
It popup every time after closing.
When I start this version with my old version's setting file, it display black screen.

**Comment by unknownbrackets** [comment]
Does this still happen?  I think we improved some shutdown code.

-[Unknown]

**Comment by leoxxx** [comment]
It still happen in 1.7.4.

**Comment by hrydgard** [comment]
With the same message? Which GPU do you have @leoxxx, and have you updated to the latest drivers for it (if possible)?

**Comment by unknownbrackets** [comment]
Just to confirm, there are a few ways to exit PPSSPP.  Does it happen for all of them?

1. Click the X button in the top right.
2. Click the "Exit" button in the main menu.
3. Select File -> Exit in the menu.

Also, does it happen even if you don't run any game, or does it only happen if you start a game before quitting?

-[Unknown]

**Comment by leoxxx** [comment]
1&2 is error. 3 is O.K. It also happen when trans mode from vulkan to others.
It just happen when  ppsspp is closing.

**Comment by unknownbrackets** [comment]
Interesting.  It's definitely helpful to know that "Exit" in the main menu screen doesn't cause it.

I wonder if WM_CLOSE is causing the Vulkan stuff to get nuked before we fully shut down the render thread.  It'd be interesting if the WM_USER_RESTART_EMUTHREAD path works on such a device...

-[Unknown]

**Comment by leoxxx** [comment]
I don't understand these funtions. Then what's the difference among 2, 1&3?

**Comment by hrydgard** [comment]
This appears to be a duplicate of #11077 by the way.

**Comment by roioros** [comment]
Hi guys!!

I was testing the latest version (1.9) and I still have the same problem using Vulkan, every time I close the emulator, it gives this error:

**vkQueuePresentKHR failed! result=VK_ERROR_DEVICE_LOST**

I hope it can be solved in the future.

Thanks!!

**Comment by leoxxx** [comment]
> 
> 
> Hi guys!!
> 
> I was testing the latest version (1.9.0) and I still have the same problem using Vulkan, every time I close the emulator, it gives this error:
> 
> **vkQueuePresentKHR failed! result=VK_ERROR_DEVICE_LOST**
> 
> I hope it can be solved in the future.
> 
> Thanks!!

Yes, it still happen in 1.9.0.
@hrydgard @unknownbrackets

**Comment by leoxxx** [comment]
Fixed in v1.10.
Close.

**Comment by unknownbrackets** [comment]
Thanks for testing and confirming.

-[Unknown]

**Comment by roioros** [comment]
Hello!

Using the latest version (1.10.3) the error still persists and using the latest GIT version (v1.10.3-1190-gc61f9bfd0), now it gives this error:

![Untitled](https://user-images.githubusercontent.com/26861500/98740234-7bd54c00-2389-11eb-81b4-39ef51ab56a2.jpg)

**Comment by hrydgard** [comment]
How about now?

**Comment by leoxxx** [comment]
I think roioros's issue is another one.
Maybe buildagent' vulkan conflict with PPSSPP's one.

**Comment by roioros** [comment]
Hi!

Well, there is an advance, now it no longer gives the error using vulkan when no game is running (before, the error always appeared), but when I run a game and close the emulator, the error appears again, as shown in this picture:

![Untitled 2](https://user-images.githubusercontent.com/26861500/102716941-da151900-42bd-11eb-9ee7-5574199888c2.jpg)

But now there is another problem, there are sometimes the emulator does not close and the process remains in memory, I have to force the emulator to close it (I don't know if it's related to this or it's a new bug):

![Untitled 3](https://user-images.githubusercontent.com/26861500/102717140-201eac80-42bf-11eb-9cf1-f6cf30bd90dc.jpg)

**Comment by leoxxx** [comment]
It will run in background a while in WIN10 after you exit.
What's your OS?

**Comment by hrydgard** [comment]
Yeah that's not good. I'll look into it (but having problems reproducing the issue)

**Comment by roioros** [comment]
Any test that you need that I do, please let me know.

My PC:
Phenom II x4 965, 8 GB RAM, AMD HD 7970.
Windows 7 Ultimate SP1 (64 bits).

**Comment by Gamemulatorer** [comment]
This should improve now?

**Comment by hrydgard** [comment]
Very likely. I'm gonna close, let's reopen if it happens again.

**Comment by leoxxx** [comment]
@hrydgard 
Need reopen.

**Comment by leoxxx** [comment]
1.14 no error dialogbox.
