### ISSUE TITLE
My PPSSPP Crash and close everytime I open the app.

### ISSUE THREAD

**Issue by joshuacode751** [hrydgard/ppsspp#10663]
My ppsspp suddenly won't open. It crashes everytime i open the app and going back to previous version the app only makes black screen. Work on 1.4.2. Haven't had this issue before until i updated it to the new version. 

My phone is oppo a71. And the version 1.5.4-605 gives me no lag and every game works perfectly on the 1.54-605 Until i updated to new version the app wont let me open. It doesn't go to the menu. On 1.4.2 it let me open but it gave me huge performance drop.

**Comment by hrydgard** [comment]
You say that 1.5.4-605 works, which is the newest one that doesn't work?

**Comment by joshuacode751** [comment]
Yeah it works but after the i update to the latest version the app wont open anymore. I updated to 1.5.4-608 and the app wont open. It just crash and wont let me go to the menu. Even going back to 1.5.4-605 now the app wont open.

**Comment by hrydgard** [comment]
Try the PPSSPP.ini file thing I mentioned above then. That would confirm that it's Vulkan and we'll need to investigate, just like in #10662

**Comment by joshuacode751** [comment]
Where can i get the PPSSPP.ini? Btw my device dont support Vulkan.

**Comment by hrydgard** [comment]
Please read my post again, it tells you.

New versions of PPSSPP will try to use Vulkan first, if not already configured to use GL, and maybe that detection crashes?

**Comment by joshuacode751** [comment]
The app wont create the folder PSP. Should I create one?

**Comment by hrydgard** [comment]
There should be one already from your old version. If not, and it fails to create it then we have some kind of file permission problem. I've seen those getting resolved by restarting the phone...

**Comment by joshuacode751** [comment]
Got to say it doesn't work. Other phones work on the build but my phone. I tried on my brothers phone. Idk how to fix it but i already Reset my android but still doesn't work. I probably need to wait for the proper build. I just dont know what really happened after i update my ppsspp. It works when i Clear the data and force stop. But after i close ppsspp the app wont open again. Tnx for helping btw :)

**Comment by joshuacode751** [comment]
It actually works. Thank you. I copied my PPSSPP.ini file to my android ppsspp and change the GPUbackend to 0. Tnx bro highly appreciated

**Comment by hrydgard** [comment]
Well, I don't consider this case closed until we make it so it doesn't crash if it has Vulkan enabled. It should safely switch over to OpenGL and not crash..

**Comment by hrydgard** [comment]
Any chance you can switch back to 3 and get some ADB logs (as in #10622) ?

**Comment by tausifj15** [comment]
Sur my device support vulkan but build from 603 to all are crashing while previous builds are working 😭

**Comment by hrydgard** [comment]
@tausifj15 Ugh. Got a crash log from adb?

**Comment by joshuacode751** [comment]
I can't get adb to work on my phone. Cant provide you any crash log sorry.

**Comment by hrydgard** [comment]
I think I've found the cause of this, there will be a fix fairly soon.

**Comment by joshuacode751** [comment]
Thank you for finding the issue. :)
