### ISSUE TITLE
Phantasy Star Portable 2 Android Problems

### ISSUE THREAD

**Issue by chaosenvoys** [hrydgard/ppsspp#10735]
What happens?
On open gl, crashes or freezes after selecting story mode in new save and my old save.
On vulkan, it has graphic glitches everywhere, where the screen has black haze moving around, and crashes when attempting to load data

What *should* happen?
I last played this game on my note 4, and it runs flawlessly on ppsspp then, i forgot what version that was..

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
I'm using galaxy s9 with exynos 9810, gpu Mali-G72 MP18-EMEA, and ppsspp 1.5.4 gold edition from play store

**Comment by hrydgard** [comment]
There have been many changes since 1.5.4 which will go into 1.6, so these bugs might already have been fixed, but of course I'm not sure. You could try a new development build from  https://buildbot.orphis.net/ppsspp/  , you can install that in parallel with the gold version. However any save states you make with it won't load in Gold until the next official version.

**Comment by chaosenvoys** [comment]
@hrydgard i've installed the latest build from orphis, but rthe problem still exist
On vulkan there are no more black haze moving around the screen, but it stutters and failed to load..
On open gl, still crashes or freezes on now loading screen after selecting story mode..

**Comment by fahadfoyjur** [comment]
Will there be any major changes in 1.6 update?

**Comment by hrydgard** [comment]
OK, thanks for testing.

@fahadfoyjur   What you find on buildbot is work-in-progress versions that will become 1.6 eventually. The major changes so far are multicore rendering for GL and a number of other optimizations and fixes.

**Comment by fahadfoyjur** [comment]
Thanks Hrydgard sir , For your reply

**Comment by unknownbrackets** [comment]
Story mode doesn't crash my Pixel when playing this.  It plays a video right then, though, and get some static when it starts playing.  However, maybe this is some non-power-of-two issue?

No crash when loading savedata, and no black haze, but Adreno.  Maybe this is related to that Mali transition bug?

-[Unknown]

**Comment by chaosenvoys** [comment]
@unknownbrackets the bug happens on my lg v20 too.. but lgs software is prone to bugs with ppsspp so, yeah.. doesn't have another phone with adreno to test it out though..

**Comment by chaosenvoys** [comment]
@unknownbrackets can you share your ppsspp settings? I wamt to try playing it with your settings..

**Comment by unknownbrackets** [comment]
Hmm, the settings I tested with were:

 * Buffered rendering, simulate block transfer enabled.
 * Auto frameskip 1.
 * 1x render resolution, native device display resolution.
 * Hardware transform and tessellation on
 * Lazy caching/retain changed textures off, disable slower effects unchecked.
 * Fast memory on.
 * Emulated CPU clock at auto.

-[Unknown]

**Comment by hrydgard** [comment]
All of you have verified good ISO files? It's strange that results would differ so much.

**Comment by unknownbrackets** [comment]
Hm, mine came straight from my disc, but curiously the crc of it doesn't come up with any results on Google.  I guess I can recheck the physical disc, maybe I had a read error...

-[Unknown]

**Comment by unknownbrackets** [comment]
Okay, pulled my disc again and the crc is good now.  Still doesn't crash though.

Did those settings help in some way?  If there's a setting causing crashes we want to fix it or at least know about it.

-[Unknown]

**Comment by hrydgard** [comment]
How is this now on the latest builds?

**Comment by hrydgard** [comment]
Outdated and no response, closing.
