### ISSUE TITLE
Metal Gear Acid 2 Weird Graphics (Physics?) Bug?

### ISSUE THREAD

**Issue by TideGear** [hrydgard/ppsspp#10942]
Here's an odd one. At the start of Snake's turn, his backpack was stretched up over his head. I don't know if this is a physics bug with the original game or a PPSSPP bug or what. It might be worth pointing out he had just climbed a ladder last turn, but I don't recall how he looked then. Using the in-game, in-mission save and reloading it removes the issue. Also, making Snake move removes it.

![ulus10077_1 00_0](https://user-images.githubusercontent.com/16357059/39041273-4c9056f2-443d-11e8-8b7e-a3f93bd2ccd0.jpg)

Savestate: 
[MGA2 Stretched Backpack.zip](https://github.com/hrydgard/ppsspp/files/1931417/MGA2.Stretched.Backpack.zip)

This was with v1.5.4-919-g19ddeea8e on a Galaxy S9+ (USA).

**Comment by hrydgard** [comment]
Please check if it happens on the real hardware, can't fix it if it does as it's then a game bug. If it doesn't, it might be a CPU emulation math bug similar to the Tekken leg shake or something. But I doubt it.

**Comment by TideGear** [comment]
Hmm, not sure how to test this on hardware. Can't load the state there...

**Comment by TideGear** [comment]
Ok, so I transferred my save to an actual PSP. I can't easily go back to the mission proper without replaying almost the whole game, but I can go back to that mission and choose from different modes like "Stealth", "Eliminate", etc. I chose the Eliminate mode (kill all enemies) for the sake of speed, and got to the same ladder. I went up and down probably more than 10 times, and I didn't get the weird backpack effect. Hope that's a decent test for you. Most of the mission is same as story mode, and it's the same map, enemy layout, etc. Shouldn't affect physics? Also, I can confirm that Snake's backpack does have simple physics/animation. I've seen it bounce in other scenes.

**Comment by TideGear** [comment]
I found some more detail about this weirdness. Try this savestate...
[Weird Part 2.zip](https://github.com/hrydgard/ppsspp/files/1934365/Weird.Part.2.zip)

End the turn and hold triangle to fast forward through turns. Watch as Snake's backpack slowly creeps up and Venus's... chest does too. It takes a lot of turns to happen. I'm starting to think the ladder isn't involved, and it may be that the camera movement is affecting physics somehow?

I've briefly tried getting this to happen elsewhere, but no luck.

**Comment by hrydgard** [comment]
Have you been able to check and see if it happens if you run PPSSPP on a PC as well?

**Comment by LunaMoo** [comment]
I think the important question here would be - if the game was regularly reloaded from normal save before the glitch happened? Because if not, that could just be a random glitch which could as well happen on real hardware if game was played long enough.
 As we know games aren't perfectly stable software and abusing savestates simulates a situation of never restarting which with time sooner or later goes really bad with most games which combined with the comfort of savestates happens to be a pretty common problem, but isn't really anything that could be fixed, at most we could have some sorts of warning printed on screen if too much time passed from last game boot recorded in the current state when savestate is made or loaded.

**Comment by TideGear** [comment]
Ok, thanks for your advice!

I can now confirm that this is a PPSSPP bug, both on Vulkan and OpenGL. I tested on real PSP hardware, Android, and Windows (both v1.5.4-931-g9c059a7b6). I managed to make a proper PSP save by loading the savestate, then saving using the in-game, in-mission save. ("Duh" to me!) I found a few things out...
1. This actually is always happening anywhere in this mission/map! You can exit the mission/map and go back into it, and it will be slowly happening at the very start of the mission/map. You don't even have to forward through turns. Just sit an watch both Snake and Venus deform. I even loaded my own proper non-state save in PPSSPP, returned to the mission/map in another mode, and it still happens.
2. It only happens on PPSSPP and not real PSP hardware.
3. I haven't found another mission/map yet that it happens on. I only briefly tried a few, but I wouldn't be too surprised if it can elsewhere with other physics objects. Who knows? So, I hope there's more than a band-aid solution to this.

Here's a proper non-state save to try...
[MGA2 Physics Weirdness Save (Not State).zip](https://github.com/hrydgard/ppsspp/files/1935322/MGA2.Physics.Weirdness.Save.Not.State.zip)
...Use "Continue" on the title screen, not "Load". You can exit and re-enter the mission/map, "??? LV1", (you can skip the intro cutscene with start) and it will still happen slowly.

**Comment by TideGear** [comment]
By the way, I rarely use savestates, because I'm a bit of a gaming purist. I tend to only use in-game saving with occasional savestates as just-in-case backups. I like savestates for bug reports though.

**Comment by TideGear** [comment]
Just saw this happen on another mission/map, "??? LV4", a battle with Metal Gear. This time it was hard to see it because it was resetting the problem whenever control was given back to Snake or Venus, not just on movement. Metal Gear's turns and attacks can take a long time, so I guess the physics occasionally had enough time to noticeably bug out before control was returned and physics were reset.

**Comment by Rafidmuhaiminwafi** [comment]
Tried using 'Buffered Rendering' mode, because I solved #10296 using this mode.

**Comment by Rafidmuhaiminwafi** [comment]
Sorry #10958

**Comment by TideGear** [comment]
@Rafidmuhaiminwafi I don't think that will help an issue like this, but thank you.

**Comment by TideGear** [comment]
By the way, I've found this even happening in the tutorial stage at the beginning of the game! Apparently, it's widespread, just only noticeable if you pause to think for a while, or the enemy's turn takes a while.

**Comment by TideGear** [comment]
Just tested in v1.6.3-536-g7b34eaa1f, and this issue remains.

**Comment by hrydgard** [comment]
It's possible but not by any means confirmed that this could be caused by the same precision issue affecting Tekken and others (#12082).

**Comment by TideGear** [comment]
@hrydgard Can I help in any way?

**Comment by hrydgard** [comment]
Test it later when we've merged a (maybe partial) fix for #12082 :)

**Comment by Gamemulatorer** [comment]
Can still reproduce this cpu glitch
![Screenshot_20221213_023118_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/207126851-68450171-c43c-4082-a773-a8b86010dc90.jpg)
