### ISSUE TITLE
Brothers in arms blackscreen  problem 

### ISSUE THREAD

**Issue by fahadfoyjur** [hrydgard/ppsspp#10978]

**Comment by fahadfoyjur** [comment]
This game make emulator hang , and blackscreen :(

**Comment by marosis** [comment]
Is this problem in 1.5.4 from Google play?

**Comment by leopard20** [comment]
@hrydgard @unknownbrackets 
This is actually the issue I reported a while ago, but closed it because I assumed it should be fixed (I didn't have the game anymore to test it)

**Comment by marosis** [comment]
@fahadfoyjur do you have still this problem? If not please close it

**Comment by benderscruffy** [comment]
v1.7.1-210-g9bda7cb64
still happens 
when you start a new game it is suppose to come up with a video but instead nothing but a black screen
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2623128/ppsspplog.zip)

**Comment by benderscruffy01** [comment]
this goes ingame now
can be closed
![brothers](https://user-images.githubusercontent.com/48821663/54876199-dfbea000-4e46-11e9-9de5-726c077ff1a1.PNG)

**Comment by hrydgard** [comment]
Cool, would be interesting to know which change got it to work, but closing.
