### ISSUE TITLE
GPD XD: PPSSPP crashing when switching apps

### ISSUE THREAD

**Issue by tiagaoextremo** [hrydgard/ppsspp#11063]
### What happens?

Usually when playing some rpgs i would check from time to time a walkthrough in .txt format switching between the txt reader and the ppsspp emulator. For the latest versions the emulator is crashing everytime i would switch to another app, even if i press the home button the emulator crashes when i return to it.

### What *should* happen?

It should be able to switch between the ppsspp emulator and any other apps.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

GPD XD, RK3288, Mali T760, Android Kitkat 4.4.4, nightly build version v1.5.4-993-gab65c5210.

**Comment by tiagaoextremo** [comment]
Should i provide some kind of logcat?

**Comment by hrydgard** [comment]
If you can, please do.

**Comment by tiagaoextremo** [comment]
Sorry about the noob question, but how should i proceed in order to do it?

**Comment by ChurroBoi** [comment]
I experience this as well. I can get a log if you need?

**Comment by tiagaoextremo** [comment]
@ChurroBoi I would appreciate that, if you don't mind.

**Comment by ChurroBoi** [comment]
@hrydgard @tiagaoextremo Here ya go. 
[ppsspp_switchapp-crash.txt](https://github.com/hrydgard/ppsspp/files/2029013/ppsspp_switchapp-crash.txt)

**Comment by hrydgard** [comment]
Thanks. It's very likely to be dying in or close to GLQueueRunner::RunInitSteps and it looks similar to previous GPD stack traces where it blew up on minor GL errors..  Need to get it error-clean.

**Comment by tiagaoextremo** [comment]
Thanks @ChurroBoi for posting the log and thanks @hrydgard for looking into it.

**Comment by 03bgood** [comment]
Yeah, this keeps happening to me as well. I hit the home button and when I return to the app, it either freezes up on me or I get a black screen (which is fixed by going into settings) is the developer aware of this situation?

**Comment by tiagaoextremo** [comment]
I just tried latest version (v1.6.2-4-g30de8194a), still the same. Fingers crossed that this will be fixed.

**Comment by tiagaoextremo** [comment]
Hi @hrydgard i'm asking this just for curiosity. This issue happening with the GPD XD it's some thing that could be fixed someday or it's more complicated than it seems? I'm still trying once a week the nightly builds, but it's the same crashing. Thanks.

**Comment by hrydgard** [comment]
Right, I do plan to fix this...

**Comment by hrydgard** [comment]
Can you try this again with the latest build?

**Comment by tiagaoextremo** [comment]
Hi Henrik. I just tried the build v1.6.3-547-g8a74e6f7b. Still crashing. I also tried the v1.6.3-548-geba6c00a8 and the same results, whether it's the home button or i exchange to another app still crashes the emulator.

**Comment by hrydgard** [comment]
Thanks for testing @tiagaoextremo . Sorry it didn't help, I'm running out of ideas on how to fix it...

**Comment by tiagaoextremo** [comment]
[ppsspp_crashing_gpd_xd.txt](https://github.com/hrydgard/ppsspp/files/2454185/ppsspp_crashing_gpd_xd.txt)

I hope it worked. I didn't knew how to get a ADB log, but i looked into google and i'm assuming it's ok. After setting everything i just turned on the device, opened PPSSPP and after loading a game i pressed the home button, which made the emulator crashed. This is the log generated after that. Thanks again.

**Comment by unknownbrackets** [comment]
You can see instructions here:
https://github.com/hrydgard/ppsspp/wiki/How-to-get-an-adb-logcat-from-a-PC

It looks like some of the log information wasn't captured in that log above.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah that's missing the crash itself. @tiagaoextremo  btw does it make a difference whether you set Display Resolution to native or 2x or something?

**Comment by tiagaoextremo** [comment]
[ppsspp.log](https://github.com/hrydgard/ppsspp/files/2454250/ppsspp.log)

Thanks @unknownbrackets. I followed your instructions. Is it correct now?

@hrydgard I just noticed that PPSSPP crashes when i select any other option besides "2X PSP", the other options Native, Auto or 1X crashes the emulator. Rendering resolution allows me to change with no issues.

**Comment by hrydgard** [comment]
Right ok, it'll be defaulting to 2X I guess and then any change will crash.

**Comment by unknownbrackets** [comment]
Thanks, this is a good log.

```
I/WindowState(  486): WIN DEATH: Window{42d20918 u0 org.ppsspp.ppsspp/org.ppsspp.ppsspp.PpssppActivity}
W/ActivityManager(  486): Exception thrown during pause
W/ActivityManager(  486): android.os.DeadObjectException
W/ActivityManager(  486): 	at android.os.BinderProxy.transact(Native Method)
W/ActivityManager(  486): 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:660)
```

Hm, that's interesting?  Anyway, seems you restarted it, and then:

```
I/PPSSPP  ( 3101): GPU_GLES: DeviceLost
I/PPSSPP  ( 3101): NativeShutdownGraphics
I/PPSSPP  ( 3101): NativeShutdownGraphics done
I/PPSSPP  ( 3101): GL submission thread paused. Frame=0
I/PPSSPP  ( 3101): Leaving emu thread
I/PPSSPP  ( 3101): EmuThreadJoin - joined
I/PPSSPP  ( 3101): ThreadEnd
D/MaliGPU ( 3101): GPU DDK VERSION: [r4p1-00rel0-11-8@0]
F/libc    ( 3101): Fatal signal 11 (SIGSEGV) at 0x0000001f (code=1), thread 3116 (AndroidRender)
I/DEBUG   (  144): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  144): Build fingerprint: 'google/hammerhead/hammerhead/4.4.4/KTU84Q/eng.skelton.20150927.102903:eng/test-keys'
I/DEBUG   (  144): Revision: '0'
I/DEBUG   (  144): pid: 3101, tid: 3116, name: AndroidRender  >>> org.ppsspp.ppsspp <<<
I/DEBUG   (  144): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0000001f
I/DEBUG   (  144): backtrace:
I/DEBUG   (  144):     #00  pc 00a58b20  /data/app-lib/org.ppsspp.ppsspp-1/libppsspp_jni.so
I/DEBUG   (  144):     #01  pc 00a58943  /data/app-lib/org.ppsspp.ppsspp-1/libppsspp_jni.so
I/DEBUG   (  144):     #02  pc 00a426f3  /data/app-lib/org.ppsspp.ppsspp-1/libppsspp_jni.so (__gxx_personality_v0+330)
I/DEBUG   (  144):     #03  pc 0003c570  /system/lib/libc.so (__gnu_Unwind_Backtrace+152)
I/DEBUG   (  144):     #04  pc 0003ca90  /system/lib/libc.so (___Unwind_Backtrace+20)
...
I/DEBUG   (  144):          789bb508  773299d9  /data/app-lib/org.ppsspp.ppsspp-1/libppsspp_jni.so (GLRShader::~GLRShader()+12)
```

So seems like we're still killing a GLRShader during restore?

-[Unknown]

**Comment by hrydgard** [comment]
Indeed so, will look into that.

**Comment by hrydgard** [comment]
OK, checked in another potential fix... let's hope it's enough this time.

**Comment by tiagaoextremo** [comment]
Hi Henrik, i just tried this build. Still the same crashing. Would you like a fresh log or is there any other way a noob like me could help?

**Comment by hrydgard** [comment]
Yes please, without a device, logs are the most useful way we have...

**Comment by tiagaoextremo** [comment]
[ppsspp.log](https://github.com/hrydgard/ppsspp/files/2498474/ppsspp.log)

Here goes. Hope it helps. :)

**Comment by unknownbrackets** [comment]
Darn, still a GLRShader destructor in the stack...

-[Unknown]

**Comment by hrydgard** [comment]
Alright, can you give it another go @tiagaoextremo ?  Thanks!

**Comment by hrydgard** [comment]
Oh duh, I see what I missed. Don't worry about it, thank you for all your testing, you'll have to test one more I'm afraid :)

**Comment by hrydgard** [comment]
Github clearly has some problems, it's sometimes showing me old versions of this thread so sorry for any double posts. But I've committed a yet another fix :) Please give it a try. Really want to get this done before the release...

**Comment by tiagaoextremo** [comment]
Hi, Henrik. First let me say thanks again. It's been finally fixed! Now i can play a few rpgs again checking some faqs and the emulator isn't crashing anymore. Also, now i can change the resolution to 1x or 2x, isn't crashing also. Your work is highly appreciated! Also thanks to @unknownbrackets for tips and helping me to create a proper log.

**Comment by unknownbrackets** [comment]
Hurray - thanks for validating, glad to hear it's fixed.

-[Unknown]

**Comment by hrydgard** [comment]
Oh awesome! Thanks yet again for all your testing!

**Comment by Emulatorer** [comment]
Look like this issue has revive see #12843
