### ISSUE TITLE
GOW Chains of Olympus black squares

### ISSUE THREAD

**Issue by weihuoya** [hrydgard/ppsspp#11123]
### What happens?
only opengl backend, this issue accured in some scenes, not every place. Around the green particles.

![screen_gl](https://user-images.githubusercontent.com/3827333/40878089-7ec652fe-66be-11e8-8925-6e685599d8a1.jpg)

### What *should* happen?
vulkan backend is ok.
![screen_vk](https://user-images.githubusercontent.com/3827333/40878092-87a760e8-66be-11e8-9abc-bfc556d0a4f3.jpg)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

s7 edge, 820, ppsspp-v1.6.2-14-gad1b75292-android.apk

**Comment by leopard20** [comment]
The health bar seems glitched too. Look at the misaligned borders.

**Comment by leopard20** [comment]
I think this pull request will fix it: https://github.com/hrydgard/ppsspp/pull/10981

**Comment by unknownbrackets** [comment]
Does it happen on desktop too, or only mobile?  It might be dual source blending.

-[Unknown]

**Comment by weihuoya** [comment]
I will test later.

**Comment by cheding09** [comment]
Happens to me too .
sometimes I try checking and unchecking the block transfer effect . somehow works but makes the game unplayble .

Backend : OpenGL
GPu : Mali-450

**Comment by weihuoya** [comment]
PC has this issue, too.

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by weihuoya** [comment]
I can't run 1.6.2 release version on my old laptop now, ppsspp stop running on startup, weird.
I will dump on other pc tomorrow.

windows 10, 1709.

**Comment by weihuoya** [comment]
[UCAS40198_0001.zip](https://github.com/hrydgard/ppsspp/files/2066692/UCAS40198_0001.zip)

**Comment by unknownbrackets** [comment]
It draws Texture L0: 0x089cdce0 (64x64) using alpha blend src.a/1-src.a, everything looks reasonable.

This is probably a state flushing issue, I suppose, given that the dump draws fine (note: it draws the blended image over the top later which makes it not fine anymore, but you can see it render properly in the GE debugger.)

I get a reproducible NVIDIA driver crash when running through the debugger on the dump, though, ugh.  

It's just using alpha blend though, hmm.

Also @hrydgard I'm seeing that crazy evil thing where it draws a bunch of tiny tiles near the end of the frame.  I don't think I've noticed the demo doing that - does GoW normally do that?  Use the dump in Vulkan, break on texture 0x089cdce0, then just hold down step prim.  I'm seeing 8x15 squares.

Also the static is weird.  This is with buffered rendering and block transfer both enabled, and "disable slower effects" unchecked?

-[Unknown]

**Comment by weihuoya** [comment]
yes, buffered rendering and block transfer both enabled, "disable slower effects" unchecked

**Comment by weihuoya** [comment]
there are another black squares.
![2](https://user-images.githubusercontent.com/3827333/41141818-ff7ce8ac-6b25-11e8-80f9-81f323798300.jpg)


![1](https://user-images.githubusercontent.com/3827333/41141825-04017104-6b26-11e8-8861-4ee9e057d087.jpg)

**Comment by Jeves** [comment]
WTF!?

**Comment by Emulatorer** [comment]
Yeah in a real psp there's no black square in the red/green orbs watch here https://youtu.be/l0ou8oP-6LE

**Comment by Gamemulatorer** [comment]
Latest ppsspp git build v1.9.3-754 doesn't have black square in the red & green orbs
![Screenshot_20200511-042140](https://user-images.githubusercontent.com/37603562/81509764-a04f5d80-933f-11ea-908c-bc309f6b6eea.png)
![Screenshot_20200511-042054](https://user-images.githubusercontent.com/37603562/81509790-ba893b80-933f-11ea-96a0-884604c7222d.png)

### phone specs
Android 6.0.1
OpenGL 2.0
Mali-450

**Comment by unknownbrackets** [comment]
Cool, I'd be interested in knowing what change fixed it.  I think we have fixed a few state issues.

-[Unknown]

**Comment by Gamemulatorer** [comment]
> Latest ppsspp git build v1.9.3-754 doesn't have black square in the red & green orbs anymore :)
> ![Screenshot_20200511-042140](https://user-images.githubusercontent.com/37603562/81509764-a04f5d80-933f-11ea-908c-bc309f6b6eea.png)
> ![Screenshot_20200511-042054](https://user-images.githubusercontent.com/37603562/81509790-ba893b80-933f-11ea-96a0-884604c7222d.png)
> 
> ### phone specs
> Android 6.0.1
> OpenGL 2.0
> Mali-450

@hrydgard this should be added to v1.10.0 milestone Issue of this already been fixed, but idk what build that fix this issue ʘ‿ʘ

**Comment by Saramagrean** [comment]
Light around the monster eyes, still a black square. should seperate issue?

![GoW-CoO-1](https://user-images.githubusercontent.com/26355472/81943203-48597500-9625-11ea-8f2e-b8f0082f8097.png)

GE Dump = [NPUG80325_0001.zip](https://github.com/hrydgard/ppsspp/files/4628824/NPUG80325_0001.zip)

**Comment by hrydgard** [comment]
Nah, let's reuse this.

**Comment by Gamemulatorer** [comment]
OpenGL issue is already fixed the remaining issue is on Vulkan now.

**Comment by hrydgard** [comment]
Weird, I didn't know this happened on Vulkan.

I'll take another look.

**Comment by Saramagrean** [comment]
Yeah, this issue happen on Vulkan only and latest git build 882 still present.

Test on Windows 10 x64 (CPU: i5-6200U, GPU: Intel HD Graphics 520)

New GE dump. [NPUG80325_0002.zip](https://github.com/hrydgard/ppsspp/files/4644143/NPUG80325_0002.zip)

**Comment by Gamemulatorer** [comment]
Just testing the dump zip and it's totally ok on OpenGL hope Vulkan too soon..
![Screenshot_20200526-112231](https://user-images.githubusercontent.com/37603562/82857360-596a8600-9f43-11ea-97e3-350aa0bada94.png)

**Comment by hrydgard** [comment]
The dump looks OK on Vulkan on my PC (nVidia).

**Comment by hrydgard** [comment]
I dunno, haven't gotten any reports of this in a while. I'll close.

**Comment by Gamemulatorer** [comment]
> Light around the monster eyes, still a black square. should seperate issue?
> 
> happen on Vulkan only, OpenGL and D3D11 look fine.
> 
> ![GoW-CoO-1](https://user-images.githubusercontent.com/26355472/81943203-48597500-9625-11ea-8f2e-b8f0082f8097.png)
> 
> GE Dump = [NPUG80325_0001.zip](https://github.com/hrydgard/ppsspp/files/4628824/NPUG80325_0001.zip)

Redmi Note 9 Mali GPU Helio G85
PPSSPP v1.11.3-github apk
Vulkan Backend
![Screenshot_2021-05-19-01-26-03-939_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/118696980-6b72c200-b841-11eb-95d8-d16607e5edb5.jpg)
