### ISSUE TITLE
[Vulkan] Weird shader bug (Z-fighting?)

### ISSUE THREAD

**Issue by Leopard20** [hrydgard/ppsspp#11583]
In certain games, you can see a bunch of weird lines on some surfaces (particularly those that have some sort of "reflection" or "shining" effect)
Here are some examples:
Ace Combat Joint Assault -> Aircraft and missiles
![screenshot_2018-11-24-21-52-23-157_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/48971809-18cf3b00-f034-11e8-8650-256710efa0c5.png)
![screenshot_2018-11-24-21-53-13-392_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/48971817-297fb100-f034-11e8-8689-4336c9b8e453.png)

NFS Underground -> Windows
![screenshot_2018-11-24-21-53-33-723_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/48971822-3bf9ea80-f034-11e8-838c-7e8e0f2d4a0f.png)
![screenshot_2018-11-24-21-53-45-144_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/48971824-52a04180-f034-11e8-916d-cc03b9d55680.png)

Silent Hill Shattered Memories -> Walls
![screenshot_2018-11-24-21-55-17-176_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/48971842-a6ab2600-f034-11e8-9f79-f142e7ffe178.png)

OGL works fine in all above games.

Device: Mi 5s Plus, Snapdragon 821
OS: Android 8.0

**Comment by unknownbrackets** [comment]
Can you try creating GE frame dumps for any of these scenes?

I'd guess something with render-to-texture or depal.

-[Unknown]

**Comment by leopard20** [comment]
For some reason, the debugger keeps saying "waiting for a game to start...". Any idea what's wrong? (Android, firewall disabled, website access on)

**Comment by unknownbrackets** [comment]
Hm... if it detects the game id, are you in the pause menu?  Try pausing and resuming perhaps?

-[Unknown]

**Comment by leopard20** [comment]
Doesn't help. Already done that. 
I'll dump one on my PC later! 😉😂

**Comment by leopard20** [comment]
Wait. I got it! The game shouldn't be paused. Derp.

**Comment by hrydgard** [comment]
Looks somewhat like Z fighting.. on the PSP, doing both base texture and environment map requires two passes. If the GPU somehow optimized the two shaders differently this kind of thing could happen... Usually I think drivers take special care to compute accurate vertex coords though. Dunno...

**Comment by leopard20** [comment]
@hrydgard 
Yeah I think it's my driver acting up. I don't recall having these problems before. 

@unknownbrackets 
Here you go:
[Download.zip](https://github.com/hrydgard/ppsspp/files/2612665/Download.zip)
This should be more than enough! Although I couldn't get a dump from Silent Hill. The game would just freeze completely.

**Comment by unknownbrackets** [comment]
Does using software transform (not software rendering, just unchecked hardware transform) help?  Does software skinning affect it?

This seems to use weights + environment mapping + an unusual `< ff` alpha test, at least in Ace Combat.

-[Unknown]

**Comment by leopard20** [comment]
No. Neither software transform nor software skinning affect any of those games (in terms of this issue of course)

**Comment by leopard20** [comment]
@unknownbrackets 
> This seems to use weights + environment mapping + an unusual < ff alpha test, at least in Ace Combat.

Could it be a driver bug? If so maybe I could test on PC to be sure.

**Comment by unknownbrackets** [comment]
It doesn't look funny when I run the dump.  If you run that dump on your phone (just open as a game), does it look funny still?

-[Unknown]

**Comment by leopard20** [comment]
Yes. Does it mean it's a driver bug?

**Comment by leopard20** [comment]
Funny thing: When I use upscaling, the game looks fine for like a second then gets weird again! LoL

**Comment by leopard20** [comment]
@unknownbrackets I just updated my Vulkan API to the latest version available for my OS (1.0.66) but the issue still persists. 
Can you test it on your phone too please?

**Comment by unknownbrackets** [comment]
Yes, seems like a driver bug.

-[Unknown]

**Comment by leopard20** [comment]
Oh, damn. :(

**Comment by leopard20** [comment]
@unknownbrackets I just tested v1.6.3 and it works fine. But v1.6.3-312 didn't. So probably not a driver bug.
Would you like for me to test some builds between those two? I so, can you please point me to a few ones that could be the culprit?

**Comment by Metalwario64** [comment]
@leopard20  I have this issue with Silent Hill: Shattered Memories, but using 1.6.3 didn't render the lighting properly in the Vulkan driver for me. The latest version works, but with the line issue. Perhaps that's why it seemed to not have the issue (just a guess)?

In Silent Hill: Shattered Memories at least, it appears that the lines are the cast shadows from the flashlight being rendered incorrectly. Since it scrolls like the shadows, and their shape seems off, I don't think it is z-fighting in that instance at least. I can't speak for the other games.

Here's how it looks on a PSP (from a Youtube video I found, as I have no means of capturing from a PSP directly, so apologies for the quick and dirty picture quality):
![sm hw](https://user-images.githubusercontent.com/34078978/49304206-a29a6080-f499-11e8-9008-fcc54121ef42.png)

Here's how it looks in PPSSPP:
![sm emu](https://user-images.githubusercontent.com/34078978/49304215-a928d800-f499-11e8-9a9c-61b3111b0c13.png)

I am running Windows 10 on an Intel G4560 processor with an Nvidia GT 1030 GPU.

**Comment by leopard20** [comment]
@unknownbrackets I bisected the issue. And it's very interesting. Once again it's caused by this: https://github.com/hrydgard/ppsspp/commit/06340bfa9c92d0ad8423ca3cacdd84795f71094a
Remember this?
https://github.com/hrydgard/ppsspp/issues/11227

Can you please revert that commit? Or at least find a better "workaround"?

**Comment by hrydgard** [comment]
@Metalwario64  This game is using some extremely advanced tricks to implement real depth shadow mapping on the PSP's hardware, which doesn't really support it. If you take a few GE dumps it will make it more convenient to figure out what's going wrong - can you do that (https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump)? I think we had some issue already, but if you don't find a good one please create a new one.

**Comment by leopard20** [comment]
@unknownbrackets The issue doesn't seem to have been fixed completely. In Ace Combat, everything looks fine in the menu:
![screenshot_2018-12-03-15-04-37-720_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/49371577-2f008980-f70d-11e8-89b2-5eb563e64840.png)
However, the issue is still present in missions:
![screenshot_2018-12-03-15-04-47-320_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/49371636-6707cc80-f70d-11e8-8a76-adf869d748d1.png)


There are no issues in Silent Hill or NFS however.

**Comment by leopard20** [comment]
So....what about this one? Don't you guys want to reopen?

**Comment by unknownbrackets** [comment]
Just don't use Vulkan, the driver is broken either way.  I'm not going to play a game of "break this game, fix this game" and I'm not going to create an intricate list of thousands of game ids with a "maybe preferrable version of the Adreno driver bugs."

Use GLES for now and wait for Adreno to release a better driver.

-[Unknown]

**Comment by leopard20** [comment]
@unknownbrackets Jeez. Simmer down dude.

**Comment by unknownbrackets** [comment]
It's still a bug, so we should keep it open.  But like I said: it's probably only fixable by Adreno.

-[Unknown]

**Comment by hrydgard** [comment]
Got a report with another instance, in Naruto - and yes, it's also Adreno.
![screenshot_20181116-214514](https://user-images.githubusercontent.com/130929/50043762-52ff8b80-007a-11e9-8397-45e62a2cfdc4.png)
![screenshot_20181116-214530](https://user-images.githubusercontent.com/130929/50043763-5430b880-007a-11e9-9ac4-17bc4db5355a.png)

**Comment by leopard20** [comment]
@unknownbrackets So far the impact seems is positive! The issue is gone!

I'll check more thoroughly later!

**Comment by leopard20** [comment]
All games I tested (including Project Diva) work fine. 
I'm not sure about the Narutu game though. I don't have this game.

I think it's safe to say it's fixed completely.

**Comment by weihuoya** [comment]
Naruto still have this issue. adreno 530, vulkan 1.0.61.

**Comment by weihuoya** [comment]
adreno driver really do evil things. naruto work fine on android 7.0. after update to android 8.0, opengl 3.2 v@269, this game get stuck on opengl backend, and get display issue on vulkan backend.

**Comment by hrydgard** [comment]
@weihuoya  got a frame dump with the problem? https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by weihuoya** [comment]
ok, wait a few days, I don't have a pc to dump.

**Comment by hrydgard** [comment]
There is now a way to get frame dumps even on Android, as described in my link. Though maybe tricky to upload the dump to GitHub...

**Comment by weihuoya** [comment]
awesome job. it works.
[recording.zip](https://github.com/hrydgard/ppsspp/files/2714168/recording.zip)

**Comment by unknownbrackets** [comment]
Can we call this issue fixed now?

-[Unknown]

**Comment by leopard20** [comment]
@unknownbrackets No. The problem still exists in Naruto:
![Screenshot_2019-09-08-13-55-31-980_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/64486303-b81a9300-d240-11e9-843c-09e7cc32a566.png)
[recording (2).zip](https://github.com/hrydgard/ppsspp/files/3587469/recording.2.zip)

**Comment by Gamemulatorer** [comment]
> @unknownbrackets No. The problem still exists in Naruto: ![Screenshot_2019-09-08-13-55-31-980_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/64486303-b81a9300-d240-11e9-843c-09e7cc32a566.png) [recording (2).zip](https://github.com/hrydgard/ppsspp/files/3587469/recording.2.zip)

If you add Naruto Shippuden to PixelDepthRounding compat.ini does it help?

**Comment by unknownbrackets** [comment]
Just for context on the bug: Naruto is drawing the dirt over the grass using a `>=` depth test and depth write disable, plus writing stencil (`FF` on 5551.)  There's no actual stencil test, though (it's ALWAYS.), and stencil is only written (REPLACE) on all pass.

So that's the scenario of the driver bug - it might incorrectly write stencil otherwise.  A bit unclear if that'd be worse, it seems to stencil out the sky for some reason (everything but the sky has stencil set.)  Might just miss some sunflare effects, but might also be used for special attacks.

If this is happening on newer Adreno devices or drivers (i.e. not with this workaround), then I'd guess it could be an issue with exactness, but the gaps seem too wide for that.

-[Unknown]

**Comment by Gamemulatorer** [comment]
> > @unknownbrackets No. The problem still exists in Naruto: ![Screenshot_2019-09-08-13-55-31-980_org ppsspp ppsspp](https://user-images.githubusercontent.com/16115820/64486303-b81a9300-d240-11e9-843c-09e7cc32a566.png) [recording (2).zip](https://github.com/hrydgard/ppsspp/files/3587469/recording.2.zip)
> 
> If you add Naruto Shippuden to PixelDepthRounding compat.ini does it help?

PixelDepthRounding fixes this but the performance penalty is huge.

**Comment by hrydgard** [comment]
VertexDepthRounding doesn't do the trick I guess?

**Comment by Gamemulatorer** [comment]
Doesn't help

**Comment by Gamemulatorer** [comment]
Maybe create like ***AdrenoDepthStencilBugWorkaround*** just like in Mali GPU?

**Comment by hrydgard** [comment]
None of my Mali phones (S8, S20) reproduce this running the .ppdmp, but there's one more thing I want to try before we force PixelDepthRounding - position invariance, seehttps://www.khronos.org/opengl/wiki/Type_Qualifier_(GLSL)#Invariance_qualifiers . I'll commit a quick attempt soon.

**Comment by hrydgard** [comment]
Don't really have high hopes that it will help, won't be surprised if we end up enabling pixeldepthrounding. We should indeed probably make a Mali-specific version of that in that case.

**Comment by Gamemulatorer** [comment]
https://github.com/hrydgard/ppsspp/commit/e56e5947d5d4cadad7e69f2f3c3dbfea5d95a15b doesn't help.

**Comment by Gamemulatorer** [comment]
https://github.com/hrydgard/ppsspp/pull/16043 doesn't help for vulkan.

**Comment by Gamemulatorer** [comment]
Can no longer reproduce this issue using the recently build.
![Screenshot_20221025_203501_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/197774546-59ea940b-8293-4c4d-a974-1187d0552532.jpg)

Vivo Y11 Snapdragon 439

**Comment by hrydgard** [comment]
That's interesting! Wonder what might have fixed it?

**Comment by Gamemulatorer** [comment]
Or maybe because the driver version of vivo y11 snapdragon 439 adreno 505 is better?
![Screenshot_20221026_004648_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/197834341-ddd7d125-4d2b-4f43-9fac-0af7a53fd12e.jpg)

**Comment by Gamemulatorer** [comment]
This issue is safe to close now.

**Comment by unknownbrackets** [comment]
Maybe also the equal checks using draws instead of clears helped normalize some differences?  Or a benefit of using `invariant` on the position?

I'll close this then as worked around (for drivers we can) and fixed where we can.   Good if it's not happening on Adreno 5xx.  Definitely possible Adreno fixed it.

-[Unknown]
