### ISSUE TITLE
Depal shader compile error on ATI

### ISSUE THREAD

**Issue by unknownbrackets** [hrydgard/ppsspp#11588]
Seeing this error:

```
error(#272) Implicit version number 110 not supported by GL3 forward compatible context
```

https://report.ppsspp.org/logs/kind/970
https://github.com/hrydgard/ppsspp/blob/7f8868868ea87d2177ef9ab17a979b4512b30be9/GPU/Common/DepalettizeShaderCommon.cpp#L255

I think this is a GL3 core context.  We probably need to use this:

https://github.com/hrydgard/ppsspp/blob/f8e946d8e5394396a30a957ddf362de7651fb2c6/ext/native/gfx_es2/gpu_features.cpp#L79

This appears to be new in 1.7.x, though I'm not sure why.  It could just be we weren't reporting it before, but I'm marking as a regression for now.

-[Unknown]

**Comment by hrydgard** [comment]
The strange thing is that this only happens in the GenerateDepalShaderFloat path which I wouldn't expect to be used in a GL3 core context on desktop. But yes, to be safe we should definitely use the right version there anyway..

**Comment by unknownbrackets** [comment]
Ah, the reports all specifically had ATI as the vendor, so I assumed they were older ATI cards.  But looking closer it seems to affect both AMD and ATI:

Devices affected:
 * ATI Radeon HD 3200 Graphics
 * ATI Radeon HD 4200
 * ATI Mobility Radeon HD 4200 Series
 * AMD Radeon HD 5500 Series
 * AMD Radeon HD 6290 Graphics
 * AMD Radeon HD 6370M
 * AMD Radeon HD 6450
 * AMD Radeon 6600M and 6700M Series
 * AMD Radeon HD 7450
 * AMD Radeon HD 7480D
 * AMD Radeon HD 8470D

GL versions range from 3.3 to 4.5.  It's weird that 4.5 is affected, maybe there's a bug causing it to use the float path by mistake?

-[Unknown]

**Comment by unknownbrackets** [comment]
All affected devices are sending back a slightly wrong GL_VERSION:

`4.4.13294 Core Profile Context 14.502.1020.0`

I wonder if we're ever getting misled by the final number there?  I tried one of the version strings and we correctly parse it.  Hm.  Maybe somehow `CheckGLExtensions` being called from the wrong thread?

-[Unknown]

**Comment by hrydgard** [comment]
Hm, this is likely fixed now, right?

**Comment by unknownbrackets** [comment]
It's not happening anymore, I'll close.

That said, I still don't really understand how it was getting into this code path on GL3.  Presumably it means GPU_SUPPORTS_32BIT_INT_FSHADER is not set, but that should definitely be set on 4.x...

-[Unknown]
