### ISSUE TITLE
Digimon Adventure PSP NPJH-50686 Tiny glitch on digivolutions menu on battle mode on Direct3D 11 Backend

### ISSUE THREAD

**Issue by LPatamon** [hrydgard/ppsspp#12188]
### What happens?
The games runs fine and all but I discovered a curious glitch on the digivolutions menu when you use the Direct3D 11 Backend. This glitch is only on Agumon and Gabumon's digivolution menu when you already have Omegamon unlocked.

The text on the Omegamon option appears with a weird background only behind Omegamon's name and the SP number (including the letters SP as well). This only when you still haven't digivolved Agumon and Gabumon to mega level.

The glitch may appear on the other digivolution levels if you don't have enough SP points since it changes the characters and numbers to red color to show you can't use it. On the OpenGL backend it works fine.

Here are a couple of Screenshots. One shows the glitch on Direct3D 11 backend and the other is with the OpenGL backend to show how it should look:

Direct3D 11 Backend with glitch
![glitchdirectx11](https://user-images.githubusercontent.com/6118529/61591621-60d83a80-ab8e-11e9-9976-b0d5a90dd87d.png)

OpenGL showing the menu normally
![normalopenglbackend](https://user-images.githubusercontent.com/6118529/61591622-60d83a80-ab8e-11e9-8f26-96f0226d2eb2.png)

### What *should* happen?
There shouldn't be such peach colored background on the unavailable digivolution, it should appear just in red colored characters.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
I use Windows 7 Ultimate 32 bits, ppsspp-v1.8.0-433-g37a97e741 (x86 version of course) and I have a 2GB Radeon R7 240 Graphic card, 4GB RAM, 1TB Hard disk and a 500GB Hard Disk and a Core i5 3Ghz CPU (4 cores).

As some extra info. That glitch exists on Direct3D 11 backend ever since it got implemented, but I didn't realize it because I used the OpenGL by default before the Direct3D 11 was added. Actually even the Vulkan backend was added first than the Direct3D 11 one.

I think the Direct3D 11 backend was added on the v1.4 builds because I had an old rar file with one of the v1.3 versions and the only backends it had was Direct3D 9, OpenGL and Vulkan, and from those three backends the default one was the OpenGL one.

Is not a serious thing, but I thought in report it because maybe it can appear on some other games. My Graphics Card is fully compatible with DirectX 11 and by default with Direct3D 11.

**Comment by unknownbrackets** [comment]
Smells like a flushing issue.  A GE dump might help, but there's a good chance it won't replicate the issue.  For some reason, I remember seeing this before and seeing a GE dump, but I don't see one in this issue.  Maybe I've mixed it up with another.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by LPatamon** [comment]
Hello. Sorry for not replying before. Got too busy lately x_x

Anyhow here is the dump, hope it helps.

[NPJH50686_0002.zip](https://github.com/hrydgard/ppsspp/files/3487017/NPJH50686_0002.zip)

By the way something really curious happened. I changed the backend back to Direct3D 11 to get the GE Dump and the digivolutions menu appeared normal without the glitch. I even checked the menu to see if the backend got changed correctly and sure it was on Direct3D 11. Then I went to the menu to watch one of he unlocked videos, got the glitch when I selected another video, and then went back into a battle and the glitch on the digivolutions menu was there once again.

I really don't know what is causing. All I know is that it is just on Direct3D 11.

**Comment by unknownbrackets** [comment]
Thanks.

First draw to that area at 1576/1795, but presumably it's caused by 1578/1795 (text.)

Textures from 089e2e80 using alpha-blend.  Not sure if that could be a "ram framebuffer" or overlap with one.  Textured using slope+bias, CLUT4, linear/linear, and importantly a clut base (getClutIndexStartPos) which is fairly uncommon.

I'm not seeing any obvious bug, though.  But perhaps it's using a ram framebuffer and passing through the depal code (not that I see a bug there either.)  Unfortunately, the dumb doesn't reproduce the corruption.

Didn't see any obvious state that would be missing flushing, but still possible...

-[Unknown]

**Comment by LPatamon** [comment]
> 
> 
> Thanks.
> 
> First draw to that area at 1576/1795, but presumably it's caused by 1578/1795 (text.)
> 
> Textures from 089e2e80 using alpha-blend. Not sure if that could be a "ram framebuffer" or overlap with one. Textured using slope+bias, CLUT4, linear/linear, and importantly a clut base (getClutIndexStartPos) which is fairly uncommon.
> 
> I'm not seeing any obvious bug, though. But perhaps it's using a ram framebuffer and passing through the depal code (not that I see a bug there either.) Unfortunately, the dumb doesn't reproduce the corruption.
> 
> Didn't see any obvious state that would be missing flushing, but still possible...
> 
> -[Unknown]

Yeah it sure is an odd thing. And it only happens when you use Direct 3D 11 backend. On the OpenGL one it doesn't causes such issue.

About what you said that presumably it's caused by 1578/1795 (text.), it might be that since the text shold appear in red color (as sin on the OpenGL capture I included on the opening post) to signal that such digivolution is not available (in this case it was the Omegamon one that you can't use it unless Agumon or Gabumon digivolve first to Mega level), but instead on Direct3D 11 a background appears on the text causing it to look as you can see on the included screenshot on the opening post.

**Comment by hrydgard** [comment]
Is this still happening? Similar-looking issues have been fixed, like #9551 .

**Comment by LPatamon** [comment]
> 
> 
> Is this still happening? Similar-looking issues have been fixed, like #9551 .

Yes. it still happens on Direct3D 11 backend:

![image](https://user-images.githubusercontent.com/6118529/99921248-bd9db500-2cee-11eb-9168-bafed8813762.png)

For now I'm using the Vulkan backend (thank goodness my current graphic card is fully compatible) and on that one the glitch doesn't happens.

**Comment by hrydgard** [comment]
Alright, thanks for testing!

**Comment by unknownbrackets** [comment]
If you change the resolution, i.e. from 4x to 2x, while the text is shown and garbled - it corrects it, is that right?

-[Unknown]

**Comment by LPatamon** [comment]
Well it partially corrects it, I mean that orange background on the glitch goes away but the text isn't showing correctly as you can see on the screenshot.

Text should be red colored as shown on a screenshot on my post above yours.


![image](https://user-images.githubusercontent.com/6118529/108481368-bcccde80-725d-11eb-9588-ced39f796407.png)

**Comment by unknownbrackets** [comment]
Is this still an issue in recent git builds (https://buildbot.orphis.net/ppsspp/)?  This functionality may have improved recently.

-[Unknown]

**Comment by LPatamon** [comment]
> 
> 
> Is this still an issue in recent git builds (https://buildbot.orphis.net/ppsspp/)? This functionality may have improved recently.
> 
> -[Unknown]

Yes. Still glitchy.
![image](https://user-images.githubusercontent.com/6118529/128338687-174e37e6-113e-4d8d-b5c0-358b16afb4d3.png)

In the meantime I use Vulkan Backend as a workaround since it works correctly there:

![image](https://user-images.githubusercontent.com/6118529/128338843-61a9d77e-8153-4376-91e4-881573d1c079.png)

**Comment by hrydgard** [comment]
Huh, surprising! Thus, leaving open.

**Comment by Gamemulatorer** [comment]
***Regression!***
Digimon adventure sky graphics glitch.

###Vulkan
![Screenshot_2022-04-19-20-26-05-646_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/164004318-4b953b08-646b-4527-a266-57dfb428d7a8.jpg)

###Opengl
![Screenshot_2022-04-19-20-26-35-366_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/164004383-78959cf7-59d8-48ac-a166-0393bc56cf02.jpg)

###Software
![Screenshot_2022-04-19-20-34-08-350_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/164004718-361de929-35e8-4b5c-89f1-46d7bfd7b547.jpg)

**Comment by Gamemulatorer** [comment]
GE DUMP!
[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/8512977/recording.ppdmp.zip)

**Comment by hrydgard** [comment]
Thanks, great report! Will look into it soon.

**Comment by hrydgard** [comment]
Hm, when I load the GE dump. the sky isn't drawn correctly in any of the backends (just plain blue in software, black in the others).

Can you grab a save state?

**Comment by hrydgard** [comment]
Hm, maybe already have something what seems to be the sky texture is a CLUT16_565  (16-bit sized texels, looking up into a 16-bit CLUT) which is kinda uncommon for non-rendertarget textures, so would be a logical place for a regression.

**Comment by hrydgard** [comment]
OK, issue found and should be fixed now. Thanks again for the report @Gamemulatorer !

**Comment by unknownbrackets** [comment]
Is this working any better now (the original color issue)?  I'm wondering if it was using some framebuffer effect in a tricky way, which might be running better or unified better now between backends.

-[Unknown]

**Comment by LPatamon** [comment]
Nope. The issue is still there on Direct3D 11 Backend

![PPSSPP Digimon evomenu](https://user-images.githubusercontent.com/6118529/191524898-50c3510b-863f-44dc-adb1-026ce52917ab.jpg)

On Vulkan works fine

![PPSSPP Digimon evomenu vulkan](https://user-images.githubusercontent.com/6118529/191525346-044f2f51-fa56-4790-a3ad-6ca4afe83135.jpg)

And the line on the videos is still there as well but that's for the other issue I have for it.

**Comment by unknownbrackets** [comment]
Could you try creating a new frame dump with the latest version?  I just want to see if it reproduces it, as we've made some fixes to frame dump creation.

The texture does use a transparent background color that is a bit orange, although moreso red (note this is with boosted alpha, the background is 100% transparent):
![text with reddish transparent background](https://user-images.githubusercontent.com/191233/197445534-dde5b957-0abf-417c-9b42-ba516f2e4b33.png)

This game uses CLUTs with 16-bit color entries, which is a bit uncommon.  Outside of that, this uses fairly standard alpha blending and not much else.  It pointlessly uses modulate against a fixed 0xFFFFFFFF vertex color.

The orange in the top item comes from a texture at 0x089e22a0 (128x32) in the framedump, which is just already the orange background entirely (not just the text):
![full orange bar](https://user-images.githubusercontent.com/191233/197446171-c20d6b49-8054-467b-9ded-e696b37ed6f5.png)

Text on top of the orange bar is draw with the texture at 0x089e2e80 (512x256), and simple alpha blending using white.  There's no sign of the white color.

Another unusual thing this does is use a CLUT offset for this text, +3 (i.e. +0x30.)  This makes it skip the first 48 entries in the palette, which changes white text to red (the first five sets of 16 colors are simple ramps of white, black, gray, red, and blue respectively.)  It uses the same 0x089e2e80 texture with this offset to colorize the text differently.

When it's drawing the orange BG, the palette includes plenty of orange entries:
![palette with orange ramp and some other oranges](https://user-images.githubusercontent.com/191233/197446878-348412cf-2768-4241-9902-15be38480282.png)

But the text drawing lower down just doesn't have much orange in it:
![text color ramps and extra blue space](https://user-images.githubusercontent.com/191233/197446956-b8cfc50a-51cb-4e26-a1c0-091fbcfa8baf.png)

The only real candidate is entry 81 (aka 0x51), but not sure how it'd get used.  And doesn't seem like it could be a texture cache issue with it reusing the text with a wrong palette.  The background of the text is entry 0 (so should be 0 + 0x30 = the transparent red color.)

-[Unknown]

**Comment by unknownbrackets** [comment]
Finally discovered the cause thanks to @Saramagrean.  This only affected GPUs without full 16-bit texture support (or saving textures for replacement.)  Specifically, this part was not working in that scenario:

> Another unusual thing this does is use a CLUT offset for this text, +3 (i.e. +0x30.)

-[Unknown]

**Comment by LPatamon** [comment]
Yes! It got fixed! One down and one to go.

Now that this one is fixed all is left to fix on this game is issue #13379 

Thanks for all your efforts in making this emulator the best :)
