### ISSUE TITLE
Ipega 9087 analog sticks and d pad not recognized

### ISSUE THREAD

**Issue by JerryTheRaceCarDriver** [hrydgard/ppsspp#12205]
I just bought an Ipega 9087 so I could play games on my LG V40 without my fingers blocking the screen. I tried to run some games with PPSSPP but for some reason the analog sticks and the d pad dont work. I tried to go into settings and map the controls, but that didnt work. I tried to test the analog sticks, that didnt work either. What's happening?

**Comment by hrydgard** [comment]
Sounds like different behavior than the seemingly related issue #12208. Do the rest of the buttons work correctly?

I've got one of these on order from AliExpress, so hopefully I'll be able to try it myself in a while.

**Comment by LunaMoo** [comment]
Doesn't most of those android gamepads require some additional apps to standardize button mappings? IE. https://play.google.com/store/apps/details?id=com.chaozhuo.gameassistant&hl=us

**Comment by marosis** [comment]
I have same gamepad but cannot reproduce this issue. When i mapping buttons, names of buttons are  same as on first launch of the emulator and everything is working fine
![IMG_20190801_170542](https://user-images.githubusercontent.com/33152267/62304836-1b194d00-b47f-11e9-9050-140fe5310117.jpg)

**Comment by JerryTheRaceCarDriver** [comment]
I tried using octopus, doesn't work.

All the other buttons work normal.

**Comment by elric7teen** [comment]
Do you still had this issue?

I have similar issue with Ipega 9077 on v.1.9.4, do you already tried using different version? i tried using v 1.8.0 and it works for me

**Comment by AydanAmorim** [comment]
@JerryTheRaceCarDriver you could solve this problemn?
I'm having the same problemn. All the buttons on my IPEGA 9087 works normally, but, my analogic and d-pad doesn't work as happen to you...

**Comment by elric7teen** [comment]
> @JerryTheRaceCarDriver you could solve this problemn?
> I'm having the same problemn. All the buttons on my IPEGA 9087 works normally, but, my analogic and d-pad doesn't work as happen to you...

try to install v1.8.0 then update it to latest version.
Im using 9077 and after I try that it works just fine for me

**Comment by unknownbrackets** [comment]
Does that mean this is fixed with the latest updates to the device software?

-[Unknown]

**Comment by Gamemulatorer** [comment]
@JerryTheRaceCarDriver can you still reproduce this using v1.14?
