### ISSUE TITLE
Vulkan not working on PowerVR Rogue GE8100 (Android) after fb size rounding workaround

### ISSUE THREAD

**Issue by Saramagrean** [hrydgard/ppsspp#12296]
### What happens?
- UI broken after switch backend OpenGL to Vulkan.

### What *should* happen?
- Vulkan backend should working normally. 

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
- Huawei Y5 Lite (Android 8.1, MediaTek MT9739, PowerVR Rouge GE8100, OpenGL ES 3.2, Vulkan driver v1.0.49)
- PPSSPP v1.8.0 Build 585

**Comment by Saramagrean** [comment]
Tried v1.8.0 Build 592, After switch to Vulkan backend, App freeze and blacksreen. 😱

**Comment by hrydgard** [comment]
Uh, okay, that's surprising. I'm gonna try later on the most modern PowerVR device I have, a wacky Spreadtrum x86-64 phone.

**Comment by hrydgard** [comment]
Hm, can't seem to get Vulkan running on that device... I do recall I had one device that had PowerVR with Vulkan support but I guess it was something else that I can't find right now.

Anyway, made another blind fix attempt. Let me know if it works.

**Comment by hrydgard** [comment]
@Saramagrean Whenever you have a sec, please try the latest build again :)

**Comment by Saramagrean** [comment]
Okay. 👌

**Comment by Saramagrean** [comment]
Not freeze and blackscreen but image is displayed on only half screen.
![69635132_579078159291611_2328836159582502912_n](https://user-images.githubusercontent.com/26355472/64147000-2af2cb00-ce49-11e9-8bf9-86a88b7f6de8.jpg)

**Comment by hrydgard** [comment]
That's quite unexpected... I would have thought both in-game and menu would be broken the same way. Argh...

**Comment by hrydgard** [comment]
Does that persist if you switch away from the app and back, or if you restart it?

**Comment by Saramagrean** [comment]
It cause by "Skip buffer effects". after changing to "Buffered rendering", the image is show fullscreen normal. 😃

**Comment by hrydgard** [comment]
Oh good, that's interesting. Then the PowerVR issue is probably "fixed" and what remains is a more generic issue - haven't tested "Skip buffer effects" much with Vulkan after merging the pre-rotate stuff. Definitely will need to fix this before 1.9.0 so keeping the issue label.

**Comment by hrydgard** [comment]
Just confirming that yes, this repros on non-PowerVR devices. I'm closing this and opening a new one.

**Comment by hrydgard** [comment]
@Saramagrean Pretty sure I fixed it for all GPUs now. But still, would be good if you could try the latest build with https://github.com/hrydgard/ppsspp/pull/12304 when it finishes compiling. Thanks!

**Comment by Saramagrean** [comment]
Sorry for late reply. tried with v1.8.0-609, the image is now full screen. Great work!

...but still encountering a graphics glitch in some game.
- God Eater 2 : Black screen after start game.
- Kamen Rider : White screen after start game.
- Gundam Vs. Next : Crash in main menu.

**Comment by hrydgard** [comment]
Thanks, yeah, those are likely further driver bugs, PowerVR really has awful drivers. For 1.9.0 I'm only focusing on making basic rendering work so that users can switch to OpenGL if needed... Thanks for the testing you've done so far. I really need to find my PowerVR device with Vulkan, probably stuck in some drawer :)

**Comment by manish221b** [comment]
> Hm, can't seem to get Vulkan running on that device... I do recall I had one device that had PowerVR with Vulkan support but I guess it was something else that I can't find right now.
> 
> Anyway, made another blind fix attempt. Let me know if it works.

hrydgard, can you tell me, how to get vulkan driver for PowerVR GE8320. It supports vulkan 1.1, but driver is not provided by SoC. Is there a solution? My device is Infinix hot 8.

**Comment by hrydgard** [comment]
Sorry, I don't have any solution to that.
