### ISSUE TITLE
Outrun 2006 crashes in cloudy highland level (OpenGL, RPI4)

### ISSUE THREAD

**Issue by akamming** [hrydgard/ppsspp#13015]
### What happens?
Outrun 2006 coast 2 coast crashes at cloudy highlands on the RPI4  (to reproducre: choose single player, outrun mode, outrun2 (not outrun2SP!!) start the game and always go left when you can choose the next course. Then it will crash in the 4th course (the cloudy highland).

This is the output of the emulator
```
I: VulkanLoader.cpp:272: VulkanMayBeAvailable: Device allowed ('SDL:Linux')
I: VulkanLoader.cpp:279: VulkanMayBeAvailable: Library loaded ('libvulkan.so')
I: VulkanLoader.cpp:332: VulkanMayBeAvailable: Enumerating instance extensions
I: VulkanLoader.cpp:343: VulkanMayBeAvailable: Instance extension count: 2
I: VulkanLoader.cpp:351: VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_report (00000009)
I: VulkanLoader.cpp:351: VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_utils (00000001)
E: VulkanLoader.cpp:369: Surface extension not found
DEBUG: Vulkan is not available, not using Vulkan.
I: Config.cpp:520: Longest display side: -1 pixels. Choosing scale 1
I: NativeApp.cpp:603: Boot filename found in args: '/home/pi/RetroPie/roms/psp/OutRun 2006 - Coast 2 Coast.cso'
Pixels: 1920 x 1080
Virtual pixels: 1920 x 1080
I: gpu_features.cpp:175: GPU Vendor : Broadcom ; renderer: V3D 4.2 version str: OpenGL ES 3.1 Mesa 19.3.2 ; GLSL version str: OpenGL ES GLSL ES 3.10
I: gpu_features.cpp:292: OpenGL ES 3.1 support detected!

loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
Control pad device 0 not supported by SDL game controller database, attempting to create default mapping...
Added default mapping ok
found control pad: USB gamepad           , loading mapping: SUCCESS, mapping is:
030000001f08000001e4000010010000,USB gamepad           ,x:b3,a:b0,b:b1,y:b2,back:b8,guide:b10,start:b9,dpleft:b15,dpdown:b14,dpright:b16,dpup:b13,leftshoulder:b4,lefttrigger:a2,rightshoulder:b6,rightshoulder:b5,righttrigger:a5,leftstick:b7,leftstick:b11,rightstick:b12,leftx:a0,lefty:a1,rightx:a3,righty:a4
pad 1 has been assigned to control pad: USB gamepad           
52:40:809 root         N[G3D]: GLES/ShaderManagerGLES.cpp:899 Precompiling the shader cache from '/home/pi/.config/ppsspp/PSP/SYSTEM/CACHE//ULUS10064.glshadercache'
52:40:810 root         N[G3D]: GLES/ShaderManagerGLES.cpp:980 Precompile: Compiled and linked 59 programs (23 vertex, 34 fragment) in 1.6 milliseconds
52:40:810 root         N[BOOT]: UI/EmuScreen.cpp:299 Loading /home/pi/RetroPie/roms/psp/OutRun 2006 - Coast 2 Coast.cso...
52:42:107 sceUSB_PSPCo E[HLE]: HLE/HLE.cpp:665 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
52:42:107 sceUSB_PSPCo E[HLE]: HLE/HLE.cpp:665 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
52:42:107 sceUSB_PSPCo E[HLE]: HLE/HLE.cpp:727 Unimplemented HLE function Kprintf
52:42:108 user_main    E[SCEIO]: HLE/sceIo.cpp:1951 UNIMPL sceIoDevctl("usbpspcm:", 03415001, 09fff610, 4, 00000000, 0)
52:42:109 sceUSB_PSPCo E[HLE]: HLE/HLE.cpp:665 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
52:42:110 sceUSB_PSPCo E[HLE]: HLE/HLE.cpp:665 Unknown syscall: Module: (unknown) (module: 255 func: 4095)
52:42:110 sceUSB_PSPCo E[HLE]: HLE/HLE.cpp:727 Unimplemented HLE function Kprintf
53:14:335 user_main    E[SCEIO]: HLE/sceIo.cpp:1951 UNIMPL sceIoDevctl("usbpspcm:", 03415002, 08bf5b08, 4, 00000000, 0)
53:14:335 user_main    E[SCEMODULE]: HLE/sceKernelModule.cpp:2061 sceKernelStopModule(0000014b, 00000000, 00000000, 00000000, 00000000): invalid module id
53:14:335 user_main    E[SCEKERNEL]: HLE/sceKernelThread.cpp:2293 sceKernelTerminateDeleteThread(330): thread doesn't exist
/opt/retropie/supplementary/runcommand/runcommand.sh: regel 1255: 12151 Busfout                 /opt/retropie/emulators/ppsspp/PPSSPPSDL --fullscreen "/home/pi/RetroPie/roms/psp/OutRun 2006 - Coast 2 Coast.cso"

```
 

### What *should* happen?
no crash ;-)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
- RPI4 (RetroPie), buster image, all updated to latest versions (including PPSSPP).  
- output of PPSSPPSDL --version:  134c9cf

What i already tried
- everything at https://github.com/hrydgard/ppsspp/wiki/Help:-PPSSPP-is-crashing (still crashing)
- resetting the emulator defaults (still crashing)
- trying both the EU and US versions of the rom (both crash)
- loading the games as an iso or a cso file (both crash)
- switch off overclocking (still crash)
- running the same rom  with the same settings, same latest  PPSSPP version in retropie on a debian laptop  (buster, also everyting up-2-date): game does not crash. So i ithink it is isolated to RPI4.
- check the forum for this issue (not found)
- reporting the issue on the forum (no response)

would be really nice if someone can fix this, or give me a hint on how i can prevent this crash myself. (apart from avoiding this course ;-)).

**Comment by HiImBrala** [comment]
I can confirm this issue happens at my Redmi 6

**Comment by akamming** [comment]
2 updates
1. just found out it is much easier to reproduce: Just go to single player / time attack mode and select the cloudy highland level.   The same crash will appear
2. because i like really like the game i also installed PPSSPP/Outrun 2006 on my Samsung S9+. i use the same rom but no crash.  (PPSSPP version 1.9.4 according to the play srtore app)

**Comment by HiImBrala** [comment]
That is weird,besides game having like tons of bugs to start with,this makes it even weirder

**Comment by Turnbl** [comment]
Yes I can confirm this also happens on the Shield TV version.

Just before the crash, the lake way down to the left doesn't look correct - it fills in a lighter colour over black towards the player as you approach it.

Then after a quick left/right after the lake, it crashes always in the same place on a straight with fences at both sides.

Just after where it crashes, on a PSP, there would be a right hand bend with 3 blue Olympus advertising boards on the left just before the first end level green signs that the car goes under.

Hope this helps in any small way!

**Comment by Panderner** [comment]
I can't produce this issue in cloudy highland when I'm using Realme C2.

**Comment by Gamemulatorer** [comment]
@akamming still crashing in the lastest build?

**Comment by akamming** [comment]
Hi,

Tx. I will check.

In am using ppsspp as part of retropie so i don't know if it has the latest build. What should be minimum build level?

Kind regards

Arnold

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by Turnbl** [comment]
I can confirm this is still happening on Shield TV (2019) using PPSSPP 1.12.3 standalone build.

The game freezes after the 2 bends after the lake, and crashes out back to the Android home menu.

**Comment by Gamemulatorer** [comment]
> I can confirm this is still happening on Shield TV (2019 - latest 9.0.2 firmware) using PPSSPP 1.12.3 standalone build.
> 
> The game freezes after the 2 bends after the lake, and crashes out back to the Android home menu.

Can you share save state where it crash?

**Comment by Turnbl** [comment]
@Gamemulatorer here you go - it literally crashes about 2 seconds after this save state:

[https://1drv.ms/u/s!AvCG49HShxvfy3FbsepCjztLr0Y8?e=zddvEh](url)

**Comment by Gamemulatorer** [comment]
> @Gamemulatorer here you go - it literally crashes about 2 seconds after this save state:
> 
> [https://1drv.ms/u/s!AvCG49HShxvfy3FbsepCjztLr0Y8?e=zddvEh](url)

Your link not working unfortunately maybe shars via MediaFire or GDrive

**Comment by Turnbl** [comment]
> > @Gamemulatorer here you go - it literally crashes about 2 seconds after this save state:
> > [https://1drv.ms/u/s!AvCG49HShxvfy3FbsepCjztLr0Y8?e=zddvEh](url)
> 
> Your link not working unfortunately maybe shars via MediaFire or GDrive

Try copying the link directly into a new Chrome window (it works for me in incognito not logged in). Looks like Github is doing something funny when it's clicked on.

**Comment by Gamemulatorer** [comment]
@Turnbl thanks for the link of your save state but still I cannot reproduce crashing on my phone tried both with opengl and vulkan.

https://user-images.githubusercontent.com/37603562/163710288-c3f05ea9-ba2b-48de-9b21-f6f62c4b4dfc.mp4

**Comment by Turnbl** [comment]
@Gamemulatorer Thanks for checking. This must be a device specific issue. Interestingly both Ghost's Redmi 6 and my Shield TV 2019 both have 3GB ram. Akamming's issue is on a RPI4, but works for them on an S9.

**Comment by Gamemulatorer** [comment]
Yeah maybe this is a platform specific issue or device dependent?
Did Spiderman 3 also crashes on your device? See https://github.com/hrydgard/ppsspp/issues/10196

**Comment by Turnbl** [comment]
> 

Just tried it and Spiderman 3 seems to work (or certainly no crashes in 10 minutes of play).

Double checking my Shield TV 2019 specs and it's actually 2GB ram:

Nvidia Tegra X1+
2GB ram
Only runs 32-bit apps

**Comment by hrydgard** [comment]
Oh I didn't notice on Shield TV? I can try to repro that later then and see if I can find something. Also on the latest firmware with Android 11?

**Comment by Turnbl** [comment]
Hi @hrydgard - no this is the non-pro 'tube/cylinder' version they brought out in 2019. This version definitely can't run Dolphin:

https://piunikaweb.com/2019/10/31/nvidia-shield-tv-2019-reportedly-supports-only-32-bit-apps/

I am on latest firmware Android 11 / v9.0.2

**Comment by hrydgard** [comment]
Ah, didn't know about that one! Quite surprising that they'd release a 32-bit-only machine as late as 2019...

**Comment by akamming** [comment]
@Gamemulatorer  it's still crashing a 1.12.3..

**Comment by Panderner** [comment]
@akamming still happen in latest builds?

**Comment by akamming** [comment]
ah there are later builds... then i have to find out how to install the latest one on pi 4  ;-)

**Comment by akamming** [comment]
hi, built from latest source on my pi4 (pfff. takes a long time...) and still crashes..

**Comment by hrydgard** [comment]
Thanks for the save state, I got repro on a debug build on Windows, some heap corruption, potentially texture decoding related (since it's in that code when it happens). Will investigate.

**Comment by hrydgard** [comment]
Fixed a bug but a different one than the one reported here, since in the original report, OpenGL is being used, not Vulkan. So this is still open...

**Comment by akamming** [comment]
I am indeed using opengl.

**Comment by Duglor** [comment]
Anything new on this horizon? I too have the same bug on my Retropie 4.8. Same Emulator.

**Comment by Duglor** [comment]
good luck

**Comment by Duglor** [comment]
is this fixed as of the new 1.16 release?

**Comment by hrydgard** [comment]
Haven't fixed anything specific related to this. That said, it's possible that something fixed it, only way to know for sure is to test it. Which goes for the other issues too - please don't ask whether every single one has been fixed.

**Comment by akamming** [comment]
Just tested: not fixed in 1.16

**Comment by Duglor** [comment]
> Just tested: not fixed in 1.16

Well, that's a shame :(.

**Comment by Duglor** [comment]
> Just tested: not fixed in 1.16

How do you manage to get by this level in the game? Is there a cheat?

**Comment by Duglor** [comment]
Thanks for adding this to Future Priority for 1.17!  and thanks for fixing the Sonic Games brightness bug and the car racing game (forget the name)'s bug with the smudgy rain windshield screens. Appreciate it!

**Comment by hrydgard** [comment]
Adding to future-prio means I'm post-poning it beyond 1.17. I'll look at this the next time I set up my raspberry pi.

This one is especially weird because it seems fine on all other platforms..

**Comment by hrydgard** [comment]
Curiously, this is the same place where it's slow on some devices (#20171).

It's possible that #20398 might have improved this.

**Comment by hrydgard** [comment]
No news or reports on this for quite some time. It might have been fixed, closing.

**Comment by akamming** [comment]
hi, it's not solved. It still crashes at the exact same spot in the exact same level...

**Comment by hrydgard** [comment]
OK, reopening. Still have no explanation. Nothing seems to go wrong on other platforms..

**Comment by akamming** [comment]
> OK, reopening. Still have no explanation. Nothing seems to go wrong on other platforms..

Me neither. With vulkaan driver it works fine. With opengl it fails (only in that level,
Always on that exact same spot)

So for me nog big problem. I can use vulkan. Just to let you knie it's not Fixed
