### ISSUE TITLE
Open Season Title Screen does not display

### ISSUE THREAD

**Issue by Panderner** [hrydgard/ppsspp#13252]
The crashing issue of this game i've mentioned in #10972 is now fixed in latest build leading this game is now playable on PPSSPP.

But i have a problem the title screen does not display.

PPSSPP:
![Screenshot_2020-08-06-02-34-50-61_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/89451071-369fed80-d78e-11ea-89b5-ebd8ead1869a.png)
PSP:
![IMG_20200806_024113](https://user-images.githubusercontent.com/37503397/89451157-5505e900-d78e-11ea-8525-715374153857.jpg)

**Comment by sum2012** [comment]
1:Softgpu work,
2: frame dump only work in Softgpu 
https://drive.google.com/file/d/1gCaqO3yb0eikJMocJ5De858ifxt0reKp/view?usp=sharing

**Comment by sum2012** [comment]
ppsspp-v1.10.3-332-gf23a367c2-windows-amd64 full debug log
https://drive.google.com/file/d/1P-IC8PystnUIEEIp47YEtHK0FckDvB7f/view?usp=sharing

**Comment by sum2012** [comment]
v1.10.3-1207-ge01d53870 
keep idle0        I[FILESYS]: filesystems\isofilesystem.cpp:530 Attempted read at end of file, 0-size read simulated
The situation of this game is worse.

**Comment by hrydgard** [comment]
Hm, when did that start?

I have a plan for the framebuffer memory thing, but that sounds bad.

**Comment by sum2012** [comment]
v1.10.3-1204-g486a82331 work
v1.10.3-1207-ge01d53870 don't work
That is #13659 @shenweip 
v1.10.3-1204-g486a82331 log: https://gist.github.com/sum2012/197f099d247f8c7de70c71da99c4b927
v1.10.3-1207-ge01d53870 log: https://gist.github.com/sum2012/b3d8f603766e95dbf4cbe43391f2e391

**Comment by shenweip** [comment]
Okay, I'll investigate this soon.

**Comment by sum2012** [comment]
@shenweip  I just think that sceMpeg_library with version 0105 will do #13659 action

**Comment by sum2012** [comment]
I have real psp but I don't know how to do pspautotest

**Comment by shenweip** [comment]
> v1.10.3-1207-ge01d53870
> keep idle0 I[FILESYS]: filesystems\isofilesystem.cpp:530 Attempted read at end of file, 0-size read simulated
> The situation of this game is worse.

This should get fixed by #13663 .

**Comment by unknownbrackets** [comment]
Is this working now, given the above?

-[Unknown]

**Comment by Panderner** [comment]
#13663 fixed the video regression but the title screen still not display.

**Comment by sum2012** [comment]
@unknownbrackets The game need #13326
