### ISSUE TITLE
The 3rd Birthday graphic problems (RetroArch Windows)

### ISSUE THREAD

**Issue by ToniBC** [hrydgard/ppsspp#13250]
With the Libretro version in Retroarch, everything updated to nightly, in Windows 10 x64 under Vulkan or GL.

(Fixed) The letters or menus of the game have a slight tremor. 
![3rd Birthday, The (Europe)  T+Esp 1 0 IlDucci -200805-185450](https://user-images.githubusercontent.com/45365478/89441911-308a1c80-d74e-11ea-8037-8b09600b6de5.png)

During the game it appears as an overlay image, as if it were dirt on the screen, it is like a still image.
![3rd Birthday, The (Europe)  T+Esp 1 0 IlDucci -200805-185511](https://user-images.githubusercontent.com/45365478/89441922-34b63a00-d74e-11ea-8b05-9541249799d3.png)

I have tried the options, both by default and alternating between them, but found no solution.

In the nightly version of PPSSPP Standalone that does not happen, it looks good without those errors in the letters or menus and without the superimposed image.

Does anyone have a solution?

**Comment by i30817** [comment]
Turn on frameskip 1 and try again.This looks like a duplicate of https://github.com/hrydgard/ppsspp/issues/13201

At least the tremor in the menus.

Anyway that's just a workaround.

**Comment by ToniBC** [comment]
No, that doesn't work. The first and most important thing is that if we put 1 in frameskip we reduce the speed of the game to 50%, so that would not even have to exist as an option. xD

And yes, it reduces the shake, because instead of 30 fps it goes to 15 fps and it is less noticeable, but it never solves it in any case.

**Comment by kage2051** [comment]
Cannot reproduce the 'superimposed image' issue in Android version of RA (both 64-bit and 32-bit). Proof of that are in the screenshot below.

![Screenshot_2020-08-09-17-35-29-731_com retroarch ra32](https://user-images.githubusercontent.com/25725203/89744388-92f25e00-da69-11ea-9545-2b8c3cf6b4b0.jpg)

It seems it's affecting only Windows builds for some reason.

**Comment by unknownbrackets** [comment]
The game transfers a video to VRAM, and then later draws 0s over it iirc.  If this isn't downloaded to VRAM, then you can get weird artifacts (which change if you skip the video at different points.)

If so, it would imply that block transfer or func replacments are not enabled.

-[Unknown]

**Comment by i30817** [comment]
You're not forgetting to add the ppsspp files the core needs to the right retroarch dir?

**Comment by ToniBC** [comment]
Add all assets from the last build to the ppsspp directory, otherwise it won't work.

And I tried changing options, but did not find any that would solve this. That is why it surprises me that when the core is updated, it fails only in retroarch and it seems that in Windows.

Then I try again, but it would be good for someone to also test it on Windows under Vulkan to see if it happens or not.

**Comment by ToniBC** [comment]
Tried the same game on Android, under Vulkan and without problems. Apparently the Windows version does not work well.

I have tried other games, and for example the 50 Cent: Bulletproof G Unit Edition also has shaking on the screen.

Others like Ace Combat X: Skies of Deception, Ace Combat: Joint Assault also do the same.

Curious.

**Comment by i30817** [comment]
This was fixed by

5313fc5b368b8d7c92d47b0560563ae613461188 is the first fixed commit
commit 5313fc5b368b8d7c92d47b0560563ae613461188
Author: Henrik Rydgård <hrydgard@gmail.com>
Date:   Tue Aug 18 09:18:24 2020 +0200

    More work on GL state leaks. Some things really need a redesign.

**Comment by ToniBC** [comment]
The shaking seems to be fixed, but the "dirt" on the screen is still present.

Tested on both GL and Vulkan on Windows.

The current version of libretro is d465ce5.

**Comment by i30817** [comment]
You're talking about the second screenshot right hand side in the original post you made? Because that doesn't happen here to me (possibly because of different graphics driver, or from using a retroarch with gles context instead of opengl however).

**Comment by ToniBC** [comment]
![Bug Screen](https://user-images.githubusercontent.com/45365478/91012283-238e7980-e5e6-11ea-9570-b504051352ec.png)

I mean marked, I tested it under Vulkan and GL in Windows 10 with the same result, Standalone version works fine.

It's like an image superimposed on that pattern, it's not that they move or anything, they're stuck there at all times.

Something is being misinterpreted in the Libretro version compared to the Standalone version.

**Comment by i30817** [comment]
This is it now running on a almost master retroarch built with gles and wayland only:
![3rd Birthday, The (USA)-200824-084032](https://user-images.githubusercontent.com/757900/91017115-b24ec680-e5e5-11ea-8992-3c6d10049826.png)

**Comment by ToniBC** [comment]
This is with all the default settings. With native resolution, errors are less noticeable, but still present.

![3rd Birthday, The (Europe)  T+Esp 1 0 IlDucci -200824-101813](https://user-images.githubusercontent.com/45365478/91020955-6acf3700-e5f3-11ea-9b44-161e842ae867.png)

In this other, same team, with Vulkan driver and everything correct. PPSSPP v1.10.3-470.
On Android under Retroarch it works fine too, it's only with Libretro and Windows from the looks of it.
It would be nice if you verified the error other people, but in Windows, not in other systems, which is where the error is.

![ULES01513_00000](https://user-images.githubusercontent.com/45365478/91021747-7ec76880-e5f4-11ea-91a3-a577b80b4b46.jpg)

**Comment by i30817** [comment]
I don't have or use windows. No confirmation from me, someone else will have to do it.

**Comment by kage2051** [comment]
I'm going to attach both results, top is from standalone app and bottom from RA core. Settings are: 1440x816, 2x xBRZ filtering, deposterize on, standalone running on Vulkan and RA core (64-bit) on GLES.

Standalone:

![Screenshot_2020-08-27-01-20-22-188_org ppsspp ppsspp](https://user-images.githubusercontent.com/25725203/91411399-8316a000-e805-11ea-8b0e-dcd28e9c5680.jpg)

RA core:

![Screenshot_2020-08-27-01-27-30-945_com retroarch aarch64](https://user-images.githubusercontent.com/25725203/91411435-8dd13500-e805-11ea-86db-fe367c2786e9.jpg)

As you can see, I cannot reproduce the issue on neither platform.

**Comment by ToniBC** [comment]
You are indicating that you tried it in the GLES version, but what I put is in the desktop version, with GPU Nvidia GTX 970 or higher, under Retroarch Windows x64 @kage2051

I'm not referring to the Android version, or Xbox, or that, the Windows version.

You say you can't reproduce the bug, but you're not testing the major version of Retroarch.

How difficult is it to test the version that most of us use?

Or is it that I do not understand which versions you are tested, because it is okay to test on other platforms, but do not skip the platform that fails.

**Comment by kage2051** [comment]
GL/Vulkan drivers on Windows tend to fail, especially on libretro cores. Have you tried using the Direct3D9/3D11 backend?

**Comment by hrydgard** [comment]
> GL/Vulkan drivers on Windows tend to fail

Not really, they should work just as well as on any other platform.

**Comment by ToniBC** [comment]
It is as @hrydgard says, the problem is that something is wrong in Libretro, surely they will use a more updated version of the drivers on PC and it will fail because of that or because of some adaptation of them.

The other platforms, Android or GLES, have limited GL and Vulkan support for what they said and as PPSSPP is more adapted to that.

The problem is not the drivers as such, because the Standalone version on PC works without problems, it is the Libretro port that something did not adapt well in Windows and you will have to see what it is.

It would be nice if they fixed it because in Retroarch we can use shaders and bezels that will surely work better than in the Standalone version.

**Comment by kage2051** [comment]
> > GL/Vulkan drivers on Windows tend to fail
> 
> Not really, they should work just as well as on any other platform.

Well, I said that because it happens a lot on PCs with Intel integrated GPUs (especially if it's Sandy/Ivy Bridge/Haswell based). Since the OP uses an Nvidia GPU card, it might not be the case.

**Comment by hrydgard** [comment]
That could be happening (detecting the wrong GPU) but it shouldn't cause these artifacts.

It might just be some weird issue in the libretro integration code in PPSSPP, or it can't access the asset files for some reason, or anything else. needs investigation, unfortunately higher priority would be actually getting Vulkan to work correctly with libretro again (it doesn't currently work, it looks like it does but it's because it switches to OpenGL). #13328 is the beginning of that work.

**Comment by i30817** [comment]
Well not even vulkan works without x11. I'm using gles for a reason, and it's because wayland doesn't load the X11 libraries if i disable xwayland support in the retroarch compilation. And then i have to have a special build of retroarch just for ppsspp because the context for opengl but without x11 returns null on retroarch built with wayland and opengl support.

**Comment by NRosenbergLoyaltyOne** [comment]
I believe I am having the exact same problems with weird artifacts on screen just like  @ToniBC. Using Retroarch win10 x64, with GL driver. On standlone PPSSPP, everything works and no artifacts are present. Tried multiple configs with same driver but nothing worked. Switching drivers to Vulkan or Dx9 just crashed PPSSPP.

**Comment by Ryunam** [comment]
Just chiming in to say that I am experiencing the same exact problem. The PPSSPP core with both gl and glcore video drivers will exhibit weird dots and visual artifacts on-screen with this game, which do not appear at all when using d3d9. 

I am using an Nvidia GPU on a desktop PC (2700 Super) and I have disabled the integrated Intel GPU entirely from the BIOS/UEFI, so I don't think it's a GPU detection problem.

**Comment by ToniBC** [comment]
The problem has been fixed, now it looks the same as the Standalone version, so I close the issue.

Thank you very much.

**Comment by i30817** [comment]
Curious why, is it because of this https://github.com/libretro/RetroArch/pull/11490 RA commit? (which is only 6 hours old merged!)

**Comment by ToniBC** [comment]
I can't tell you exactly, I use Vulkan as a driver, so I should use that when running PPSSPP, but of course, I may be using GLCore for some reason. But before it failed with all, the dirt on the screen was observed with all drivers.

I don't know when it was fixed, maybe it was something unrelated to PPSSPP or it was related to other things, like the screen shaking that was fixed before.
