### ISSUE TITLE
ATV Offroad Fury Blazin Trails Graphical Problems

### ISSUE THREAD

**Issue by fahadrashid7705** [hrydgard/ppsspp#13444]
### What happens?
in latest build some graphical problem this game in my pc and mobile. caracter dissapeared only atv bike visible . 
and road texture glitches if i go back very old build of ppsspp like ppsspp-v1.6.3-352-gec5b0c21a-windows-amd64 the problem totally solved hope you undestand plz fix this issue .

**Comment by Panderner** [comment]
tell me @fahadrashid7705 what the last build worked?

**Comment by hrydgard** [comment]
Please post some screenshots of the problem, preferably before and after. But it's most likely related to my recent partial rewrite of the framebuffer management, which still has a few issues.

**Comment by fahadrashid7705** [comment]
> Please post some screenshots of the problem, preferably before and after. But it's most likely related to my recent partial rewrite of the framebuffer management, which still has a few issues.

ok my brother

**Comment by Gamemulatorer** [comment]
The white lane is shaking during gameplay

**Comment by fahadfoyjur** [comment]
Yes this one of the issue

**Comment by fahadfoyjur** [comment]
![Screenshot_20200917-200838](https://user-images.githubusercontent.com/30353841/93483134-4fb9c380-f922-11ea-8bdf-23cc0bd4c620.png)

**Comment by fahadfoyjur** [comment]
![Screenshot_20200917-200359](https://user-images.githubusercontent.com/30353841/93483278-7b3cae00-f922-11ea-8d2b-27f21c608ac0.png)

**Comment by fahadrashid7705** [comment]
any way to fix it ?

**Comment by Gamemulatorer** [comment]
> any way to fix it ?

Just sit back and relax developer will find way to fix this issue sooner or later no need to rush ✈

**Comment by Panderner** [comment]
@fahadrashid7705 try stable version of PPSSPP and investigate when the last build worked.

**Comment by fahadfoyjur** [comment]
তাহ‌লে ‌অপেক্ষা ক‌রি । ডেভলাপার দের বিরক্ত করা ঠিক হ‌বে না । sorry 

> > any way to fix it ?
> 
> Just sit back and relax developer will find way to fix this issue sooner or later no need to rush ✈

Then wait. It would not be right to bother the developers. sorry

**Comment by Panderner** [comment]
Note: Graphical glitches in ATV Offroad Fury: Blazin' Trails are appeared if you holding the unthrottle button during loading screens or pressing the X button next to ATV/Rider section

DO NOT USE UNTHROTTLE BUTTON DURING THE LOADING SCREEN OR X BUTTON NEXT TO ATV/RIDER SECTION

**Comment by Panderner** [comment]
Here's a Comparison:

Without using unthrottle button:
![Screenshot_2020-09-21-20-15-42-00_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93765429-755b0b80-fc47-11ea-8166-b468ba65fd8a.png)
![Screenshot_2020-09-21-20-15-08-97_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93765434-7724cf00-fc47-11ea-9bb0-5e67e8ebd324.png)
![Screenshot_2020-09-21-20-14-29-51_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93765436-77bd6580-fc47-11ea-8ca9-d6e4ad46d15b.png)

With using unthrottle button:
![Screenshot_2020-09-21-20-15-58-53_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93765533-a1768c80-fc47-11ea-99f3-e306c353d0d4.png)
![Screenshot_2020-09-21-20-15-16-71_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93765535-a3405000-fc47-11ea-9322-6817390b0c5e.png)
![Screenshot_2020-09-21-20-14-47-19_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/93765536-a3d8e680-fc47-11ea-99cb-62929b3200fd.png)

**Comment by fahadfoyjur** [comment]
Ok let me check

**Comment by fahadfoyjur** [comment]
No not working

**Comment by hrydgard** [comment]
Do you have frameskipping enabled?

**Comment by Panderner** [comment]
> Do you have frameskipping enabled?

@hrydgard yes it's same happens for frame skipping. Fast Forwarding and Frame Skipping can cause graphical glitches for this game

**Comment by hrydgard** [comment]
Yeah well I was asking @fahadfoyjur - because I think that's likely to be it, and there's not really a bug here, but annoying that it doesn't work when skipping frames. We might need a compat flag that turns frameskips and frameskip-unthrottle off for games like this.

**Comment by Panderner** [comment]
> We might need a compat flag that turns frameskips and frameskip-unthrottle off for games like this.

This will affect lower-end devices that can't run this game at full speed in 1x resolution.

**Comment by fahadrashid7705** [comment]
> Do you have frameskipping enabled?

no brother i am not enable the frameskip

**Comment by fahadrashid7705** [comment]
and not hold the unthrottle button

**Comment by Panderner** [comment]
@fahadrashid7705 have you updated to latest build?

**Comment by fahadfoyjur** [comment]
Yes ofcourse

**Comment by Panderner** [comment]
@fahadfoyjur are you lying? check if the frame skipping turned off and not to press the fast foward button.

**Comment by fahadrashid7705** [comment]
cool man , why i am lying ? every games on your phone runs good and myself issues maybe you lying

**Comment by fahadrashid7705** [comment]
this is an issue it need to be solved

**Comment by Panderner** [comment]
@fahadrashid7705 send me the screenshot if the frame skipping is turned off.

**Comment by fahadrashid7705** [comment]
ok i directly send a my gameplay video

**Comment by fahadfoyjur** [comment]
https://youtu.be/kBccD1TCJ9Q

**Comment by fahadfoyjur** [comment]
Here is my gameplay video plz watch

**Comment by Panderner** [comment]
ok @fahadfoyjur what region of this game?

**Comment by fahadrashid7705** [comment]
i tryed usa and europe both

**Comment by Panderner** [comment]
@fahadrashid7705 what device are you using?

**Comment by Panderner** [comment]
@fahadrashid7705 @fahadfoyjur Confirmed if you disable slower effects it cause graphical glitches on characters models but not in ATV/Rider section.

Disable slower effects on:
![Screenshot_2020-09-26-13-22-39-34_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/94330976-b6fb0600-fffb-11ea-9839-601eede2becb.png)

Disable slower effects off:
![Screenshot_2020-09-26-13-23-23-77_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37503397/94330983-c24e3180-fffb-11ea-8d77-5c6027653a61.png)

**Comment by fahadfoyjur** [comment]
I allready told you my device is sd430 and gpu adreno 505 , ok let me try once again and inform you there

**Comment by fahadrashid7705** [comment]
yes atv quard bike and carecter texture worked if i disable 2 options hardware tessellation and disable slow effects . but terrain texture fleaker still issue

**Comment by unknownbrackets** [comment]
The unthrottle part of this issue should be fixed in the latest git builds.

Are there still graphical glitches?

-[Unknown]

**Comment by Gamemulatorer** [comment]
Redmi Note 9 Helio G85 PPSSPP github apk
OpenGL
![Screenshot_2021-05-18-22-31-09-966_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/118670089-e4b1eb00-b828-11eb-9892-089638b2008a.jpg)
Vulkan
![Screenshot_2021-05-18-22-30-48-515_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/118670114-e8457200-b828-11eb-9853-e50c4aef0904.jpg)

**Comment by unknownbrackets** [comment]
Great, I'm going to close this then assuming it's been fixed with that change.

If you're seeing this and have exactly the same graphical issues, please comment and we'll reopen.  If they are different issues even if the same game, please create a new issue.

-[Unknown]

**Comment by German-Herrador** [comment]
Still happens in 1.14.4
Mali-G51
Vulkan and OpenGL (gameplay is using Vulkan)

There's flickering/missing textures in the floor and the character is missing: 
https://youtu.be/TrmUC6YquJk

**Comment by hrydgard** [comment]
Does it still happen in the latest builds @German-Herrador ? https://buildbot.orphis.net/ppsspp/

**Comment by German-Herrador** [comment]
Yes, tested in v1.14.4-825-gf32d0c2d6 (latest atm) and both Vulkan and OpenGL still have this problem. However using software renderer makes the character appear again and the flickering missing textures in the floor are less and no longer flicker they are just missing. Very strange behavior.

Vulkan:
![Screenshot_20230311_155451_org ppsspp ppsspp](https://user-images.githubusercontent.com/109971356/224513295-e6de9698-d86f-4ee6-b19c-0f735572069a.jpg)

Software Renderer: 
![Screenshot_20230311_155841_org ppsspp ppsspp](https://user-images.githubusercontent.com/109971356/224513302-976f0148-8f29-419e-aca2-4b64c8c04e23.jpg)

**Comment by German-Herrador** [comment]
Yes, tested in v1.14.4-825-gf32d0c2d6 (latest atm) and both Vulkan and OpenGL still have this problem. However using software renderer makes the character appear again and the flickering missing textures in the floor are less and no longer flicker they are just missing. Very strange behavior.

Vulkan:
![Screenshot_20230311_155451_org ppsspp ppsspp](https://user-images.githubusercontent.com/109971356/224513295-e6de9698-d86f-4ee6-b19c-0f735572069a.jpg)

Software Renderer: 
![Screenshot_20230311_155841_org ppsspp ppsspp](https://user-images.githubusercontent.com/109971356/224514174-0d91923c-589a-4f40-bbd8-0838771dea8c.jpg)

**Comment by German-Herrador** [comment]
Since i have a low-end GPU maybe we need other people to test it to be sure.

**Comment by Gamemulatorer** [comment]
Geometry shader culling doesn't help?

**Comment by German-Herrador** [comment]
What's that?

**Comment by Gamemulatorer** [comment]
> What's that?

In graphics settings:>

**Comment by German-Herrador** [comment]
I can't find "Geometry Shader Culling". As for the Vulkan Backend that is the one that i always use.

Sorry if i didn't understand well what you are saying.

**Comment by Gamemulatorer** [comment]
I mean this

**Comment by German-Herrador** [comment]
I see, i don't have that option (using latest version mentioned above).
![Screenshot_20230311_172747_org ppsspp ppsspp](https://user-images.githubusercontent.com/109971356/224516136-fc01ef6b-8464-4583-b28c-9361989b8c2b.jpg)

You know why would that be?

**Comment by Gamemulatorer** [comment]
NVM :) I can also reproduce this issue on my snapdragon 439 adreno 505 phone.
This flickering issue might be related to this https://github.com/hrydgard/ppsspp/issues/8481

**Comment by German-Herrador** [comment]
With skip GPU readbacks enabled the character disappears. However the flickering floor is still present even with other graphical options. 
![Screenshot_20230311_214436_org ppsspp ppsspp](https://user-images.githubusercontent.com/109971356/224523137-9331b530-4da3-4307-afd8-492382181f23.jpg)

**Comment by Jbhfrgyuukvf** [comment]
Alguien sabe cómo reparar el error de las texturas del suelo de atv ofrroad pro

**Comment by hrydgard** [comment]
On PC with Vulkan, this looks and runs just fine, but on at least Mali Androids (tested on S8 and S21), the flickering block problem remains, unfortunately. Both for OpenGL and Vulkan. 

OK, I've found evidence that this is actually a CPU emulation bug, on ARM64.

On my Snapdragon Windows laptop, the bug reproduces if I run an ARM64 binary, but not x86-64 under emulation! So almost certainly this is a bug in the ARM64 jit.

Android on ARM64, jit: Bug
x64 emulated onsnapdragon, jit: No bug
ARM64 on snapdragon, jit: Bug
ARM64 on snapdragon, IR interpreter: No bug

Yes, this is an ARM64 jit bug!!! 

JIT debug tool tests:

* Disable GPR (yes GPR!) regalloc across instructions fixes it
* Disabling the entire VFPU doesn't fix it
* Disabling FPU doesn't fix it
* Disabling ALU or ALU_IMM or LSU (either one of the three) fixes it.
* Disabling just lw or sw or Comp_IType is enough to fix it.

So this is either a bug in the GPR regalloc itself, or some single instruction misuses the regalloc (but disabling any of the three heavy categories nudges it into working anyway, probably less pressure). Very strange!

No clue how to best debug this. Maybe selectively flush the registers in front of and behind certain categories of instructions... Or if it's a general bug in the regalloc, that won't find it... hm.

**Comment by hrydgard** [comment]
The CPU backend "Jit using IR" is unaffected. So that's a good workaround for now.

Considering whether it's time to abandon the pre-IR JITs, maybe... The IR jit does need a bit more work though.

**Comment by hrydgard** [comment]
The bad block is at 08aa6448 . It contains multiple "ins" instructions which are rare, not surprising if they trip up the regalloc somehow...

Hm, though, disabling in the jit doesn't fix it...

Ok, I got it, it's min and max where both arguments are imms (!)

**Comment by hrydgard** [comment]
All major issues are fixed here. The remaining issue is how far-away blocks of terrain look a little brighter, but without more accurate mip mapping I don't know if we can practically fix that. It's not a big deal when playing.

So I'm gonna close once #21238 is in.
