### ISSUE TITLE
Elements missing when scoping in Valkyria Chronicles II (ULUS-10515)

### ISSUE THREAD

**Issue by justafella** [hrydgard/ppsspp#13462]
### What happens?
Things such as objects from scenery disappear while scoping. Sometimes soldiers get cropped as well if they're in front of those objects. Happens on Vulkan and Direct3D 11.

### What *should* happen?
Everything should be fine as is with Direct3D 9 and OpenGL.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

- Windows 10 64 bit;
- Acer Aspire ES15;
- Intel Celeron QuadCore N3450;
- Intel HD Graphics 500 (driver ver. 27.20.100.8587);
- 4 GB RAM;
- ppsspp v1.10.3-735-ga0251eae2

![ULUS10515_00000](https://user-images.githubusercontent.com/65559598/93784595-31dab000-fbfb-11ea-9980-7e2d07aba430.jpg)
![ULUS10515_00001](https://user-images.githubusercontent.com/65559598/93784616-356e3700-fbfb-11ea-94ed-9b31c4fd09d2.jpg)
![ULUS10515_00002](https://user-images.githubusercontent.com/65559598/93784629-38692780-fbfb-11ea-8562-fbc9dabaa609.jpg)

Here is a Save State for testing:
[ULUS10515_1.00_2.zip](https://github.com/hrydgard/ppsspp/files/5256302/ULUS10515_1.00_2.zip)

**Comment by justafella** [comment]
As for cropped units:
![ULUS10515_00000](https://user-images.githubusercontent.com/65559598/93785742-6a2ebe00-fbfc-11ea-810b-2f32d6acddec.jpg)
![ULUS10515_00001](https://user-images.githubusercontent.com/65559598/93785750-6bf88180-fbfc-11ea-9f70-532ac1dc3f4c.jpg)
![ULUS10515_00002](https://user-images.githubusercontent.com/65559598/93785753-6c911800-fbfc-11ea-93b3-373ebfe04919.jpg)

**Comment by Panderner** [comment]
@justafella could you send me the GE Dump for scoping?

**Comment by justafella** [comment]
How do I do it?

**Comment by Panderner** [comment]
> How do I do it?

Just go to http://ppsspp-debugger.unknownbrackets.org/

**Comment by justafella** [comment]
Well, if I got that right, these are the files:

Scoping: 
[recording (2).zip](https://github.com/hrydgard/ppsspp/files/5256647/recording.2.zip)

Scoping+zoom:
[recording (3).zip](https://github.com/hrydgard/ppsspp/files/5256652/recording.3.zip)

**Comment by hrydgard** [comment]
Thanks, those will be useful!

**Comment by justafella** [comment]
> If you need it, whenever I come across the cropped unit problem again I'll bring its GE dump as well
Here it is:

Cropped unit on scope: [recording.zip](https://github.com/hrydgard/ppsspp/files/5272351/recording.zip)

Cropped unit on scope+zoom: [recording (1).zip](https://github.com/hrydgard/ppsspp/files/5272355/recording.1.zip)

Hope it helps you guys

**Comment by unknownbrackets** [comment]
Well, here's something interesting.

In Valkyria Chronicles 3, I reproduced easily.  In the GE debugger, I then disabled the depth clamp flag for a frame, which fixed it, because background stuff was clamping over the character.

But then I realized that it stayed fixed - nothing was turning clamp back on.  I played through a bunch of the game without it getting set back enabled.  Instead, returning to the chapter map finally re-enabled it.  It also re-enabled when going to the deploy screen, each time when "Now loading" was being shown.  Interestingly, for the loading into the mission - it did not set the depth clamp flag.

So it could be this is depth clamp behaving wrong - but it could also be that, somewhere, something is supposed to clear this and isn't?  Well, just a guess.  I can't find anything obvious that should be resetting it (like contexts on lists or signals or CALLs etc.)

-[Unknown]

**Comment by unknownbrackets** [comment]
The behavior described in #12058 should fix this.

-[Unknown]

**Comment by justafella** [comment]
I have tested the game with the same save state I provided back then, using the latest buildbot. My system remains the same apart from the graphics driver's version (that I keep updated). I tested it on all backends (with hardware transform on and then off) but only D3D9 worked properly. I couldn´t understand everything [here](https://github.com/hrydgard/ppsspp/issues/12058), so if there is something more I could do for testing as an end-user, I´ll gladly help.

**Comment by unknownbrackets** [comment]
If you try the artifacts in #14833, it should fix it on modern systems.

-[Unknown]

**Comment by justafella** [comment]
I haven't been able to test this yet because I can't seem to build it right. I'm all new to this and even with the instructions provided I'm still messing up somewhere. I'd be grateful if you could build it and send me a .zip or something.

**Comment by unknownbrackets** [comment]
There's a build attached to the under artifacts.

1. Go to https://github.com/hrydgard/ppsspp/pull/14833/checks.
2. Select Artifacts near the top right.
3. Select Windows x64 build (or similar.)

macOS, Windows ARM64, and Linux builds are available too.  These are not permanent however, and only last for 90 days after the code in the pull request is most recently updated.

-[Unknown]

**Comment by justafella** [comment]
IT IS FIXED!!!! Thank you!!!!! You may close the issue 🥇

**Comment by hrydgard** [comment]
Let's close it when that branch is merged - I'm not gonna merge it for 1.12, due to the risk of breakage. It will however be merged soon after that release, and then we can close this.

**Comment by vit9696** [comment]
Does not seem to fix the issue for me on macOS 11.6 with https://github.com/hrydgard/ppsspp/pull/14833 on Vulkan. OpenGL implementation is unsupported as explained in https://github.com/hrydgard/ppsspp/pull/14833#issuecomment-922460423.

<img width="1072" alt="Screenshot 2021-09-19 at 15 32 38" src="https://user-images.githubusercontent.com/4348897/133927661-a3a6abea-e150-4a88-af8b-d1cabfcc4a8a.png">

**Comment by hrydgard** [comment]
Vulkan on MacOS uses MoltenVK, it could be that it lacks support for the clip/cull distances.

**Comment by vit9696** [comment]
That somewhat surprised be, but you are right:

```
(lldb) p caps_.clipCullDistanceSupported
(bool) $0 = false
(lldb) p vulkan->GetDeviceFeatures().enabled.shaderClipDistance
(const VkBool32) $1 = 1
(lldb) p vulkan->GetDeviceFeatures().enabled.shaderCullDistance
(const VkBool32) $2 = 0
```

There is a note on that in https://github.com/KhronosGroup/MoltenVK/issues/203#issuecomment-419676902. Interestingly, culling appears to be rather rarely used by the games (https://github.com/KhronosGroup/MoltenVK/issues/203#issuecomment-494815290), so one can expect it not to land any soon. I wonder if the alternative can be found here.

**Comment by vit9696** [comment]
To be fair, [software one](https://github.com/unknownbrackets/ppsspp/commit/da50f87d2e5c4bc20d2df051b063ab61c61b4869) (i.e. `HardwareTransform` = `False`) does work fairly well for me with both OpenGL and Vulkan though after fixing up the hardware usage requirements in https://github.com/hrydgard/ppsspp/pull/14833#discussion_r711746731 without performance issues. However, this is a desktop (11700k clocked at 5.0 GHz to be precise), laptops may have bigger issues.

**Comment by justafella** [comment]
Is there any wayI can get an android build with these fixes? I have a Moto G9 Play with Qualcomm SM6115 Snapdragon 662 (11 nm) Octa-core (4x2.0 GHz Kryo 260 Gold + 4x1.8 GHz Kryo 260 Silver) Adreno 610

**Comment by Gamemulatorer** [comment]
> Is there any way I can get an android build with these fixes? I have a Moto G9 Play with Qualcomm SM6115 Snapdragon 662 (11 nm) Octa-core (4x2.0 GHz Kryo 260 Gold + 4x1.8 GHz Kryo 260 Silver) Adreno 610

You need to compile thsi https://github.com/hrydgard/ppsspp/pull/14833#discussion_r711746731 all by your self.

**Comment by unknownbrackets** [comment]
It'll get merged in not very long and included in git builds.  It should work on Adreno, but it won't yet work on Mali, so it's not a complete fix.  Be warned there are likely to be issues on some devices once it's merged, so I can't say for sure it'll work on your device.

-[Unknown]

**Comment by vit9696** [comment]
I did earlier: https://github.com/hrydgard/ppsspp/issues/13462#issuecomment-922474313, can retest the master version, but I am pretty sure it is still broken.

**Comment by vit9696** [comment]
Yes, the issue is still there. In master both hardware and software transforms are broken. The former is broken because culling is unsupported and the latter is broken, because nobody merged the second branch by @unknownbrackets. Funny enough, this branch is now entirely gone from GitHub, so I needed to restore the patch from my local copy (attached below).
[0001-GPU-Implement-cull-behavior-in-sw-transform.patch.zip](https://github.com/hrydgard/ppsspp/files/7377241/0001-GPU-Implement-cull-behavior-in-sw-transform.patch.zip)

**Comment by vit9696** [comment]
@hrydgard @unknownbrackets can we merge software culling in 1.13 to at least have a partial workaround? I believe Mali would also benefit.

**Comment by hrydgard** [comment]
Yeah, I think we should. It can be optimized, but that can be done after.

For Mali I'm planning to try a different approach using a geometry shader, too.

**Comment by vit9696** [comment]
Just to make it clear, with https://github.com/hrydgard/ppsspp/pull/15072 merged, disabling hardware transform fixes this issue on macOS. Thanks. I guess it might be useful to autoenable software culling based on the platform for affected games, but something like that is clearly out of the scope of this issue.

**Comment by Gamemulatorer** [comment]
This might improve now with https://github.com/hrydgard/ppsspp/pull/16142?

**Comment by justafella** [comment]
Closing this since it has been a long time since I opened it and it was solved a long time ago.
