### ISSUE TITLE
Dante's Inferno D3D11 Text Issue

### ISSUE THREAD

**Issue by Peduls** [hrydgard/ppsspp#13786]
### What happens?
Texts appears with black boxes around it when using the D3D11 renderer.

### What *should* happen?
Black boxes around text should not be present. This issue does not appear when using OpenGL/Vulkan.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Operating System
	Windows 10 Enterprise 64-bit
CPU
	Intel Core i7 7700 @ 3.60GHz
	Kaby Lake 14nm Technology
RAM
	32.0GB
Motherboard
	Micro-Star International Co. Ltd. Z390-A PRO (MS-7B98) (U3E1)
Graphics
	VG248 (1920x1080@144Hz)
	4095MB NVIDIA GeForce GTX 1070 (EVGA)
Storage
	465GB Samsung SSD 850 EVO 500GB (SATA (SSD))
	465GB Samsung SSD 850 EVO 500GB (SATA (SSD))
	2794GB TOSHIBA HDWD130 (SATA )
Optical Drives
	ASUS DRW-24B1ST j
Audio
	Realtek High Definition Audio
PPSSPP Version
	v1.10.3-1330
D3D11
	![ULUS10469_D3D11](https://user-images.githubusercontent.com/34750422/102592883-60203c80-40d1-11eb-9646-b44a3f5a44bd.png)

Vulkan
	![ULUS10469_Vulkan](https://user-images.githubusercontent.com/34750422/102592891-64e4f080-40d1-11eb-9abb-91366b39c12d.png)

**Comment by Peduls** [comment]
I am using the official PSP font. Not sure if that matters.

**Comment by hrydgard** [comment]
Font shouldn't matter, this is clearly a rendering issue. Maybe an easier-to-test case of #12188 ...

**Comment by unknownbrackets** [comment]
Could you try exporting a GE frame dump?  These help a lot.  Just make sure to export it when you see the issue - it's almost like a screenshot.  If you make it while the issue isn't happening, it won't help.

See here for instructions - it's not hard and works on Android too:
https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by nassau-tk** [comment]
D3D11 GE dump.
[NPJH50220_Dante'sInferno.zip](https://github.com/hrydgard/ppsspp/files/5800575/NPJH50220_Dante.sInferno.zip)

And, Light Green line appear on the screen bottom at OpenGL & Vulkan.
[NPJH50220_Dante'sInferno_Vulkan_OGL.zip](https://github.com/hrydgard/ppsspp/files/5800593/NPJH50220_Dante.sInferno_Vulkan_OGL.zip)

![image](https://user-images.githubusercontent.com/48179091/104286015-d01aba80-54f7-11eb-9c13-49a4f82a5601.png)

**Comment by unknownbrackets** [comment]
Can you load one of the first 4 dumps and post a screenshot of what they look like for you?  They look fine for me, so I just want to make sure I'm looking at the right area.

The green is caused by green below the framebuffer data is zeros, which the palette maps to green.

Interestingly, these dumps have multiple frames in them, implying the game is rendering above 60 FPS.

-[Unknown]

**Comment by nassau-tk** [comment]
@unknownbrackets 

Dumpfiles screenshot here!

[NPJH50220_0001.ppdmp on D3D11]
![image](https://user-images.githubusercontent.com/48179091/107135693-17059f80-6940-11eb-9948-4cee700038bb.png)

[NPJH50220_0003.ppdmp on D3D11]
![image](https://user-images.githubusercontent.com/48179091/107135711-4b795b80-6940-11eb-95a2-55a53eecfe41.png)

....? It seems clearly & correctly.
I forgot that these GEdump has problem or not....:sweat:

**Comment by nassau-tk** [comment]
@unknownbrackets 

PLease see these movie&notice below.
![image](https://user-images.githubusercontent.com/48179091/107135904-ff2f1b00-6941-11eb-9b98-2a4cf71eb694.png)



**[D3D11]**
https://user-images.githubusercontent.com/48179091/107135841-8e87fe80-6941-11eb-9cae-278466238caa.mp4

**[Vulkan (OGL&D3D9 same too)]**
https://user-images.githubusercontent.com/48179091/107135912-140bae80-6942-11eb-8e68-c3f39c608de7.mp4

**Comment by nassau-tk** [comment]
And, I re-checked the game on D3D11.
Probably, This issue can't seems on GEdump.

**[Screenshot & Movie.]**
https://user-images.githubusercontent.com/48179091/107136031-220dff00-6943-11eb-9e26-2d956c88405b.mp4

![image](https://user-images.githubusercontent.com/48179091/107135953-61881b80-6942-11eb-9dc5-a675c9c8ad94.png)
![image](https://user-images.githubusercontent.com/48179091/107135966-8086ad80-6942-11eb-8481-bba229d4f6d9.png)
![image](https://user-images.githubusercontent.com/48179091/107135969-8b414280-6942-11eb-9e2d-15c3d8861c0d.png)

**Comment by unknownbrackets** [comment]
Is this still an issue in recent git builds (https://buildbot.orphis.net/ppsspp/)?  This functionality may have improved recently.

-[Unknown]

**Comment by hrydgard** [comment]
This is indeed fixed now with #14678 . Nice!

**Comment by Mahnd** [comment]
Any chance for a Vulkan fix for the light green line described above? I assume it's fixed on the d3d11 renderer but under Linux/Vulkan I still see it.

**Comment by unknownbrackets** [comment]
Reducing the render resolution should fix it.  See here for an explanation of this sort of issue:

https://forums.ppsspp.org/showthread.php?tid=13556

-[Unknown]
