### ISSUE TITLE
Valkyrie Profile performance issue with vulkan, d3d9/11 

### ISSUE THREAD

**Issue by BParks21** [hrydgard/ppsspp#15398]
### Game or games this happens in

ULUS10107 Valkyrie Profile Lenneth

### What area of the game

Any traversable area with different rooms/locations that require loading (dungeons & towns) mainly. 

### Speed seen in PPSSPP

Drops to 90% speed with vulkan, around 94% with D3D9/11 & remains at 100% with ogl.

### Platform

Windows

### Mobile phone model or graphics card

GTX 1080ti

### PPSSPP version affected

v1.12.3-889-g50350e13a

### Last working version

Not sure

### Graphics backend (3D API)

Vulkan, D3D11/9

### Any other notes or things you've tried

Game drops to 90% game speed for no reason and audio will hiccup. Even at default settings using vulkan and D3D9/11. Not sure what's going on ogl is fine. Also happens with latest libretro core.

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the slowdown.
- [ ] Include logs or screenshots of issue.

**Comment by LunaMoo** [comment]
The problem by description sounds like texture scaling, but can't reproduce on my end with either texture scaling or default settings, at least with PPSSPP proper, not interested in libretro.

**Comment by BParks21** [comment]
> The problem by description sounds like texture scaling, but can't reproduce on my end with either texture scaling or default settings, at least with PPSSPP proper, not interested in libretro.

Happens with scaling off.

**Comment by ANR2ME** [comment]
is this happened only on recent builds?
if it's you should try to find out the last version that worked full speed

**Comment by BParks21** [comment]
@LunaMoo what version are you testing?

**Comment by LunaMoo** [comment]
I tested with fresh copy of v1.12.3-905-g4c095ce06 as well as with my personal build, saw no noticeable difference between backends.

 Checking frame graph I can see pretty huge spike in both Vulkan and OGL from decodetex, but I guess my RTX 3060 Ti is faster than GTX 1080 Ti by a decent margin so it's still well within budget to keep running at full speed, weaker hardware would probably see similar drop in OGL as in Vulkan.

**Comment by BParks21** [comment]
@hrydgard Are you able to reproduce? I'll do some testing with older builds.

**Comment by BParks21** [comment]
Yeah I can't produce this on 1.12.3 stable.

**Comment by unknownbrackets** [comment]
Have you had any luck determining a build this got slower in?  Is it any better in the latest git?

-[Unknown]

**Comment by BParks21** [comment]
No haven't had a chance to test older builds. It's the same in the latest git.

**Comment by EternalsDarkhole** [comment]
Try build before https://github.com/hrydgard/ppsspp/pull/15162

**Comment by BParks21** [comment]
Ok i will try as soon as I can

**Comment by Gamemulatorer** [comment]
This might improve via https://github.com/hrydgard/ppsspp/pull/15474

**Comment by BParks21** [comment]
Valkyrie Profile performance is fixed with Vulkan, but now Crisis Core is crashing after the intro logos on Vulkan not Opengl. Not sure if it's related.

**Comment by Gamemulatorer** [comment]
> Valkyrie Profile performance is fixed with Vulkan, but now Crisis Core is crashing after the intro logos on Vulkan and D3D11 not Opengl. Not sure if it's related.

Crashing after intro logo is not related to this issue you must create separate issue about that :)

**Comment by hrydgard** [comment]
I'll take a look at that, might be some bug in the fix.

**Comment by hrydgard** [comment]
Think it should be working now in -1067.

**Comment by BParks21** [comment]
> Think it should be working now in -1067.

Still crashing to the desktop for me in that version, vulkan and d3d.

**Comment by hrydgard** [comment]
Hmm, ok. I'll take another look. Got some non-default options enabled, like texture scaling?

**Comment by BParks21** [comment]
Yes I had xbrz x5 on. Turning it off prevents crashing. Used to work with it on.

**Comment by hrydgard** [comment]
Thanks, I got the crash to reproduce. Will fix.

**Comment by BParks21** [comment]
Ok thanks

**Comment by hrydgard** [comment]
Fixed in the next build.
