### ISSUE TITLE
PPSSPP running from UNC location is broken

### ISSUE THREAD

**Issue by MeruOtonashi** [hrydgard/ppsspp#15422]
### Game or games this happens in

None

### What area of the game / PPSSPP

When launching PPSSPP from a UNC location, it is able to create the folder structure to save the configuration settings + content for the memory card. However, when I change settings, they are not saved.
Attempting to save from any game loaded gives an error where it is unable to write the data.

To work around this, I mount the UNC location as a network drive (Y: drive). Once this is done, all settings can be saved, and all games are able to write save data.

### What should happen

The emulator should be able to handle UNC location paths when writing emulator configurations + game save data.
The emulator is able to read the information.
Example:
\\server-name\PSP

### Platform

Windows

### Mobile phone model or graphics card

Zotac GeForce RTX2070

### PPSSPP version affected

v1.12.3-980-g3bfab6326

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
#15424 makes this work for me.

You can also validate that simply creating a "SYSTEM" folder inside memstick/PSP makes this work.  If so, that change should resolve the issue.

In Config.cpp, we were bailing early for UNC paths, and this caused us never to create the parent directory.  That's why settings couldn't save.

-[Unknown]

**Comment by MeruOtonashi** [comment]
@unknownbrackets

Having the system folder there allows PPSSPP to read the configurations in UNC, yes. However, I am still not able to write the settings to the config file. Games still do not create save files. I've attachedan example of the in-game error that it does when attempting to save in UNC (Metal Slug XX USA). This happens to all games without exception.

![image](https://user-images.githubusercontent.com/80700793/156292290-37dfae5b-11c7-4cdf-8b1a-70af0e0505e3.png)

There's likely something underlying the code where it writes data that is affected.

**Comment by MeruOtonashi** [comment]
@unknownbrackets 
Actually, scratch my thought from the first post. I tested further and:
1. Can confirm that recreating the system folder from scratch, the settings do get saved properly from the emulator. I believe when I first reported this bug was when I did an direct PPSSPP executable replacement in the folder, so some settings from the really old version wasn't playing well with this.

2. For the above test with Metal Slug XX, it is unable to create the game save data because it is a new game. However, if I do create the save data first so that the folder structure gets created, I can then save properly going forward after.

So you're right, the issue you pointed to pre-create the folder will likely solve this.

**Comment by unknownbrackets** [comment]
Ah, there was another problem causing issues for savedata, the way it was creating the parent directory was broken there as well, but for a different reason.  That'll be fixed when that pull is merged as well, now.

-[Unknown]

**Comment by MeruOtonashi** [comment]
Awesome, thanks for your input.
Once the next dev build is done is done, I'll run a quick test and see if it is fully resolved and close this. :D 

Awesome work!

**Comment by MeruOtonashi** [comment]
Confirmed all working!
Thanks for the quick response y'all!!
