### ISSUE TITLE
Rendering issue in Assassin's Creed - Bloodlines

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#15821]
Reported by Totally Not Leo on Discord.

Apparently something is going wrong in post-processing, the upper left corner of the image is bright:

![image](https://user-images.githubusercontent.com/130929/183712244-354e63f7-aabe-4ae5-afd2-68164247f33b.png)

![image](https://user-images.githubusercontent.com/130929/183712258-9b59478f-b5f7-4908-8d01-41abe700bb70.png)

![image](https://user-images.githubusercontent.com/130929/183712275-a13b5fab-08f7-4e04-9b1b-9eee7675d22a.png)

**Comment by nassau-tk** [comment]
???
v1.13.1-291
Windows10 64-bit
Not happen the issue...


![image](https://user-images.githubusercontent.com/48179091/184668888-46acd4a6-2684-4fec-9f74-c680fc93a2bf.png)
[ULJM05571_0002.zip](https://github.com/hrydgard/ppsspp/files/9338311/ULJM05571_0002.zip)

**Comment by LunaMoo** [comment]
Probably the same thing which now happens in #6349, affecting only Open GL, renders the effect only in the upper left corner.

**Comment by Gamemulatorer** [comment]
Cannot reproduce this issue on my vivo y11 snapdragon 439 adreno 505 tried both opengl and vulkan.
![Screenshot_20221211_111019_2f85358b2198d26f8aca533d68bee793](https://user-images.githubusercontent.com/37603562/206884881-c582cf2a-60b2-4cec-a63d-c6eb5d76ab87.jpg)

**Comment by unknownbrackets** [comment]
I think there's a decent chance we have fixed this with other recent changes.  @mutoyoru can you try a recent git build?

-[Unknown]

**Comment by mutoyoru** [comment]
I only encounter this issue on Android devices which can only use OpenGL as rendering option. I used "v1.13.2-2483-g5c27b3e01" build (build date 2022-12-13 10:25:23) and it seems this issue is still persits. Also, the stable version can render top-left corner normally as it should be, but on the latest build I tried, it's broken also. I'll be adding a screenshot below:

![Screenshot_20221213-154434_PPSSPP](https://user-images.githubusercontent.com/96297884/207322957-0df3c76e-59c6-41a4-9597-b740a0cda206.png)

**Comment by hrydgard** [comment]
Thanks for testing, that's good info.

**Comment by Gamemulatorer** [comment]
I can also reproduce this in my vivo y51a snapdragon 410 adreno 306 also sometimes the game is crashing.
![Screenshot_20221213_214133](https://user-images.githubusercontent.com/37603562/207342075-ae74194f-3965-4d97-805c-e7fc2570733b.png)

**Comment by Xediox-zex** [comment]
![Screenshot_20231218_024018](https://github.com/hrydgard/ppsspp/assets/78394956/90322a24-764c-4064-804f-4352baddb4f6)
![Screenshot_20231218_024409](https://github.com/hrydgard/ppsspp/assets/78394956/133e6d15-416e-4c7d-b3fe-d880ad165ee9)

I am on a Vivo y71 (budget range phone) ,it has a snapdragon 425 with an Adreno 308 gpu , the Qualcomms website says 

APIs: OpenGL® ES 3.0

I've set it to run ,and the speed is good , not very good but not very choppy too ,the background is blurry ,but enough to read text , also if I I get hit , an overlay completely ruins the experience.
Hope this helps ,
Please look into it

**Comment by hrydgard** [comment]
@Xediox-zex The graphical overlay glitch is interesting. Are you able to catch it in a GE frame dump?

https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump

**Comment by Xediox-zex** [comment]
@hrydgard 
Unsure of what record means in the docs ,screen recording ?

**Comment by Xediox-zex** [comment]
Though these are the current observations 
![Screenshot_20231218_123914](https://github.com/hrydgard/ppsspp/assets/78394956/77763178-d1a4-4278-b0ce-6dbaf5035986)

**Comment by hrydgard** [comment]
Please follow the instructions in https://github.com/hrydgard/ppsspp/wiki/How-to-create-a-frame-dump .

**Comment by Xediox-zex** [comment]
[ULUS10455.zip](https://github.com/hrydgard/ppsspp/files/13728662/ULUS10455.zip)
 

Here's the frame dump I've created
