### ISSUE TITLE
Mahjong Artifacts missing part of the game play area

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#15828]
### Game or games this happens in

 Mahjong Artifacts  NPUZ00062

### What area of the game / PPSSPP

missing part of the game play area
![PPSSPP v1 13 1-249-gf80dd088b - NPUZ00062 _ Mahjongg Artifacts 10_08_2022 9_57_12 PM](https://user-images.githubusercontent.com/2696404/183920334-6975b888-3fc5-4b53-9915-774ef244a66c.png)

here is a GE Dump
[NPUZ00062.zip](https://github.com/hrydgard/ppsspp/files/9300644/NPUZ00062.zip)

### What should happen

this is what it is supposed to look like
![0-256-03](https://user-images.githubusercontent.com/2696404/183920751-3c390819-76db-45ba-84b3-0ec0ae2f4a12.jpg)

### Platform

Windows

### Mobile phone model or graphics card

AMD RX 580

### PPSSPP version affected

PPSSPP v1.13.1-249

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

**Comment by unknownbrackets** [comment]
I'm pretty sure this is depth related - the dump unfortunately doesn't include the board, which must've been rendered in a previous frame.  A frame dump while using the software renderer would be helpful.

That said, the minz and maxz are both set to exactly 0, and I think some accuracy issue is causing the top left (which does use zero depth values) not render.

-[Unknown]

**Comment by benderscruffy** [comment]
here is a GE Dump with software renderer

[NPUZ00062.zip](https://github.com/hrydgard/ppsspp/files/9305510/NPUZ00062.zip)

**Comment by sum2012** [comment]
Last bad  v1.13.1-289-ga35d26190
First good v1.13.1-291-g8d0c84bf0
That mean #15845 
It is  simple workaround for fix for another game.
Not sure can close

**Comment by hrydgard** [comment]
That should be fixed once #15858 is in, since the feature that #15845 fixes goes away and is replaced with a different method to achieve the same thing.

**Comment by unknownbrackets** [comment]
Is this still working now in the latest git?

-[Unknown]

**Comment by sum2012** [comment]
v1.13.1-381-g5046cbd01 still working

**Comment by unknownbrackets** [comment]
Thanks for confirming - I'll close this then.

-[Unknown]

**Comment by benderscruffy** [comment]
v1.13.1-391-g5097a6a8f
still a problem for me
here is 2 different GE dumps
maybe an AMD problem
![NPUZ00062_00001](https://user-images.githubusercontent.com/2696404/185780879-59284304-6e4a-4724-a841-387854888d01.jpg)
![NPUZ00062_00000](https://user-images.githubusercontent.com/2696404/185780880-09ea253f-900d-4a55-9e54-a8359c47b308.jpg)
[NPUZ00062a.zip](https://github.com/hrydgard/ppsspp/files/9388636/NPUZ00062a.zip)
[NPUZ00062.zip](https://github.com/hrydgard/ppsspp/files/9388637/NPUZ00062.zip)

**Comment by sum2012** [comment]
Same As me (Nvidia)
Break by #15871 or #15870

**Comment by hrydgard** [comment]
Thanks, will look into it.

**Comment by sum2012** [comment]
@benderscruffy  Cab you try v1.13.1-381-g5046cbd01 ?

**Comment by benderscruffy** [comment]
still happens in v1.13.1-381-g5046cbd01

**Comment by sum2012** [comment]
@benderscruffy How about  v1.13.1-291-g8d0c84bf0 ?

**Comment by unknownbrackets** [comment]
Strangely, even the software renderer frame dumps have black sections (the texture is black.)  I suspect this game renders the board either on CPU or to a temporary buffer, and then just textures from that.  Somehow, some parts of that are coming out black.

It could be a misdetected framebuffer suboffset.  That said, I don't see why software would have black textures...

-[Unknown]

**Comment by benderscruffy** [comment]
here is a renderdoc
[mahjong.zip](https://github.com/hrydgard/ppsspp/files/9488474/mahjong.zip)

**Comment by benderscruffy** [comment]
Closing as have new system and cannot test on old pc

**Comment by hrydgard** [comment]
Like the others, this is not likely to be specific to your old pc, so I'm reopening.

**Comment by sum2012** [comment]
v1.16.6-372-gc3f881b7a
I am using integrated AMD gpu of cpu  (AMD Ryzen 7900)
![1](https://github.com/hrydgard/ppsspp/assets/2177532/87e2b4a5-5642-454f-b77d-5d6599757e7d)

**Comment by hrydgard** [comment]
@sum2012 could you try this again? I suspect a recent fix might have taken care of that.

**Comment by sum2012** [comment]
soft gpu get assort 
![5](https://github.com/user-attachments/assets/cf2a1a9a-de91-45c2-8d0a-985c75332925)

**Comment by hrydgard** [comment]
Hm, ok, different problem then. Also, thanks for reporting the softgpu one, I'll fix it shortly!

**Comment by hrydgard** [comment]
two more things, sorry @sum2012 :

Could you get a GE frame dump? I can't find one in the previous posts.

Also, I can't figure out how that can happen, looking at the code :/

What GPU do you have? Do you enable frameskipping or something?

**Comment by hrydgard** [comment]
Never mind, I think I figured out the assert. #19532 

The rendering bug in this game is still a mystery though, will at least need a framedump. But fortunately playing with the software renderer should be fine in a game like this.

**Comment by sum2012** [comment]
v1.17.1-1275 the softgpu is fixed.
framedump is in the first post
![4](https://github.com/user-attachments/assets/a63529b5-d6e5-43da-9e09-5a543b96a1bb)

**Comment by Jack54guythecoder** [comment]
Still broken as of v1.19.2-121-gf3a67a4285.

[NPUZ00062_0001.zip](https://github.com/user-attachments/files/20805258/NPUZ00062_0001.zip)

Heres a framedump.

**Comment by Jack54guythecoder** [comment]
@hrydgard  Did you figured something out?

**Comment by hrydgard** [comment]
No, just tagging for investigation

**Comment by Jack54guythecoder** [comment]
UPDATE> I found another game from the same devs that has this issue, THE MYSTERY OF THE CRYSTAL PORTAL, maybe if this is fixed, the other game can be as well.


CAPTURE> 

[NPUZ00063_0001.zip](https://github.com/user-attachments/files/21205590/NPUZ00063_0001.zip)
Weird that the SERIAL ID itself is sequential as well, lol

P.T: Heres a screenshot of another section which has the same issue

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/b6e4495e-d633-47cd-af23-953d52ef1370" />
It does not correct itself when zooming in and out in THIS game.

**Comment by hrydgard** [comment]
From the framedump, it's a bad framebuffer match during texturing, it has identified a probably unused depth buffer as the source for texturing, instead of the actual data behind it in memory. I'll see if I can come up with some safe heuristic..

**Comment by Jack54guythecoder** [comment]
[NPUZ00062_0003.zip](https://github.com/user-attachments/files/25249211/NPUZ00062_0003.zip)

Reopen, it still does not work.

**Comment by hrydgard** [comment]
Ok, I'll take a look. At least we fixed the crystal portal heh.

**Comment by hrydgard** [comment]
It's a slightly different problem with texture/framebuffer matching. It uses four large textures that are created as render targets for some reason, and we detect them as overlapping and it's a bit of a mess. I have an idea.

**Comment by Jack54guythecoder** [comment]
(sigh) why is this still broken?
And no, i dont have any special config.

[NPUZ00062_0004.zip](https://github.com/user-attachments/files/25471056/NPUZ00062_0004.zip)

**Comment by Jack54guythecoder** [comment]
v1.19.3-1812-gd81785496f. is the vesrsion, btw.

Now, in order to repllicate, you just have to zoom in and out and move around with the analog stick.

**Comment by hrydgard** [comment]
@Jack54guythecoder Sorry. The game's rendering is highly unusual, it doesn't really work like any other games, so our framebuffer caching system which was designed for games with a very different usage pattern gets really confused by it.

The remaining problem appears to be that if a render target isn't used or textured from for a number of frames, we throw it away. Most games update render targets every frame or very often, but this game uses large ones as background for some strange reason. And when you zoom in, one or multiple may be unused for some time and gets thrown away. I think I'll implement a compat flag for this game, any more invasive changes are too risky at this point in the release process.

Save states will still have the same problem unfortunately.
