### ISSUE TITLE
Cards not rendering

### ISSUE THREAD

**Issue by jacocal** [hrydgard/ppsspp#17470]
### Game or games this happens in

Yu-Gi-Oh Tag Force 6 - ABDEAA27

### What area of the game

At any point in game, the card texture or the image belonging to the cards are not rendering

### What happens

Cards are showing as a black rectangle

![image](https://github.com/hrydgard/ppsspp/assets/9086269/d3753703-0018-4468-a3de-8c389c89f692)

### What should happen

An image of the card should be showing

![image](https://github.com/hrydgard/ppsspp/assets/9086269/8a8733b8-1591-492a-bea9-73fe561eb157)

### GE frame capture

[ULJM05940.zip](https://github.com/hrydgard/ppsspp/files/11492403/ULJM05940.zip)

### Platform

Windows

### Mobile phone model or graphics card

GeForce RTX 2070

### PPSSPP version affected

1.15

### Graphics backend (3D API)

Direct3D 11

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
That's weird. If you load the framedump up, does it display? Because it does for me, making it not that great for debugging the issue.

Did you make the frame dump in software mode? If so, please try to make a second one with it off.

**Comment by hrydgard** [comment]
Briefly looking into how the card is drawn, it's composited together from various pieces on a separate framebuffer, then that one is drawn as a texture.

Do you have "Skip buffer effects" or another speed hack option enabled?

**Comment by jacocal** [comment]
@hrydgard For your first question, the image in the "Not Working" section as well as the dump file were taken with the software rendering off, the one in the working section was taken in with the software rendering on.

For the second question, I have the following setting:
![image](https://github.com/hrydgard/ppsspp/assets/9086269/32573675-e640-4854-8ddf-2e1e1edfc848)

**Comment by hrydgard** [comment]
yes, I can see you have "Skip buffer effects" checked. Exit the game and uncheck it, it should fix the problem.

And we should mark this game as "requires buffer effects" so you get a warning...

**Comment by hrydgard** [comment]
Confirmed that it was skip buffer effects. Closing.

**Comment by jacocal** [comment]
The Game is indeed ABDEAA27, it was patched with the English Patch but issue persists on the JP version as well with the skip buffering effects

**Comment by hrydgard** [comment]
Yeah, that's as expected. Thanks, I'll add the ID to the list of games that will nag you if you enable skip buffer effects.

**Comment by hrydgard** [comment]
Though that ID seems to be missing a letter? Game IDs are 9 letters/numbers., like ULJM05940. Also your framedump is called that, so I'm inclined to believe that's the actual ID?

**Comment by unknownbrackets** [comment]
ABDEAA27 is the CRC I think.

-[Unknown]

**Comment by hrydgard** [comment]
Oh duh, that makes more sense.
