### ISSUE TITLE
"Vulkan lost"

### ISSUE THREAD

**Issue by qazxsw4320** [hrydgard/ppsspp#17485]
### Game or games this happens in

God of War chains of olympus

### What area of the game

Right when the game starts.

### What happens

Right when I open the game it crashes while using vulkan and this also happens on the God of War ghkst of sparta as well. Right when I open the game it says "vulkan lost." This did not happen on version 1.14.4 but once 1.15 released ot started to happen. Also I have not used any texture packs or anything game like that.

### What should happen

Game should not crash while using vulkan.
![Screenshot 2023-05-20 110012](https://github.com/hrydgard/ppsspp/assets/122139385/72cb405b-0fdb-405d-b604-d943d9091c25)

### Platform

Windows

### Mobile phone model or graphics card

Intel (R) UHD Graphics 605

### PPSSPP version affected

1.15.3

### Last working version

1.14.4

### Graphics backend (3D API)

Vulkan

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

**Comment by ANR2ME** [comment]
If you were using a release version, try using the latest dev build from https://buildbot.orphis.net/ppsspp/ in case this issue has been resolved.

**Comment by qazxsw4320** [comment]
I tried using a latest dev build but I'm still having the same problems.

**Comment by hrydgard** [comment]
Is it possible to download new drivers for your GPU from Intel.com or something? 

I'm pretty sure that any bugs here will be in the driver, it's impossible for us to stay compatible with every old driver version for every old GPU - all we can do is try to follow the spec, and we pass the Vulkan validation layers nearly perfectly.

The only chance that we might be able to provide some workaround is if you could try a bunch of versions between 1.14.4 and 1.15 from https://buildbot.orphis.net/ppsspp/index.php?m=fulllist to find out exactly when it started crashing, you should be able to narrow it down in about 11 tries if you go about it optimally (binary search, halve the range every time).

**Comment by qazxsw4320** [comment]
Updating the drivers did the trick thank you. I do have a it of performance issues though but other then that it's working
