### ISSUE TITLE
New sceAtrac implementation: Testing and results

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#20125]
Now that #20098 is merged:

Get build 1433 or higher (the new sceAtrac implemenation is now on by default).

IMPORTANT: When testing, do not load from an old savestate, or a new savestate produced from an old savestate. Restart and load in-game, otherwise you won't get the new implementation!

## Games confirmed fixed with the new impl

- [x] #6663 
- [x] #19994
- [x] #15233
- [x] #19082
- [x] #19177
- [x] #20025
- [x] #5564 
- [x] #7708
- [x] #11899 (sceSas integration)
- [x] #11091
- [x] #18923
- [x] #10139
- [x] #8179
- [x] #19236
- [x] #13773
- [x] #12298
- [x] #8076
- [x] #12083 
- [x] #16904
- [x] #20150

## Things that need __sceSasConcatenateATRAC3 (should now work since #20156 )

[Reports](https://report.ppsspp.org/logs/kind/197)

- [x] #6511 (sceSas integration) 
- [x] #9066 (needs __sceSasConcatenateATRAC3, see #20128 ) 
- [x] Angus Hates Aliens
...more

## Games that need testing with the new impl

- [ ] #8269
- [ ] Last Ranker needs testing due to comments in #7638

## Things that were previously broken, and the new impl doesn't fix

- [ ] #11205
- [ ] #9067 (sceAudioCodec used directly, so not really sceSas)
- [ ] #8647 - it spams the log and fails to loop, but does somehow play for a bit.
- [ ] #19640

## Hack PRs that have been closed

- [x] #19015
- [x] #18396
- [x] #7638

## Compat.ini settings that can be removed

Actually, probably shouldn't - we'll still have to support the old sceAtrac implementation for savestate compatibility. But there's `[AtracLoopHack]`.

**Comment by VermeilChan** [comment]
Tested this with ppsspp_win_v1.18.1-1386-g9190a83035 in metal slug and it seems like it fixed it (I enabled experimental sceAtrac)

**Comment by sum2012** [comment]
Passport to London fix in v1.18.1-1386-g9190a83035 with experimental sceAtrac.
@hrydgard I cannot output "debug" log level now in normal  release ?

**Comment by hrydgard** [comment]
Hm, you're supposed to, at least on desktop. On Android/iOS we cut debug logs in normal releases although I am considering reversing that, the performance change is small...

**Comment by sum2012** [comment]
Castlevania Rondo of Blood original BGM choppy/intermittent  fix in v1.18.1-1386-g9190a83035 with experimental sceAtrac.
Silverfall (ULES00808) soundtrack loop after a while fix in v1.18.1-1386-g9190a83035 with experimental sceAtrac (No need loop hack)

**Comment by hrydgard** [comment]
NABN00B reports occasional crashes in GTA LCS. 

Suspiciously, the BSS section of the sceAtrac module we load is tiny, not enough memory allocated for our contexts, so we might be stomping on some memory we shouldn't stomp on. Will need to fix.

**Comment by aeroallways2** [comment]
The Monster Hunter audio popping is not fixed by the experimental sceAtrac.

**Comment by hrydgard** [comment]
@aeroallways2 thanks for reporting.

**Comment by hrydgard** [comment]
@sum2012 #11091 is also fixed right?

**Comment by hrydgard** [comment]
I don't understand - it doesn't softlock anymore, right?

**Comment by hrydgard** [comment]
Oh I see, I didn't read too carefully. Let's just force Simulate UMD delays in the game then, I don't know why we haven't.. we've had a compat.ini setting for that for some time.

**Comment by tilkinsc** [comment]
I see you are learning a lot. Could you document specifically the Atrac2 format, since it seems like it hasn't.

**Comment by LunaMoo** [comment]
He already does that: [Atrac3, Atrac3+ and other codecs](https://www.ppsspp.org/docs/development/ppsspp-internals/atrac/)
Note that there's no Atrac2, it's just current internal name of the new implementation.

**Comment by FATCatAndroid12** [comment]
***REGRESSION!!!***
The new sceAtrac broke Digimon Adventure audio!

**Comment by FATCatAndroid12** [comment]
The new sceAtrac fixed Shrek! https://github.com/hrydgard/ppsspp/issues/10139

**Comment by FATCatAndroid12** [comment]
Brave Story New Traveller instantly crash with New sceAtrac enable latest apk build https://github.com/hrydgard/ppsspp/pull/20132/commits/0aec6aeddd75f9ff59053e13ade81ce7b778d8d8

**Comment by hrydgard** [comment]
Thanks for reporting!

**Comment by hrydgard** [comment]
@FATCatAndroid12 Digimon Adventure is now fixed.

Couldn't reproduce the brave story crash.

**Comment by FATCatAndroid12** [comment]
> [@FATCatAndroid12](https://github.com/FATCatAndroid12) Digimon Adventure is now fixed.

Yes the audio is fixed but the crash during in-game save didnt
![Image](https://github.com/user-attachments/assets/741d7275-d676-4e4b-b40d-4be044c00b45)

> Couldn't reproduce the brave story crash.

Still instantly crashing on my redmi note 9
![Image](https://github.com/user-attachments/assets/cca083b8-049a-4d27-998d-ad8842aac58d)

**Comment by FATCatAndroid12** [comment]
Uninstalled and Re-installed ppsspp v1.18.1-1413 Brave Story New Traveller can no longer produce crashing but Digimon Adventure save in-game still crashing..

**Comment by hrydgard** [comment]
Hm, weird. Well, next time you reinstall to try to fix something, keep the PPSSPP ini file. Then we could see if the issue is some setting ..

**Comment by FATCatAndroid12** [comment]
I discover the culprit why Brave Story crash before introduction video its because of skip-buffer!

**Comment by hrydgard** [comment]
interesting! I'll have to look into that separately.

**Comment by hrydgard** [comment]
Went ahead and turned this one by default, allowing me to close all the confirmed fixed issues. Remaining ones still need testing!

**Comment by sum2012** [comment]
Add regression #20145

**Comment by FATCatAndroid12** [comment]
https://github.com/hrydgard/ppsspp/issues/10139#issuecomment-2746913524

**Comment by Tathagata-0** [comment]
I'm getting a crash in Sol Trigger unless "Use the old sceAtrac implementation" is enabled, even at default settings otherwise. I couldn't find out where the log is located after enabling it, but the crash happens at the same point every time, here's a save file shortly before it (after loading and proceeding a few steps forward to a scene, then the game crashes at the start of the scene after that): 

[NPJH50619DATA00.zip](https://github.com/user-attachments/files/19437282/NPJH50619DATA00.zip)

**Comment by hrydgard** [comment]
@Tathagata-0 #20156 should have fixed the issue.

**Comment by Tathagata-0** [comment]
@hrydgard Yep, looks like that fixed it, thanks a ton! 🙏

**Comment by FATCatAndroid12** [comment]
> I don't think there are any remaining regressions left now? So maybe can move on to other things for a while before fixing the last few problems..


Digimon Adventure opening fmv after ***Bandai*** logo hang for 3 seconds and then crashing out the emulator no blue screen crashscreen.

**Comment by hrydgard** [comment]
Well that option has done precisely nothing for a long time, by mistake. Likely you're running out of ram with it on... I'm considering just deleting it, it's very rarely useful these days.

**Comment by tilkinsc** [comment]
> [@Tathagata-0](https://github.com/Tathagata-0) [#20156](https://github.com/hrydgard/ppsspp/pull/20156) should have fixed the issue.
> 
> I don't think there are any remaining regressions left now? So maybe can move on to other things for a while before fixing the last few problems..

Guinea pig testing is the best way run tests! Trial by fire!

**Comment by NABN00B** [comment]
#### Last Ranker
Took a quick look on `v1.19.3-651-gddc16c9227`:
- sound doesn't break after battle
- no freeze

log:
<img width="1628" height="631" alt="Image" src="https://github.com/user-attachments/assets/6e2ee7ea-d725-4003-83c5-fd9b58a82c9d" />
Not sure if it warrants a new issue.

**Comment by hrydgard** [comment]
Invalid start bit is kinda odd. But to be clear, you're saying that atrac playback is still working?

all the file not found stuff is weird..

**Comment by NABN00B** [comment]
#### Last Ranker

Going through the intro battle and the first two random encounters in the game, I didn't notice any regression in audio. BGM, ambient and SFX play the same in both versions.

I'm unable to reproduce the ATRAC error entry.

`v1.17.1` log:
```
56:10:585 Core\System.cpp:433 N[BOOT]: PPSSPP v1.17.1 Windows 64 bit
56:10:624 Core\Compatibility.cpp:151 N[G3D]: UnitsPerMeter for ULJM05676: 0.000000
56:11:885 root         W[G3D]: Vulkan\ShaderManagerVulkan.cpp:527 Shader cache version mismatch, 53, expected 51
56:11:885 root         W[G3D]: Vulkan\GPU_Vulkan.cpp:117 ShaderManagerVulkan failed to load cache header.
56:11:885 root         W[G3D]: Vulkan\GPU_Vulkan.cpp:137 Incompatible Vulkan pipeline cache - rebuilding.
56:11:902 root         N[BOOT]: UI\EmuScreen.cpp:389 Booted D:/Program Files/Emulators/PPSSPP/memstick/PSP/GAME/Last Ranker (Japan).iso...
56:11:913 main         W[SCEUTIL]: HLE\sceImpose.cpp:80 00000000=sceImposeSetLanguageMode(0, 0): ignoring requested language
56:11:914 main         I[SCEUTIL]: HLE\sceUtility.cpp:543 0=sceUtilityLoadModule(00000301)
56:11:956 main         I[SCEUTIL]: HLE\sceUtility.cpp:543 0=sceUtilityLoadModule(00000300)
56:11:981 main         I[SCEUTIL]: HLE\sceUtility.cpp:543 0=sceUtilityLoadModule(00000302)
56:12:007 main         I[SCEUTIL]: HLE\sceUtility.cpp:543 0=sceUtilityLoadModule(00000303)
56:12:465 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:1 Creating 5551 FBO at 04000000/04088000 stride=512 480x272 (force=1)
56:12:469 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:1 Creating 8888 FBO at 04000000/04110000 stride=512 480x272 (force=1)
56:12:470 main         W[G3D]: Common\FramebufferManagerCommon.cpp:878 Reinterpret detected from 04000000_5551 to 04000000_8888
56:12:474 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2026 Framebuffer size 00088000 conspicuously not matching copy size 00044000 for dest in NotifyFramebufferCopy. Ignoring.
56:12:474 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2145 Memcpy fbo upload 04000000 -> 04000000 (size: 88000)
56:12:566 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:1 Creating 8888 FBO at 04088000/04110000 stride=512 480x272 (force=1)
56:13:803 main         I[SCEUTIL]: Dialog\PSPSaveDialog.cpp:122 sceUtilitySavedataInitStart(0893be00) - LIST (11)
56:13:803 main         I[SCEUTIL]: Dialog\PSPSaveDialog.cpp:123 sceUtilitySavedataInitStart(0893be00) : Game key (hex): 1F9187CE35949A110DE5F1F888019801
56:13:803 main         W[SCEUTIL]: Dialog\PSPDialog.cpp:46 Game requested language 0, ignoring and using user language
56:57:475 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2145 Memcpy fbo upload 04000000 -> 04000000 (size: 200000)
56:57:490 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:1 Creating 5551 FBO at 04000000/04088000 stride=512 480x272 (force=1)
56:57:491 main         W[G3D]: Common\FramebufferManagerCommon.cpp:878 Reinterpret detected from 04000000_8888 to 04000000_5551
56:57:492 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2026 Framebuffer size 00044000 conspicuously not matching copy size 00088000 for dest in NotifyFramebufferCopy. Ignoring.
56:57:492 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2145 Memcpy fbo upload 04000000 -> 04000000 (size: 44000)
56:57:562 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:1 Creating 5551 FBO at 04044000/04088000 stride=512 480x272 (force=1)
56:57:564 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2762 Block transfer upload 0968cd50 -> 040cc040 (512x1 0,0 bpp=4)
56:57:564 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:1 Resizing 8888 FBO at 04088000/04110000 stride=512 from 480x272 to 512x272 (force=0, skipCopy=1)
56:58:591 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:223 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
57:25:774 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2706 Block transfer readback 512x272 2bpp from 04044000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
59:15:741 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2706 Block transfer readback 512x272 2bpp from 04044000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
59:17:576 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2706 Block transfer readback 512x272 2bpp from 04000000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
59:19:229 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2706 Block transfer readback 512x272 2bpp from 04044000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
59:19:262 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:223 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
59:20:339 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2706 Block transfer readback 512x272 2bpp from 04000000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
59:21:706 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:223 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
59:22:759 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2706 Block transfer readback 512x272 2bpp from 04000000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
59:23:504 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:223 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
59:24:556 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2706 Block transfer readback 512x272 2bpp from 04000000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
59:25:189 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:223 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
59:26:242 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2706 Block transfer readback 512x272 2bpp from 04000000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
59:27:442 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:223 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
59:28:495 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2706 Block transfer readback 512x272 2bpp from 04044000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
59:32:703 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2706 Block transfer readback 512x272 2bpp from 04000000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
01:07:323 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:1 Creating 5551 FBO at 041faff0/04088000 stride=128 128x128 (force=1)
01:07:324 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2145 Memcpy fbo upload 041faff0 -> 041faff0 (size: 8000)
01:07:324 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:1 Resizing 5551 FBO at 04000000/04088000 stride=512 from 480x272 to 512x272 (force=0, skipCopy=0)
01:07:439 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:1 Resizing 5551 FBO at 04044000/04088000 stride=512 from 480x272 to 512x272 (force=0, skipCopy=0)
01:14:134 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:223 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
01:34:609 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:223 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
01:41:391 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:223 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
01:44:137 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:223 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
01:46:489 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:223 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
02:04:740 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:1 Creating 5551 FBO at 041faff0/04088000 stride=128 128x128 (force=1)
02:04:740 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2145 Memcpy fbo upload 041faff0 -> 041faff0 (size: 8000)
02:17:097 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:223 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
02:21:176 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:223 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
02:23:329 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:223 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
02:49:399 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:1 Creating 5551 FBO at 041faff0/04088000 stride=128 128x128 (force=1)
```

`v1.19.3-651-gddc16c9227` log:
```
04:17:012 unknown      I[AUDIO]: HW\GranularMixer.cpp:74 Mixer is initialized
04:17:015 Main         D[IO]: VFS\VFS.cpp:14 Registered VFS for prefix : D:/Program Files/Emulators/PPSSPP-devbuild/assets
04:17:015 Main         D[IO]: VFS\VFS.cpp:14 Registered VFS for prefix : D:/Program Files/Emulators/PPSSPP-devbuild
04:17:018 Main         I[IO]: File\FileUtil.cpp:984 CreateEmptyFile: D:/Program Files/Emulators/PPSSPP/memstick/_writable_test.$$$
04:17:018 Main         I[IO]: File\FileUtil.cpp:565 Delete: file D:/Program Files/Emulators/PPSSPP/memstick/_writable_test.$$$ was deleted.
04:17:018 Main         I[IO]: Core\System.cpp:837 Creating 'D:/Program Files/Emulators/PPSSPP/memstick/PSP' and subdirs:
04:17:019 Main         I[LOADER]: Core\Config.cpp:1217 Loading config: D:/Program Files/Emulators/PPSSPP/memstick/PSP/SYSTEM/ppsspp.ini
04:17:452 EmuThread    W[LOADER]: UI\NativeApp.cpp:318 Did not switch failed backend! 3
04:19:968 ExecLoader   N[BOOT]: Core\System.cpp:595 PPSSPP v1.19.3-651-gddc16c9227
04:19:994 ExecLoader   N[G3D]: Core\Compatibility.cpp:167 UnitsPerMeter for ULJM05676: 0.000000
04:20:151 ExecLoader   W[G3D]: Vulkan\ShaderManagerVulkan.cpp:518 Shader cache version mismatch, 51, expected 53
04:20:151 ExecLoader   W[G3D]: Vulkan\GPU_Vulkan.cpp:118 ShaderManagerVulkan failed to load cache header.
04:20:151 ExecLoader   W[G3D]: Vulkan\GPU_Vulkan.cpp:146 Incompatible Vulkan pipeline cache - rebuilding.
04:20:156 root         N[BOOT]: UI\EmuScreen.cpp:378 Booted D:/Program Files/Emulators/PPSSPP/memstick/PSP/GAME/Last Ranker (Japan).iso...
04:20:166 main         W[SCEUTIL]: HLE\sceImpose.cpp:77 0=sceImposeSetLanguageMode(0, 0): ignoring requested language
04:20:618 main         W[SCEIO]: HLE\sceIo.cpp:971 ERRNO_FILE_NOT_FOUND=sceIoGetstat(ms0:/PSP/SAVEDATA/ULJM05676DATDATA/INSTDAT.VLD, 09fe6910): FILE NOT FOUND
04:20:675 main         W[SCEIO]: HLE\sceIo.cpp:971 ERRNO_FILE_NOT_FOUND=sceIoGetstat(ms0:/PSP/SAVEDATA/ULJM05676DATDATA/INSTDAT.VLD, 09fe68f0): FILE NOT FOUND
04:20:698 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:8 Reinterpret detected from 04000000_5551 to 04000000_8888
04:20:701 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:2 Framebuffer size 00088000 conspicuously not matching copy size 00044000 for dest in NotifyFramebufferCopy. Ignoring.
04:20:701 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:2 Memcpy fbo upload 04000000 -> 04000000 (size: 88000)
04:21:982 main         I[SCEUTIL]: Dialog\PSPSaveDialog.cpp:143 sceUtilitySavedataInitStart(0893be00) - LIST (11)
04:21:982 main         I[SCEUTIL]: Dialog\PSPSaveDialog.cpp:144 sceUtilitySavedataInitStart(0893be00) : Game key (hex): 1F9187CE35949A110DE5F1F888019801
04:21:982 main         W[SCEUTIL]: Dialog\PSPDialog.cpp:70 Game requested language 0, ignoring and using user language
04:21:982 main         I[SCEUTIL]: Dialog\PSPSaveDialog.cpp:327 Return value: 0
04:22:182 SaveIO       I[SCEUTIL]: Dialog\SavedataParam.cpp:1270 LIST (searchstring=ULJM05676DATA??): 0 files (max: 20)
04:48:616 main         W[SCEIO]: HLE\sceIo.cpp:971 ERRNO_FILE_NOT_FOUND=sceIoGetstat(ms0:/PSP/SAVEDATA/ULJM05676DATDATA/INSTDAT.VLD, 09fe6890): FILE NOT FOUND
04:48:883 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:2 Memcpy fbo upload 04000000 -> 04000000 (size: 200000)
04:48:900 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:2 Copy: Multiple dst vfb candidates for (dst: 04044000, size: 278528):
 - 04000000 8888 480x272 y=136 h=136
 - 04044000 5551 480x272 y=0 h=272 *
 (COLOR)
04:48:900 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:2 Memcpy fbo upload 04044000 -> 04044000 (size: 44000)
04:48:922 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:8 Reinterpret detected from 04000000_8888 to 04000000_5551
04:48:923 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2790 Block transfer upload 0968cd50 -> 040cc040 (512x1 0,0 bpp=4)
04:49:766 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:220 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
04:49:766 main         W[SCEIO]: HLE\sceIo.cpp:971 ERRNO_FILE_NOT_FOUND=sceIoGetstat(gamedata/if/res/if_versus.npk.zzz, 09fe67f0): FILE NOT FOUND
04:54:780 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2730 Block transfer readback 512x272 2bpp from 04044000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
04:57:117 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2730 Block transfer readback 512x272 2bpp from 04000000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
04:57:149 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:220 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
04:57:149 main         W[SCEIO]: HLE\sceIo.cpp:971 ERRNO_FILE_NOT_FOUND=sceIoGetstat(gamedata/if/pict/btl_pit009.ptm.zzz, 09fe67a0): FILE NOT FOUND
04:58:202 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2730 Block transfer readback 512x272 2bpp from 04044000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
04:59:235 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:220 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
04:59:235 main         W[SCEIO]: HLE\sceIo.cpp:971 ERRNO_FILE_NOT_FOUND=sceIoGetstat(gamedata/if/pict/btl_pit010.ptm.zzz, 09fe67a0): FILE NOT FOUND
05:00:271 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2730 Block transfer readback 512x272 2bpp from 04044000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
05:00:937 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:220 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
05:00:937 main         W[SCEIO]: HLE\sceIo.cpp:971 ERRNO_FILE_NOT_FOUND=sceIoGetstat(gamedata/if/pict/btl_pit011.ptm.zzz, 09fe67a0): FILE NOT FOUND
05:01:990 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2730 Block transfer readback 512x272 2bpp from 04000000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
05:02:656 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:220 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
05:02:656 main         W[SCEIO]: HLE\sceIo.cpp:971 ERRNO_FILE_NOT_FOUND=sceIoGetstat(gamedata/if/pict/btl_pit012.ptm.zzz, 09fe67a0): FILE NOT FOUND
05:03:709 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2730 Block transfer readback 512x272 2bpp from 04044000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
05:04:876 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:220 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
05:04:876 main         W[SCEIO]: HLE\sceIo.cpp:971 ERRNO_FILE_NOT_FOUND=sceIoGetstat(gamedata/if/pict/btl_pit013.ptm.zzz, 09fe67a0): FILE NOT FOUND
05:05:928 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2730 Block transfer readback 512x272 2bpp from 04044000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
05:10:032 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2730 Block transfer readback 512x272 2bpp from 04000000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
06:10:875 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2730 Block transfer readback 512x272 2bpp from 04044000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
06:28:426 main         W[G3D]: Common\FramebufferManagerCommon.cpp:2730 Block transfer readback 512x272 2bpp from 04044000 (x:0 y:0 stride:512) -> 09880240 (x:0 y:0 stride:512)
06:43:878 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:2 Memcpy fbo upload 041faff0 -> 041faff0 (size: 8000)
06:47:478 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:220 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
06:47:478 main         W[SCEIO]: HLE\sceIo.cpp:971 ERRNO_FILE_NOT_FOUND=sceIoGetstat(gamedata/if/evt/ef001011.efc.zzz, 09fe67a0): FILE NOT FOUND
07:07:403 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:220 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
07:07:403 main         W[SCEIO]: HLE\sceIo.cpp:971 ERRNO_FILE_NOT_FOUND=sceIoGetstat(gamedata/if/pict/fld_tut_01_0.ptm.zzz, 09fe6760): FILE NOT FOUND
07:12:759 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:220 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
07:12:759 main         W[SCEIO]: HLE\sceIo.cpp:971 ERRNO_FILE_NOT_FOUND=sceIoGetstat(gamedata/if/pict/btl_pit030.ptm.zzz, 09fe67a0): FILE NOT FOUND
07:15:347 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:220 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
07:15:347 main         W[SCEIO]: HLE\sceIo.cpp:971 ERRNO_FILE_NOT_FOUND=sceIoGetstat(gamedata/if/pict/btl_pit031.ptm.zzz, 09fe67a0): FILE NOT FOUND
07:17:800 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:220 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
07:17:800 main         W[SCEIO]: HLE\sceIo.cpp:971 ERRNO_FILE_NOT_FOUND=sceIoGetstat(gamedata/if/pict/btl_pit032.ptm.zzz, 09fe67a0): FILE NOT FOUND
07:35:658 main         W[FRAMEBUF]: Common\FramebufferManagerCommon.cpp:2 Memcpy fbo upload 041faff0 -> 041faff0 (size: 8000)
07:44:400 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:220 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
07:44:400 main         W[SCEIO]: HLE\sceIo.cpp:971 ERRNO_FILE_NOT_FOUND=sceIoGetstat(gamedata/if/pict/btl_pit040.ptm.zzz, 09fe67a0): FILE NOT FOUND
07:46:887 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:220 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
07:46:887 main         W[SCEIO]: HLE\sceIo.cpp:971 ERRNO_FILE_NOT_FOUND=sceIoGetstat(gamedata/if/pict/btl_pit041.ptm.zzz, 09fe67a0): FILE NOT FOUND
07:48:572 main         W[FILESYS]: FileSystems\MetaFileSystem.cpp:220 Path is relative, but current directory not set for thread 278. returning 8002032C(SCE_KERNEL_ERROR_NOCWD) instead.
07:48:572 main         W[SCEIO]: HLE\sceIo.cpp:971 ERRNO_FILE_NOT_FOUND=sceIoGetstat(gamedata/if/pict/btl_pit042.ptm.zzz, 09fe67a0): FILE NOT FOUND
```
