### ISSUE TITLE
4x rendering resolution on 1080p resolution

### ISSUE THREAD

**Issue by trueedcfans** [hrydgard/ppsspp#20585]
### Game or games this happens in

All games

### What area of the game

N/A

### What happens

Hi, I am using ppsspp on an android device with a 1920x1080 screen. At 4x rendering resolution the out put resolution will be 1920x1088. According to the user manual of ppsspp: 

"4x is almost exactly equal to 1080p (1920x1288 vs 1920x1280), and if you have your monitor set to that, PPSSPP will automatically cut off 4 pixels at the top and bottom of the screen to make it fit."

However my default setting will leave 1 pixel at the left and right instead of cutting off the extra pixel at the top and bottom. I also can not find any setting regarding to this. I try adding the "DisplayCrop16x9" into the ppsspp.ini file but it wont do anything. I am using 1.19.1 android version.

I understand that 1 pixel does not change too much on a 1080p screen, I just really like the pixel to pixel layout. Please let me know how can I config this thanks!

### What should happen

N/A

### Platform

Android

### Mobile device model or graphics card (GPU)

sd 865 with adreno 650 GPU

### PPSSPP version affected

1.19.1

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [x] Test in the [latest git build](https://www.ppsspp.org/devbuilds) in case it's already fixed.
- [x] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [x] Try resetting settings or older versions and include if the issue is related.
- [x] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [ ] Include logs or screenshots of issue.

**Comment by NABN00B** [comment]
This is noticeable on desktop too when capturing fullscreen PPSSPP with OBS Studio.

**Comment by trueedcfans** [comment]
I just noticed that the ppsspp mistakenly put 1920x1280 as 1080p resolution( should be 1920x1080) on the official website. Could this be the issue if the emulator wont enable "DisplayCrop16x9 = True" since the preset resolution for this may be "1920x1280"?

**Comment by hrydgard** [comment]
I've fixed the incorrect text on the website (will be pushing out an update soon).

"DisplayCrop16x9" isn't the correct spelling btw, it's "DisplayCropTo16x9" (don't forget the To) if you want to override this.

**Comment by trueedcfans** [comment]
> I've fixed the incorrect text on the website (will be pushing out an update soon).
> 
> "DisplayCrop16x9" isn't the correct spelling btw, it's "DisplayCropTo16x9" (don't forget the To) if you want to override this.

Hi thank you for the helpful info Henrik! Now I put "DisplayCropTo16x9 = True" into the ppsspp.ini file but still not working. Can you please direct me on how to properly enable the 19x9 crop feature? Also is it possible to add a toggle in setting?

**Comment by hrydgard** [comment]
Well it's on by default, ini is only for turning it off. And it's not activating for some reason then. 

Let's check the code: 

```
	if (scale == 1.0f && aspectRatioAdjust == 1.0f && offsetX == 0.5f && offsetY == 0.5f && !g_Config.bDisplayIntegerScale && g_Config.bDisplayCropTo16x9) {
		if (fabsf(frame.w / frame.h - 16.0f / 9.0f) < 0.0001f) {
			outW *= 272.0f / 270.0f;
			outH *= 272.0f / 270.0f;
		}
	}
```

So, it activates if you haven't moved the image at all in Display Layout and settings,  (scale aspect offsetx/y are all defaults) and also DisplayIntegerScale is enabled, and your display has a resolution that exactly matches a 16:9 ratio.

Now, the frame.w/frame.h measurements can be affected by things like cutouts for cameras and similar. It's calculated in the function GetScreenFrame and only cutouts (insets) can make it not directly use the screen resolution...

**Comment by trueedcfans** [comment]
> Well it's on by default, ini is only for turning it off. And it's not activating for some reason then.
> 
> Let's check the code:
> 
> ```
> 	if (scale == 1.0f && aspectRatioAdjust == 1.0f && offsetX == 0.5f && offsetY == 0.5f && !g_Config.bDisplayIntegerScale && g_Config.bDisplayCropTo16x9) {
> 		if (fabsf(frame.w / frame.h - 16.0f / 9.0f) < 0.0001f) {
> 			outW *= 272.0f / 270.0f;
> 			outH *= 272.0f / 270.0f;
> 		}
> 	}
> ```
> 
> So, it activates if you haven't moved the image at all in Display Layout and settings, (scale aspect offsetx/y are all defaults) and also DisplayIntegerScale is enabled, and your display has a resolution that exactly matches a 16:9 ratio.
> 
> Now, the frame.w/frame.h measurements can be affected by things like cutouts for cameras and similar. It's calculated in the function GetScreenFrame and only cutouts (insets) can make it not directly use the screen resolution...

I went back to default setting and toggled integer scale factor, but still can not enable auto crop. here is my current setting and please lmk if anything is wrong:

![Image](https://github.com/user-attachments/assets/55529ad0-05ef-4130-b711-31a848343ed1)
![Image](https://github.com/user-attachments/assets/a8c059a1-05c3-485f-b90f-55cd417633d0)

**Comment by hrydgard** [comment]
Are you sure it's not working as expected? If it wasn't working, i'd expect to see a small sliver of black to the right underneath the menu. This thing is not really very noticable, I made it for myself, I didn't really expect anyone to notice it existed.

**Comment by trueedcfans** [comment]
> Are you sure it's not working as expected? If it wasn't working, i'd expect to see a small sliver of black to the right underneath the menu. This thing is not really very noticable, I made it for myself, I didn't really expect anyone to notice it existed.

I am most certainly sure it's not working as expected, here is a video:

https://www.youtube.com/watch?v=Ue7sKjq-cV0&ab

**Comment by hrydgard** [comment]
Yeah, you are right. Well, I'm out of ideas.

**Comment by trueedcfans** [comment]
> Yeah, you are right. Well, I'm out of ideas.

is it possible to make this a toggle in setting?

**Comment by hrydgard** [comment]
I tested it now on Windows with a window pixel resolution of exactly 1920x1080 and it worked fine. 

BTW, it does check that integer scaling is disabled, which is probably unnecessary, I will remove that. But integer scaling is based on the screen width, and also seems to be doing exactly the right thing here.

I can't quite explain what you're seeing, it should work. Make sure to press the Reset button on the Display Layout screen so there's no other parameter throwing the check off.

**Comment by KeroroGUN50** [comment]
Hello PPSSPP Lord. Is it possible to make 'DisplayCropTo16x9' available on all displays, regardless of whether the internal resolution is set to 4x or if the display is exactly 1920x1080 ?
