### ISSUE TITLE
Zero no Kiseki and Class of Heroes BGM cut off and hangup with the updated ffmpeg (GHA phase shifting)

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#5286]
happen in a specific scene. With the old ffmpeg,this does not happen.

debug log
https://gist.github.com/daniel229/8728305

Affected games:
 * Zero no Kiseki
 * Class of Heroes (likely entire series)
 * Digimon Adventure
 * Split/Second
 * God of War: Chains of Olympus
 * Persona
 * Gungnir
 * Gods Eater Burst / God Eater Burst / God Eater
 * Ys Seven
 * LittleBigPlanet
 * Tekken 6
 * Sol Trigger
 * Final Fantasy Tactics
 * Norn9 ~Norn + Nonette~

Others reported here:
http://report.ppsspp.org/logs/kind/620

**Comment by hrydgard** [comment]
Can you try again now? GHA phase shift is now enabled.

**Comment by daniel229** [comment]
Great,all games that had GHA phase shift before now they are fixed.Issue can be closed.

**Comment by innocentius** [comment]
It looks like the newest version still hit this problem. Is it leaved not solved?

**Comment by maximumspatium** [comment]
@innocentius 
First of all, you're commenting to the already closed issue. It would be better to create a new one and say us what game triggers the problematic behaviour.

I'm ready to look for a fix but I need more pointers. The more specific you'll be, the sooner we'll able to provide a fix. In short, I'll very appreciate it if you'll able to extract problematic sound files from your game. If not, there are enough people skilled in the art to do this extraction for you.

Best regards
Maxim
