### ISSUE TITLE
Pangya Fantasy Golf crashes on some maps (License White Wiz Exemple)

### ISSUE THREAD

**Issue by rogerrr** [hrydgard/ppsspp#6057]
I enter the game play eg a license from white wiz, some matches and accept other begins to hang when it arrives at the end or when I press select and then squared to go out and it does nothing just does not work the exit button or x to continue a match that was over to go to the menu.

**Comment by hrydgard** [comment]
Still happens?

**Comment by Xaelath** [comment]
@hrydgard still happens.
sometimes its just fixed like that and then it comes and it reaches to dead end.

**Comment by rogerrr** [comment]
Yes persists even in the latest version ... thank you for your attention.

**Comment by rogerrr** [comment]
The problem has continue, i tested yesterday in actually version. Room Fantasy Golf Pangya :( .

**Comment by unknownbrackets** [comment]
Has this improved?  Some other Pangya issues have been resolved recently.

-[Unknown]

**Comment by daenerys-d** [comment]
I have crash and block out issues with Cecilia's stage 5. PPSSPP android always crash. It's my 3rd time downloading the game from different source but still the same issue. Please help.

**Comment by Saramagrean** [comment]
@daenerys-d use PPSSPP latest git build.
https://buildbot.orphis.net/ppsspp/

**Comment by unknownbrackets** [comment]
Has this improved in the latest git build?

-[Unknown]

**Comment by Saramagrean** [comment]
Since v1.9.3-511-gb2c66a304 this issue is fixed.

**Comment by unknownbrackets** [comment]
Great, so basically Pangya works well now except the IO timing method issue.

-[Unknown]
