### ISSUE TITLE
2 small errors in the BLEACH HEAT OF SOUL 6 [UCAS40258]  in the version 0.9.9 and BUILD

### ISSUE THREAD

**Issue by kirous** [hrydgard/ppsspp#6627]
- Do not load the intro video again when it is in the PRESS START MENU BUTTON and the game crashes.
- The CONSOLE LOG shoots me this error:

40:51:183 Main         E[FONT]: HLE\sceFont.cpp:626 Font exists but is closed, which was not allowed in this call.
40:51:183 Main         E[FONT]: HLE\sceFont.cpp:908 sceFontClose(8e06f1c) - font not open?
40:51:183 Main         E[FONT]: HLE\sceFont.cpp:626 Font exists but is closed, which was not allowed in this call.
40:51:183 Main         E[FONT]: HLE\sceFont.cpp:908 sceFontClose(8e06f68) - font not open?
- This red, for this reason it will not load the video again or be anything else.
- Another mistake but not as severe, is always loading the game, I vizualiza this:

![bleachsave](https://cloud.githubusercontent.com/assets/5083411/3696510/ef087cbc-138f-11e4-8df6-470595b3a846.png)
- You see, the image is not vizualiza when saving the game, but when you go to save it if the image is displayed.
- The game is OK. Are only these two details.

**Comment by unknownbrackets** [comment]
The save thing should be fixed now.  Does the crash still happen in the latest PPSSPP git build?

-[Unknown]

**Comment by sum2012** [comment]
v1.7.5-553-gc77af182a  crash before menu

debug log: https://drive.google.com/file/d/1H_oKJ7sdy3LGG1XAvn_cJ7qWU-ZHB6on/view?usp=sharing

crash trace

 	atio6axx.dll!00000000696c4e02()	Unknown
 	atio6axx.dll!0000000069693da5()	Unknown
 	atio6axx.dll!00000000692283e4()	Unknown
 	atio6axx.dll!0000000069626a03()	Unknown
>	PPSSPPDebug64.exe!GLQueueRunner::PerformBlit(const GLRStep & step) Line 633	C++
 	PPSSPPDebug64.exe!GLQueueRunner::RunSteps(const std::vector<GLRStep *,std::allocator<GLRStep *> > & steps, bool skipGLCalls) Line 588	C++
 	PPSSPPDebug64.exe!GLRenderManager::Run(int frame) Line 527	C++
 	PPSSPPDebug64.exe!GLRenderManager::ThreadFrame() Line 201	C++
 	PPSSPPDebug64.exe!WindowsGLContext::ThreadFrame() Line 466	C++
 	PPSSPPDebug64.exe!MainThreadFunc() Line 243	C++
 	[External Code]	
 	PPSSPPDebug64.exe!invoke_thread_procedure(unsigned int(*)(void *) procedure, void * const context) Line 92	C++
 	PPSSPPDebug64.exe!thread_start<unsigned int (__cdecl*)(void * __ptr64)>(void * const parameter) Line 115	C++
 	[External Code]	

![2](https://user-images.githubusercontent.com/2177532/54083726-b55ae600-4362-11e9-8649-530892c6d29b.png)

**Comment by hrydgard** [comment]
Hm, could maybe be out of bounds of the src or the destination of the blit, possibly? We have some clipping code in the Vulkan path that we maybe should use on all backends.

**Comment by sum2012** [comment]
It only crash on Opengl.
DX9 and DX 11 not crash that place.

**Comment by sum2012** [comment]
git bisect result:
https://github.com/hrydgard/ppsspp/pull/11676/commits/2dc3912d0a9f0366e4ac0663a7ce77035b4b64d5 in  #11676

**Comment by unknownbrackets** [comment]
Hmm, aspectMask there is GL_STENCIL_BUFFER_BIT.  I wonder where we're trying to blit depth without z - that's definitely a bug.

-[Unknown]

**Comment by unknownbrackets** [comment]
Sorry, #11873 should fix that now.

-[Unknown]

**Comment by hrydgard** [comment]
Oh good catch! That goes in 1.8.0.

**Comment by sum2012** [comment]
Thanks @unknownbrackets  @hrydgard 
The video still crash when I enable fast memory.

58:49:061 Main         W[MEMMAP]: MemmapFunctions.cpp:92 ReadFromHardware: Invalid address 00000000
58:49:061 Main         W[MEMMAP]: MemmapFunctions.cpp:92 ReadFromHardware: Invalid address 00000004
58:49:061 Main         W[MEMMAP]: MemmapFunctions.cpp:128 WriteToHardware: Invalid address 0000000c
58:49:061 Main         W[MEMMAP]: MemmapFunctions.cpp:92 ReadFromHardware: Invalid address 00000000
58:49:061 Main         W[MEMMAP]: MemmapFunctions.cpp:92 ReadFromHardware: Invalid address 0000000c
58:49:061 Main         W[MEMMAP]: MemmapFunctions.cpp:92 ReadFromHardware: Invalid address 00000008
58:49:061 Main         W[MEMMAP]: MemmapFunctions.cpp:92 ReadFromHardware: Invalid address 00000008
58:49:061 Main         W[MEMMAP]: MemmapFunctions.cpp:92 ReadFromHardware: Invalid address 00000000
58:49:061 Main         W[MEMMAP]: MemmapFunctions.cpp:128 WriteToHardware: Invalid address 00000004
58:49:061 Main         W[MEMMAP]: MemmapFunctions.cpp:128 WriteToHardware: Invalid address 00000008
58:49:061 Main         W[MEMMAP]: MemmapFunctions.cpp:128 WriteToHardware: Invalid address 00000000
58:49:061 Main         W[MEMMAP]: MemmapFunctions.cpp:92 ReadFromHardware: Invalid address 0000000c
58:49:061 Main         W[MEMMAP]: MemmapFunctions.cpp:92 ReadFromHardware: Invalid address 00000008
58:49:061 Main         W[MEMMAP]: MemmapFunctions.cpp:92 ReadFromHardware: Invalid address 00000008
58:49:061 Main         W[MEMMAP]: MemmapFunctions.cpp:92 ReadFromHardware: Invalid address 00000000
58:49:061 Main         W[MEMMAP]: MemmapFunctions.cpp:128 WriteToHardware: Invalid address 00000004
58:49:061 Main         W[MEMMAP]: MemmapFunctions.cpp:128 WriteToHardware: Invalid address 00000000
58:49:061 Main         W[MEMMAP]: MemmapFunctions.cpp:128 WriteToHardware: Invalid address 00000008

full log: https://drive.google.com/file/d/1tRPbyxC-SrJf9X-3q1Sj7MolLsy_gGFO/view?usp=sharing

I try to hack to allow the close font ,but crash in the other place.

**Comment by unknownbrackets** [comment]
Hm.  Those errors are between `HLE\sceKernelThread.cpp:3195 Executing mipscall 101` and `HLE\sceKernelThread.cpp:3252 __KernelReturnFromMipsCall(), returned 00000000`.

Basically, we're calling freeFuncAddr from `sceFontDoneLib`, but there's a double free.  I bet it doesn't call the callback on a double free, and that might be why it crashes.

Does it help to make the below change?

```c++
		// TODO: The return value of this is leaking.
		__KernelDirectMipsCall(params_.freeFuncAddr, 0, args, 2, false);
```

To:

```c++
		if (handle_) {
			// TODO: The return value of this is leaking.
			__KernelDirectMipsCall(params_.freeFuncAddr, 0, args, 2, false);
		}
```

-[Unknown]

**Comment by hrydgard** [comment]
That change is almost certainly good - calling a callback a second time on a double-free can't be right.

**Comment by sum2012** [comment]
Well done @unknownbrackets  @hrydgard 
Those errors are gone when apply the change.
Can happy to use fast memory.
Just a log error message: 
27:54:009 Main         I[SCEIO]: HLE\sceIo.cpp:1031 stderr: font_error:I, 08c70000

full log: https://gist.github.com/sum2012/fbf6354c2c965e211f9685eb070b5725

**Comment by hrydgard** [comment]
Good. I don't think that error output is much to worry about.

**Comment by sum2012** [comment]
Now no error on this game.
Can close this issue.
Closing
