### ISSUE TITLE
FlatOut Head On: BGM skips after few seconds (Atrac3+)

### ISSUE THREAD

**Issue by viti95** [hrydgard/ppsspp#6663]
The BGM jumps to the next song after few seconds, seems to be a not implemented function in ffmpeg (channel unit expansion).

Edit: i'm using PPSSPP v0.9.9-34-gb7ac539

![2014-07-31 22_56_17-ppsspp debug console](https://cloud.githubusercontent.com/assets/8323882/3771640/29888668-18f7-11e4-8fdb-0ca495cd6ed7.png)

**Comment by Pulfer** [comment]
Still happens with PPSSPP 1.0.

**Comment by Pulfer** [comment]
Still happens with PPSSPP 1.0.1.

**Comment by unknownbrackets** [comment]
Would be interesting to know if #8105 helps this.  If it doesn't, I suspect it could be the same issue as #3650.

-[Unknown]

**Comment by hrydgard** [comment]
Doesn't help, the game still tries to decode bad data and skips to the next track.

**Comment by Pulfer** [comment]
Still happens with PPSSPP 1.2.1.

**Comment by benderscruffy** [comment]
using v1.3-697-gdfae4b6 	
still happens
here is a JPCSP trace log of all the SceAtrac functions
rename txt to zip
[jpcsptracelog.txt](https://github.com/hrydgard/ppsspp/files/789377/jpcsptracelog.txt)

**Comment by suelo50** [comment]
ppsspp 1.4 same error

**Comment by metalmike666** [comment]
Yuppers !!! I'am having the same problem with the ppsspp gold the audio tracks for the game Flatout head on keeps skipping

**Comment by marosis** [comment]
what if we search for the music startup settings in the game files. after understanding, we would create special settings for this game only. setting could also be triggered by identifying ULES00968 (EUR) I dont know code for USA

**Comment by hrydgard** [comment]
Problem seems to be that the game tries to decode garbage data as audio because streaming isn't working correctly, there's nothing to easily patch.

For now, the only workaround might be to turn down the music to 0 in the game and play something else in the background.

**Comment by benderscruffy** [comment]
v1.5.4-933-g386c9d4fc
still present

**Comment by marosis** [comment]
Is somehow possible fix this?

**Comment by ppmeis** [comment]
A bit old issue. But tested on latest Windows build...error persist on Flatout HeadOn:

![image](https://user-images.githubusercontent.com/4381277/45978215-ff1d7180-c04b-11e8-9725-0f5da1c8d6fc.png)
![image](https://user-images.githubusercontent.com/4381277/45978216-02b0f880-c04c-11e8-951e-3369d7f9e830.png)

**Comment by fatglist** [comment]
Last Version is 1.8.0! Problem not fixed =(
![image](https://user-images.githubusercontent.com/48914070/54919892-f7fbf100-4f12-11e9-9cf9-9533177b931f.png)

**Comment by Pulfer** [comment]
Still presents with 1.9.2.

**Comment by Abbanon** [comment]
Can confirm, it's also present in `1.9.3-251-ga9302c49f`.

**Comment by Panderner** [comment]
Tell me what is a unsupported feature in ATRAC Audio for this game? Why this feature unsupported in ffmpeg?

**Comment by hrydgard** [comment]
I think it's more likely that something is wrong with audio buffering and it's reading garbage data as ATRAC. But hard to be sure...

**Comment by crazyrexz** [comment]
it still present on 1.10.0?

**Comment by Panderner** [comment]
> it still present on 1.10.0?

@crazyrexz yes still present in 1.10

**Comment by sum2012** [comment]
still present in v1.10.3-1330-g73da378ef  
log:
https://gist.github.com/sum2012/6b2d14acbf02c87085adcd0a5d252ebd

**Comment by mamcocob64** [comment]
The issue has persisted since 2014. Why the hell hasn't it been fixed yet? You'd think that the issue would have been resolved by now. I'm no programing genius but there is no reason for the issue to be present for 6 fucking years. Are the developers ignoring this or are they struggling to fix it?

**Comment by meowthed** [comment]
still present as of v1.13.1, should be marked as future prio?

**Comment by sum2012** [comment]
@meowthed Done,I try again this game (at least hack)

**Comment by marosis** [comment]
Could be possible to make some further investigation or is this more about game itself, or psp firmware thingy? (What about disassemble code of the game?)

**Comment by marosis** [comment]
But that's really mad idea

**Comment by sum2012** [comment]
@marosis PPSSPP is HLE emulator,don't need disassemble,
The issue is Atrac sound.
Try change some code in 
https://github.com/hrydgard/ppsspp/blob/master/Core/HLE/sceAtrac.cpp

**Comment by ppmeis** [comment]
Tested in latest build. Same issues.

**Comment by NightWolf2014** [comment]
> Could be possible to make some further investigation or is this more about game itself, or psp firmware thingy? (What about disassemble code of the game?)

That its a problem from the emulator, the PPSSPP can't load the data of the game soundtrack correctly. This bug is bothering anyone who has been playing since 2014, no one can find a solution, I never knew if it is possible to fix it or not and to make matters worse the game does not have a customizable soundtrack like in EA and Gran Turismo 2009 games, which would help a lot to avoid this problem .

**Comment by Grimmjow91** [comment]
I am also having this issue. Bummer that there doesn't seem to be a fix for it.

**Comment by sum2012** [comment]
Update log to v1.14.4-253-g03f64a021-windows-amd64
https://gist.github.com/sum2012/99b885bd4bc36927c98ab990692d727a

Hope someone can code to dump the ppsspp's atrac sound stream back to file to debug the issue

**Comment by Goodfeat** [comment]
September 2023, the problem with the music is still present. I play on Recalbox.
I hope this will be fixed this year?

**Comment by jussimir** [comment]
This is one of the best psp games, I’m still hoping someone is able to fix this issue once and for all

**Comment by jussimir** [comment]
We are waiting for some blessed developer to come from the heavens to solve
this problem for all those passionate about this game...

Em sáb., 2 de dez. de 2023 às 00:25, Akoi89 ***@***.***>
escreveu:

**Comment by thomashastings** [comment]
Theoretically, what would be needed to fix this issue? Seeing the exceptional compatibility of PPSSPP, I'd lean towards making a modded version of the game with the needed changes to the soundtrack.

So far, I managed to
- unpack the game using [UMDGen](https://umdgen.en.lo4d.com/windows)
- convert the soundtrack located in `[iso root]/PSP_GAME/USRDIR/DATA/SONGS1` to wav files,
- convert them back to AT3 with varying bitrates using [ATRACTool](https://github.com/XyLe-GBP/ATRACTool-Reloaded/releases),
- make a modded ISO using these files again with UMDGen,
- check test the outcome in PPSSPP v1.16.6 (from flathub), and
- see that the issue wasn't fixed

Most of the process can be automated quite nicely though.

Of course, this was a really naive first try, but it proves that the files of the soundtrack can be altered relatively easily. Therefore, if the _unsupported feature_ of these files was found, it could hopefully be removed as well. Are there any pointers in this regard?

**Comment by NightWolf2014** [comment]
> Theoretically, this problem can be solved with a modified emulator that could play tracks from a special folder with music.
> 
> Perhaps you need a patch that could recognize music tags from the game and connect the desired melody from the folder. This solution is available on some Sega Megadrive emulators, when the soundtrack was played separately from the game in high quality
> 
> It seems that this would be a normal solution for this game

I agree with that point, the developers doens't send any message to explain if this bug are possible to fix or not, so that can be the only way to hear the game songs without problems.

**Comment by jussimir** [comment]
Hey everyone! 🌟 I haven't had the chance to test it extensively yet, but it seems to be working, that is a first in ten years I've been following this bug hoping for a fix!! 🚀

**Comment by viti95** [comment]
Wow,  I was preparing a party for the 10 year anniversary 😂. I'll try this as soon as possible.

**Comment by viti95** [comment]
I've done some testing, now songs don't jumps after a few seconds, but there is a little bit of skipping after few seconds. Then music plays perfectly fine. Maybe there is metadata hidden in the songs and needs to be skipped?

**Comment by sum2012** [comment]
@viti95  I just ignore the bad decode data , so it is hack. Hope some day really fix it.

**Comment by Goodfeat** [comment]
this is really cool, I'm very happy with this decision, if only because the music is now playing.

Although it is worth noting the fact that failures actually occur due to metadata that the emulator cannot process correctly.
I noticed that the music starts to break up precisely at the moment when the title of the track and the artist disappear. Moreover, the stuttering of the music lasts exactly as long as the sign with the name of the artist hangs.

The sign with the name of the track hangs for about 8-9 seconds, then the sign disappears and the stuttering lasts the same 8-9 seconds
There is probably a time shift in the music, since the music is not played to the end

and nevertheless I am happy with the current decision )

**Comment by hrydgard** [comment]
Not sure what decision you are referring to, as I haven't committed to merging the change. However, it's interesting that the track plays nicely afterwards. But, the experiments of thomashastings would seem to disprove the metadata theory, since replacing the files didn't make a difference...

**Comment by Goodfeat** [comment]
> Not sure what decision you are referring to

meant the decision @sum2012 , his decision was
is that the error that occurs during the process is processed by the line

```
 packet_->size = 0;
 return ATDECODE_BADFRAME;
```

instead of 
` return ATDECODE_FAILED;`

I think you can use this solution instead, just move the “fix” value somewhere in the audio settings in menu

![image](https://github.com/hrydgard/ppsspp/assets/44455128/72f45e89-f8fa-4e53-9c98-555d65a788a0)

**Comment by sum2012** [comment]
i prepare add the hack code ,apply  in compare.ini

在 2024年2月15日週四 下午12:07，Vladimir Sokolov ***@***.***> 寫道：

**Comment by Goodfeat** [comment]
![image](https://github.com/hrydgard/ppsspp/assets/44455128/6198c174-3a80-47f6-88d0-4ce80805bc72)
Using this code, I was able to slightly reduce throttling in music by about half. If you increase the dd value, there is a lag in the music or it stops playing altogether.

I conclude that you need to somehow skip part of the track by jumping to a certain point on the track,

**Comment by thomashastings** [comment]
So good to see these changes! I'll test them as soon as I get to a windows box.
Regarding the metadata: it seems that the metadata of the files not stored inside the files themselves, as the original titles and artists appeared even if the ost files were exchanged for something completely different.

**Comment by sum2012** [comment]
@Goodfeat if you have time , you can see jpcsp emulator source https://github.com/jpcsp/jpcsp/blob/master/src/jpcsp/HLE/modules/sceAtrac3plus.java 
It decode the Atrac3 correctly in this game.  (Although jpcsp emulator have problem in K-ON game)

**Comment by Goodfeat** [comment]
@sum2012 I'm not good at Java. Besides, I just saw a slight shift in this topic and tried to help. yesterday, It was just surprisingly easy enough for me to launch this project in visual studio.

Since the music interruption issue was resolved, I decided to try fixing the audio lag. And it seemed to me that the problem was quite superficial and I just needed to jump to the desired section of the track.

My theory was that the game first buffers the metadata part of the track, but literally after a few seconds the game does the same thing. But instead of playing music, for some reason it reads the metadata again into the at3 stream. Because of this, there is a lag in the music.

**Comment by Goodfeat** [comment]
I made a new build of the emulator. Now the lag in music is only 384ms

And I changed the code a little so that it was possible to make an audio patch.

I understand that this solution may be incorrect, but currently it is fully working.


[PPSSPPWindows64_FixFlatout_V1.1_.zip](https://github.com/hrydgard/ppsspp/files/14316957/PPSSPPWindows64_FixFlatout_V1.1_.zip)

@hrydgard  Can this solution be added to the official build of the emulator?
```
  /* This is for setting up the emulator */
  int errors;// count errors
  long jmp = 620048; // if it fails, jump to the sample  (lag 384ms for flat out)
  bool fix = true; // fix flatout
```
```
	if (res == ATDECODE_GOTFRAME) {
		// We only want one frame per call, let's continue the next time.
		break;
        }
	if ( res == ATDECODE_BADFRAME) {
	       if (fix == true) { // fix audio
			if (atrac->currentSample_ < jmp) { 
				atrac->currentSample_ = jmp;
		    }
		    else {
				atrac->currentSample_ += 2047;
			}
		}
		// We only want one frame per call, let's continue the next time.
	}	
```

[sceAtrac_Fix_audio_FlatOut.zip](https://github.com/hrydgard/ppsspp/files/14316975/sceAtrac_Fix_audio_FlatOut.zip)

**Comment by sum2012** [comment]
At least you need to make compat similar to

https://github.com/hrydgard/ppsspp/blob/master/Core/HLE/sceAtrac.cpp#L1199

在 2024年2月17日週六 上午8:15，Vladimir Sokolov ***@***.***> 寫道：

**Comment by VadloCarlo** [comment]
can smb add this fix to the android version of ppsspp? thanks in advance

**Comment by jussimir** [comment]
Firstly, thank you all so much for working to resolve this issue that has persisted for over 10 years in PPSSPP 😊. Now with the official release of PPSSPP on iPhone, what would be the next steps to get Flatout working properly on this version of PPSSPP? I'm really looking forward to playing Flatout on my device 😄, but anyway, a huge thanks to everyone, especially to Hrydgard, goodfeat, and sum2012 for their invaluable recent contributions to this project 😁

**Comment by hrydgard** [comment]
I'm very well aware that this isn't good. I was in the middle of reworking the Atrac decoder in order to both understand it better myself and making it more accurate (hopefully fixing this) when the iOS restrictions were removed, and since then I've been working on that mainly. I will get back to this in the near future.

**Comment by sum2012** [comment]
I need to go to hotel 2 months for furnish so that  I cannot use computer.

**Comment by NightWolf2014** [comment]
Any news about the bug fiz? Man, i still want to play the game with the soundtrack playing correctly.

**Comment by NightWolf2014** [comment]
> I need to go to hotel 2 months for furnish so that I cannot use computer.

Any news?

**Comment by sum2012** [comment]
do not have idea

在 2024年9月9日週一 上午5:27，NightWolf2014 ***@***.***> 寫道：

**Comment by rumly111** [comment]
I thought this problem was solved. I just compiled v1.8.1 and the music track still skips to next one after few seconds. In the console I see some error messages:

`52:03:700 FMOD Streame E[ME]: at3_standalone/compat.cpp:19 Atrac3/3+: Invalid start bit!
52:03:934 FMOD FSOUND_ E[ME]: HLE/sceAtrac.cpp:688 80630021=sceAtracSetLoopNum(0, 0): no loop information to write to!`

OS: Linux
PPSSPP: v1.8.1

**Comment by hrydgard** [comment]
It is indeed not solved. I plan to make another push to get my Atrac3+ playback rework working in the near future. The new debugger stuff I'm working on is partly to be able to better visualize what's going on internally in Atrac3+ playback...

**Comment by rumly111** [comment]
> It is indeed not solved. I plan to make another push to get my Atrac3+ playback rework working in the near future. The new debugger stuff I'm working on is partly to be able to better visualize what's going on internally in Atrac3+ playback...

Thanks!

**Comment by jussimir** [comment]
Thank you for your owk on this Hrydgard!

> It is indeed not solved. I plan to make another push to get my Atrac3+ playback rework working in the near future. The new debugger stuff I'm working on is partly to be able to better visualize what's going on internally in Atrac3+ playback...

**Comment by IldarKhanifatullin** [comment]
Retro consoles are very popular now. I'm playing Flat Out Head On on Anbernic on Linux. My brother also loves this game, and I want to give him the same console with this game. I want to solve this problem so that he gets all the emotions from this wonderful game. Please help, can someone attach a fixed ppsspp emulator for Linux here?

**Comment by sum2012** [comment]
The Atrac code is changed, I cannot make the hack now

**Comment by GW-Der** [comment]
Happy new year 2025 guys, aaand the bug is still here with us too, nothing changed.

**Comment by NightWolf2014** [comment]
> After all these years, I can confirm that the work-in-progress sceAtrac rewrite [#20098](https://github.com/hrydgard/ppsspp/pull/20098) will finally fix this.

Finally this problem would end.

**Comment by Goodfeat** [comment]
And this is great news, I'm glad that this problem has finally been overcome.

**Comment by hrydgard** [comment]
Fixed since #20138 (though really fixed by #20098).

**Comment by viti95** [comment]
So glad this is finally solved! 10+ years of waiting for this, I even had time to build my own Doom port in the meantime! 😂

**Comment by hrydgard** [comment]
@Iarley-01 Right now it's looking like sometime in May. I aim to get it out before summer.

In the meantime, you can get development builds from https://www.ppsspp.org/devbuilds/ , if you're willing to live on the unstable edge.
