### ISSUE TITLE
(old Nvidia iGPU) Simulate block transfer seems to be not working...

### ISSUE THREAD

**Issue by Blutgang** [hrydgard/ppsspp#6964]
for me (ancient IGPU) with the OpenGL backend on one particular game: Digimon Adventure. (no character outline effect, no menu transparency and no save dialog transparency) Simulate block transfer with the Direct3D9 backend does work on Digimon Adventure.

Edit: Most likely a driver bug...

OpenGL:
![npjh50686_00000](https://cloud.githubusercontent.com/assets/4369039/4485449/b2a5e580-49cb-11e4-9d35-64f438e79c25.png)

Direct X:
![directx](https://cloud.githubusercontent.com/assets/4369039/4485450/b8577c14-49cb-11e4-8da3-95a14d2e4179.png)

Otherwise, "simulate block transfer" does work on other games such as Burnout Legends and Digimon Digivice Ver. Portable on OpenGL. 

Device Info:
![menu_00000](https://cloud.githubusercontent.com/assets/4369039/4485452/c15f4d32-49cb-11e4-9ec7-8cff84bdfd82.png)

How do I debug this particular problem?

OpenGL (log)
````
42:42:360 EmuThread.cpp:169 I[BOOT]: Done.
42:48:998 System.cpp:326 I[BOOT]: PPSSPP v0.9.9.1-558-gfeada0e Windows 32 bit
42:49:008 MemMap.cpp:278 I[MM]: Found valid memory base at 0A400000 after 38 tries.
42:49:008 MemMap.cpp:339 I[MM]: Memory system initialized. RAM at 0A620000 (mirror at 0 @ 12400000, uncached @ 12400000)
42:49:019 PSPLoaders.cpp:159 I[LOAD]: NPJH50686 : デジモンアドベンチャー
42:49:020 PSPLoaders.cpp:200 I[LOAD]: Loading disc0:/PSP_GAME/SYSDIR/EBOOT.BIN...
42:49:020 HLE\sceKernelMemory.cpp:431 I[KERNEL]: Kernel and user memory pools initialized
42:49:097 HLE\sceKernel.cpp:151 I[KERNEL]: Kernel initialized.
42:49:185 Util\BlockAllocator.cpp:381 I[HLE]: -----------
42:49:185 Util\BlockAllocator.cpp:385 I[HLE]: Block: 08800000 - 08804000 size 00004000 taken=1 tag=usersystemlib
42:49:185 Util\BlockAllocator.cpp:385 I[HLE]: Block: 08804000 - 08a87600 size 00283600 taken=1 tag=ELF/Digimon
42:49:185 Util\BlockAllocator.cpp:385 I[HLE]: Block: 08a87600 - 0c000000 size 03578a00 taken=0 tag=(untitled)
42:49:185 Util\BlockAllocator.cpp:387 I[HLE]: -----------
42:49:187 HLE\sceKernelModule.cpp:1028 I[LOAD]: Module Digimon: 00000000 089776e0 089776f8
42:49:248 HLE\ReplaceTables.cpp:824 I[HLE]: Replaced memcpy at 088b7edc with hash 0ffa5db8396d4274
42:49:248 HLE\ReplaceTables.cpp:824 I[HLE]: Replaced memset at 088b7f1c with hash eabb9c1b4f83d2b4
42:49:248 HLE\ReplaceTables.cpp:824 I[HLE]: Replaced memcpy at 0895b3b8 with hash 0266f96d740c7e03
42:49:248 HLE\sceKernelModule.cpp:1229 I[LOAD]: Exporting ent 0 named Digimon, 2 funcs, 4 vars, resident 08977a54
42:49:249 HLE\sceKernelModule.cpp:1557 I[LOAD]: Module entry: 088b63b8
42:49:367 root         N[BOOT]: EmuScreen.cpp:129 Loading C:/Documents and Settings/Roxas/Desktop/DWRD/NPJH-50686.iso...
42:49:376 root         I[KERNEL]: HLE\sceKernelThread.cpp:2178 276=sceKernelCreateThread(name=user_main, entry=088b64d8, prio=20, stacksize=262144)
42:49:376 root         I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=276, argSize=33, argPtr=0bfffed0)
42:49:377 root         I[KERNEL]: HLE\sceKernelThread.cpp:2318 __KernelReturnFromThread: 0
42:49:398 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 284=sceKernelCreateThread(name=CRI FS File Access 0, entry=089127b8, prio=20, stacksize=4096)
42:49:399 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=284, argSize=4, argPtr=0bfff3c0)
42:49:399 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 289=sceKernelCreateThread(name=CRI FS Memory File System, entry=089127b8, prio=20, stacksize=4096)
42:49:399 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=289, argSize=4, argPtr=0bfff3c0)
42:49:399 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 292=sceKernelCreateThread(name=CRI FS Data Decompression 0, entry=089127b8, prio=20, stacksize=4096)
42:49:399 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=292, argSize=4, argPtr=0bfff410)
42:49:401 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 305=sceKernelCreateThread(name=CRI Server Manager, entry=089127b8, prio=20, stacksize=8192)
42:49:401 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=305, argSize=4, argPtr=0bfff460)
42:49:432 CRI FS File  E[FileSys]: FileSystems\DirectoryFileSystem.cpp:501 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
42:49:432 CRI FS File  E[IO]: HLE\sceIo.cpp:1200 ERROR_ERRNO_FILE_NOT_FOUND=sceIoOpen(ms0:/psp/SAVEDATA/NPJH50686INSTALL/FILEDATA.DNS, 40004001, 000021a4) - file not found
42:49:434 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 310=sceKernelCreateThread(name=LoaderThread, entry=08805858, prio=6f, stacksize=16384)
42:49:435 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=310, argSize=4, argPtr=08a2f374)
42:49:439 user_main    I[UTIL]: HLE\sceUtility.cpp:224 sceUtilityLoadModule(768)
42:49:460 user_main    I[UTIL]: HLE\sceUtility.cpp:224 sceUtilityLoadModule(770)
42:49:477 user_main    I[UTIL]: HLE\sceUtility.cpp:224 sceUtilityLoadModule(771)
42:49:513 user_main    I[ME]: HLE\sceMpeg.cpp:412 sceMpegInit()
42:49:571 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:329 Creating FBO for 00044000 : 480 x 272 x 1
42:49:572 user_main    W[G3D]: Common\FramebufferCommon.cpp:520 Memcpy fbo upload 04444000 -> 04044000
42:49:583 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 14 fs 15
42:49:636 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:329 Creating FBO for 00000000 : 480 x 272 x 1
42:49:652 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 088aefb8 to block at 088b7edc
42:49:652 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 088aefbc to block at 088b7edc
42:49:662 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 088aeef0 to block at 088b7edc
42:49:662 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 088aeef4 to block at 088b7edc
42:49:964 user_main    I[UTIL]: HLE\sceUtility.cpp:224 sceUtilityLoadModule(769)
42:49:995 user_main    I[SCESAS]: HLE\sceSas.cpp:106 sceSasInit(08a86780, 256, 32, 0, 44100)
42:49:995 user_main    I[SCESAS]: HLE\sceSas.cpp:506 sceSasSetGrain(08a86780, 256)
42:49:996 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 314=sceKernelCreateThread(name=CRI Atom Sound Output, entry=089127b8, prio=20, stacksize=2048)
42:49:996 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=314, argSize=4, argPtr=0bfff320)
42:50:008 user_main    E[UTIL]: HLE\sceUtility.cpp:221 sceUtilityLoadModule(768): already loaded
42:50:008 user_main    E[UTIL]: HLE\sceUtility.cpp:221 sceUtilityLoadModule(770): already loaded
42:50:008 user_main    I[ME]: HLE\sceAtrac.cpp:1497 sceAtracReinit(0, 3)
42:50:013 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0891da70 to block at 088b7f1c
42:50:039 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0891b30c to block at 088b7f1c
42:50:054 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0892c764 to block at 088b7f1c
42:50:056 user_main    E[UTIL]: HLE\sceUtility.cpp:221 sceUtilityLoadModule(768): already loaded
42:50:056 user_main    E[UTIL]: HLE\sceUtility.cpp:221 sceUtilityLoadModule(770): already loaded
42:50:056 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 322=sceKernelCreateThread(name=CRI Atom Atrac Decode, entry=089127b8, prio=20, stacksize=2048)
42:50:057 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=322, argSize=4, argPtr=0bfff390)
42:50:065 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 08879ac0 to block at 088b7f1c
42:50:074 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 327=sceKernelCreateThread(name=LoaderThread, entry=08879a04, prio=1e, stacksize=16384)
42:50:075 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=327, argSize=4, argPtr=08a2f9f0)
42:50:087 user_main    W[G3D]: Common\FramebufferCommon.cpp:679 Block transfer download 04044000 -> 041bffc0
42:50:156 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 17 fs 18
42:50:161 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 20 fs 21
42:50:165 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 23 fs 24
42:50:169 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 23 fs 26
42:51:348 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 08957ce8 to block at 088b7edc
42:51:348 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 08957db0 to block at 088b7f1c
42:51:348 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 08958c3c to block at 0895b3b8
42:51:349 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 08954218 to block at 088b7f1c
42:51:350 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 089545b8 to block at 088b7edc
42:51:350 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 089545ec to block at 088b7edc
42:51:350 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 089545ac to block at 088b7edc
42:51:351 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 08955f80 to block at 088b7edc
42:51:352 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0895ccf8 to block at 088b7edc
42:53:145 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0889ca88 to block at 088b7f1c
42:53:146 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0889c528 to block at 088b7edc
42:53:146 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0889ce5c to block at 088b7f1c
42:53:146 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0889ce5c to block at 088b7f1c
42:53:146 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0889ce5c to block at 088b7f1c
42:53:146 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 089362c0 to block at 088b7f1c
42:53:181 user_main    I[UTIL]: Dialog\PSPSaveDialog.cpp:85 sceUtilitySavedataInitStart(08a2fd60) - SIZES (8)
42:53:181 user_main    I[UTIL]: Dialog\PSPSaveDialog.cpp:86 sceUtilitySavedataInitStart(08a2fd60) : Game key (hex): 11213203040703050708020A0C12013A
43:13:631 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 08880a9c to block at 088b7f1c
43:13:631 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 08880ad8 to block at 088b7f1c
43:13:664 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 20 fs 28
43:14:031 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0889c750 to block at 088b7f1c
43:14:031 user_main    I[UTIL]: Dialog\PSPSaveDialog.cpp:85 sceUtilitySavedataInitStart(08a2fd60) - LIST (11)
43:14:031 user_main    I[UTIL]: Dialog\PSPSaveDialog.cpp:86 sceUtilitySavedataInitStart(08a2fd60) : Game key (hex): 11213203040703050708020A0C12013A
43:14:468 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 23 fs 30
43:14:495 CRI Server M I[ME]: HLE\sceAtrac.cpp:549 0=sceAtracGetAtracID(4096)
43:14:495 CRI Server M I[ME]: HLE\sceAtrac.cpp:1821 sceAtracLowLevelInitDecoder(0, 0bfbc8b0)
43:14:495 CRI Server M I[ME]: HLE\sceAtrac.cpp:1830 Channels: 2 outputChannels: 2 bytesperFrame: 2e8
43:14:495 CRI Server M W[ME]: HLE\sceAtrac.cpp:1861 This is an atrac3+ stereo audio (low level)
43:17:741 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 088ba0a8 to block at 088b7edc
43:17:741 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 088b8dc0 to block at 088b7edc
43:17:742 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0889cd48 to block at 088b7f1c
43:17:934 user_main    I[UTIL]: Dialog\PSPSaveDialog.cpp:85 sceUtilitySavedataInitStart(08a2fd60) - LISTLOAD (4)
43:17:934 user_main    I[UTIL]: Dialog\PSPSaveDialog.cpp:86 sceUtilitySavedataInitStart(08a2fd60) : Game key (hex): 11213203040703050708020A0C12013A
43:18:084 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 14 fs 21
43:18:086 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 33 fs 30
43:19:842 idle0        I[UTIL]: Dialog\SavedataParam.cpp:580 Loading file with size 130976 in ms0:/PSP/SAVEDATA/NPJH50686DATA27/SECURE.BIN
43:21:268 CRI Server M I[ME]: HLE\sceAtrac.cpp:1084 sceAtracReleaseAtracID(0)
43:21:501 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0894ac8c to block at 088b7edc
43:21:501 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0894a5b4 to block at 088b7edc
43:21:501 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0894a5b4 to block at 088b7edc
43:21:501 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0894a5b4 to block at 088b7edc
43:21:501 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0894a5b4 to block at 088b7edc
43:21:502 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 08949568 to block at 088b7edc
43:21:529 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 35 fs 36
43:21:533 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 38 fs 39
43:21:536 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 38 fs 41
43:21:539 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 38 fs 43
43:21:542 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 38 fs 45
43:21:548 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 47 fs 45
43:21:560 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 49 fs 15
43:22:669 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0894ef84 to block at 088b7f1c
43:23:465 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 51 fs 18
43:23:468 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 51 fs 36
43:23:472 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 54 fs 41
43:23:531 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 56 fs 57
43:23:535 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 59 fs 57
43:23:540 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 59 fs 61
43:23:545 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 59 fs 63
43:23:555 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 65 fs 66
43:23:564 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 68 fs 69
43:23:567 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 68 fs 71
43:23:576 user_main    W[JIT]: x86\Jit.cpp:335 Uneaten prefix at end of block: 0894ec9c
43:23:643 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 56 fs 61
43:23:709 CRI Server M I[ME]: HLE\sceAtrac.cpp:549 0=sceAtracGetAtracID(4096)
43:23:710 CRI Server M I[ME]: HLE\sceAtrac.cpp:1821 sceAtracLowLevelInitDecoder(0, 0bfbc8b0)
43:23:710 CRI Server M I[ME]: HLE\sceAtrac.cpp:1830 Channels: 2 outputChannels: 2 bytesperFrame: 2e8
43:23:710 CRI Server M W[ME]: HLE\sceAtrac.cpp:1861 This is an atrac3+ stereo audio (low level)
43:23:883 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 68 fs 74
43:26:111 user_main    I[G3D]: GLES\ShaderManager.cpp:139 Linked shader: vs 76 fs 77
43:46:525 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 272: Thread "idle0": pc= 08000000 sp= 083fff00  READY     (wt=0 wid=0 wv= 00000000 )
43:46:525 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 273: Thread "idle1": pc= 08000000 sp= 083fef00  READY     (wt=0 wid=0 wv= 00000000 )
43:46:526 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 274: Module "Digimon": name=Digimon gp=00000000 entry=088b63b8
43:46:526 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 276: Thread "user_main": pc= 088a9080 sp= 0bfff640 RUN      (wt=0 wid=0 wv= 00000000 )
43:46:526 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 277: MemoryPart "UserSbrk": MemPart: 08a88000 - 08ae8a00	size: 00060a00
43:46:526 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 278: CallBack "exit": thread=276, argument= 00000000
43:46:526 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 279: FPL "heap": -
43:46:526 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 280: LwMutex "heap": -
43:46:526 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 281: LwMutex "LoaderMutex": -
43:46:526 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 282: LwMutex "CriCsPsp": -
43:46:526 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 283: EventFlag "CriCond": init=00000000 cur=00000000 numwait=0
43:46:526 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 284: Thread "CRI FS File Access 0": pc= 0890d71c sp= 0bfbfa70   WAIT    (wt=4 wid=283 wv= 00000000 )
43:46:526 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 285: CallBack "crifsioutil_PowerCallback": thread=284, argument= 00000000
43:46:526 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 286: CallBack "crifsioutil_MsCallback": thread=284, argument= 00000000
43:46:526 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 287: LwMutex "CriCsPsp": -
43:46:526 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 288: EventFlag "CriCond": init=00000000 cur=00000000 numwait=0
43:46:526 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 289: Thread "CRI FS Memory File System": pc= 0890d71c sp= 0bfbea70   WAIT    (wt=4 wid=288 wv= 00000000 )
43:46:526 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 290: LwMutex "CriCsPsp": -
43:46:526 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 291: EventFlag "CriCond": init=00000000 cur=00000000 numwait=0
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 292: Thread "CRI FS Data Decompression 0": pc= 0890d71c sp= 0bfbda70   WAIT    (wt=4 wid=291 wv= 00000000 )
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 293: LwMutex "CriCsPsp": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 294: LwMutex "CriCsPsp": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 295: LwMutex "CriCsPsp": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 296: LwMutex "CriCsPsp": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 297: LwMutex "CriCsPsp": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 298: LwMutex "CriCsPsp": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 299: LwMutex "CriCsPsp": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 300: LwMutex "CriCsPsp": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 301: LwMutex "CriCsPsp": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 302: LwMutex "CriCsPsp": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 303: LwMutex "CriCsPsp": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 304: LwMutex "CriCsPsp": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 305: Thread "CRI Server Manager": pc= 08912964 sp= 0bfbca70   WAIT    (wt=2 wid=305 wv= 00000000 )
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 307: OpenFile "disc0:/PSP_GAME/USRDIR/FILEDATA.CPK": Seekpos: 25031d80
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 308: LwMutex "LoaderMutex": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 309: EventFlag "LoaderEvFlag": init=00000000 cur=00000000 numwait=0
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 310: Thread "LoaderThread": pc= 088058ac sp= 0bfbaaa0  READY     (wt=1 wid=0 wv= 00000000 )
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 311: EventFlag "SceGuSignal": init=00000001 cur=00000001 numwait=0
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 312: LwMutex "CriCsPsp": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 313: LwMutex "CriCsPsp": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 314: Thread "CRI Atom Sound Output": pc= 088dc478 sp= 0bfb6a70   WAIT    (wt=10 wid=9 wv= 00000100 )
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 315: LwMutex "CriCsPsp": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 316: LwMutex "CriCsPsp": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 317: LwMutex "CriCsPsp": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 318: LwMutex "CriCsPsp": -
43:46:527 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 319: LwMutex "CriCsPsp": -
43:46:528 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 320: LwMutex "CriCsPsp": -
43:46:528 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 321: EventFlag "CriCond": init=00000000 cur=00000000 numwait=0
43:46:528 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 322: Thread "CRI Atom Atrac Decode": pc= 0890d71c sp= 0bfb6270   WAIT    (wt=4 wid=321 wv= 00000000 )
43:46:528 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 323: LwMutex "CriCsPsp": -
43:46:528 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 324: LwMutex "CriCsPsp": -
43:46:528 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 325: LwMutex "LoaderMutex2": -
43:46:528 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 326: EventFlag "LoaderEvFlag": init=00000000 cur=00000000 numwait=0
43:46:528 user_main    I[KERNEL]: HLE\sceKernel.cpp:516 KO 327: Thread "LoaderThread": pc= 08879a1c sp= 0bfb5aa0   WAIT    (wt=1 wid=0 wv= 00000000 )
43:46:528 user_main    I[KERNEL]: HLE\sceKernel.cpp:162 Shutting down kernel - 54 kernel objects alive
43:46:545 GLES\Framebuffer.cpp:1786 I[SCEGE]: Destroying FBO for 00044000 : 480 x 272 x 1
43:46:545 GLES\Framebuffer.cpp:1786 I[SCEGE]: Destroying FBO for 00000000 : 480 x 272 x 1
43:46:616 Config.cpp:885 I[LOAD]: Config saved: C:\Users\Roxas\Downloads\ppsspp\memstick/PSP/SYSTEM/ppsspp.ini
43:46:620 Config.cpp:897 I[LOAD]: Controller config saved: C:\Users\Roxas\Downloads\ppsspp\memstick/PSP/SYSTEM/controls.ini
43:46:671 Config.cpp:885 I[LOAD]: Config saved: C:\Users\Roxas\Downloads\ppsspp\memstick/PSP/SYSTEM/ppsspp.ini
43:46:674 Config.cpp:897 I[LOAD]: Controller config saved: C:\Users\Roxas\Downloads\ppsspp\memstick/PSP/SYSTEM/controls.ini
````

DX9 (log)
````
39:59:118 EmuThread.cpp:169 I[BOOT]: Done.
40:05:562 Config.cpp:885 I[LOAD]: Config saved: C:\Users\Roxas\Downloads\ppsspp\memstick/PSP/SYSTEM/ppsspp.ini
40:05:567 Config.cpp:897 I[LOAD]: Controller config saved: C:\Users\Roxas\Downloads\ppsspp\memstick/PSP/SYSTEM/controls.ini
40:06:834 System.cpp:326 I[BOOT]: PPSSPP v0.9.9.1-558-gfeada0e Windows 32 bit
40:06:844 MemMap.cpp:278 I[MM]: Found valid memory base at 13000000 after 73 tries.
40:06:844 MemMap.cpp:339 I[MM]: Memory system initialized. RAM at 13020000 (mirror at 0 @ 1B000000, uncached @ 1B000000)
40:06:857 PSPLoaders.cpp:159 I[LOAD]: NPJH50686 : デジモンアドベンチャー
40:06:858 PSPLoaders.cpp:200 I[LOAD]: Loading disc0:/PSP_GAME/SYSDIR/EBOOT.BIN...
40:06:859 HLE\sceKernelMemory.cpp:431 I[KERNEL]: Kernel and user memory pools initialized
40:06:944 HLE\sceKernel.cpp:151 I[KERNEL]: Kernel initialized.
40:07:039 Util\BlockAllocator.cpp:381 I[HLE]: -----------
40:07:039 Util\BlockAllocator.cpp:385 I[HLE]: Block: 08800000 - 08804000 size 00004000 taken=1 tag=usersystemlib
40:07:039 Util\BlockAllocator.cpp:385 I[HLE]: Block: 08804000 - 08a87600 size 00283600 taken=1 tag=ELF/Digimon
40:07:039 Util\BlockAllocator.cpp:385 I[HLE]: Block: 08a87600 - 0c000000 size 03578a00 taken=0 tag=(untitled)
40:07:039 Util\BlockAllocator.cpp:387 I[HLE]: -----------
40:07:041 HLE\sceKernelModule.cpp:1028 I[LOAD]: Module Digimon: 00000000 089776e0 089776f8
40:07:106 HLE\ReplaceTables.cpp:824 I[HLE]: Replaced memcpy at 088b7edc with hash 0ffa5db8396d4274
40:07:106 HLE\ReplaceTables.cpp:824 I[HLE]: Replaced memset at 088b7f1c with hash eabb9c1b4f83d2b4
40:07:107 HLE\ReplaceTables.cpp:824 I[HLE]: Replaced memcpy at 0895b3b8 with hash 0266f96d740c7e03
40:07:107 HLE\sceKernelModule.cpp:1229 I[LOAD]: Exporting ent 0 named Digimon, 2 funcs, 4 vars, resident 08977a54
40:07:107 HLE\sceKernelModule.cpp:1557 I[LOAD]: Module entry: 088b63b8
40:07:179 root         N[BOOT]: EmuScreen.cpp:129 Loading C:/Documents and Settings/Roxas/Desktop/DWRD/NPJH-50686.iso...
40:07:189 root         I[KERNEL]: HLE\sceKernelThread.cpp:2178 276=sceKernelCreateThread(name=user_main, entry=088b64d8, prio=20, stacksize=262144)
40:07:189 root         I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=276, argSize=33, argPtr=0bfffed0)
40:07:189 root         I[KERNEL]: HLE\sceKernelThread.cpp:2318 __KernelReturnFromThread: 0
40:07:212 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 284=sceKernelCreateThread(name=CRI FS File Access 0, entry=089127b8, prio=20, stacksize=4096)
40:07:212 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=284, argSize=4, argPtr=0bfff3c0)
40:07:213 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 289=sceKernelCreateThread(name=CRI FS Memory File System, entry=089127b8, prio=20, stacksize=4096)
40:07:213 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=289, argSize=4, argPtr=0bfff3c0)
40:07:213 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 292=sceKernelCreateThread(name=CRI FS Data Decompression 0, entry=089127b8, prio=20, stacksize=4096)
40:07:213 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=292, argSize=4, argPtr=0bfff410)
40:07:215 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 305=sceKernelCreateThread(name=CRI Server Manager, entry=089127b8, prio=20, stacksize=8192)
40:07:215 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=305, argSize=4, argPtr=0bfff460)
40:07:246 CRI FS File  E[FileSys]: FileSystems\DirectoryFileSystem.cpp:501 DirectoryFileSystem::OpenFile: FAILED, 3 - access = 1
40:07:246 CRI FS File  E[IO]: HLE\sceIo.cpp:1200 ERROR_ERRNO_FILE_NOT_FOUND=sceIoOpen(ms0:/psp/SAVEDATA/NPJH50686INSTALL/FILEDATA.DNS, 40004001, 000021a4) - file not found
40:07:249 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 310=sceKernelCreateThread(name=LoaderThread, entry=08805858, prio=6f, stacksize=16384)
40:07:249 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=310, argSize=4, argPtr=08a2f374)
40:07:253 user_main    I[UTIL]: HLE\sceUtility.cpp:224 sceUtilityLoadModule(768)
40:07:275 user_main    I[UTIL]: HLE\sceUtility.cpp:224 sceUtilityLoadModule(770)
40:07:292 user_main    I[UTIL]: HLE\sceUtility.cpp:224 sceUtilityLoadModule(771)
40:07:337 user_main    I[ME]: HLE\sceMpeg.cpp:412 sceMpegInit()
40:07:371 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:329 Creating FBO for 00044000 : 480 x 272 x 1
40:07:371 user_main    W[G3D]: Common\FramebufferCommon.cpp:520 Memcpy fbo upload 04444000 -> 04044000
40:07:415 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:329 Creating FBO for 00000000 : 480 x 272 x 1
40:07:430 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 088aefb8 to block at 088b7edc
40:07:430 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 088aefbc to block at 088b7edc
40:07:476 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 088aeef0 to block at 088b7edc
40:07:476 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 088aeef4 to block at 088b7edc
40:07:782 user_main    I[UTIL]: HLE\sceUtility.cpp:224 sceUtilityLoadModule(769)
40:07:810 user_main    I[SCESAS]: HLE\sceSas.cpp:106 sceSasInit(08a86780, 256, 32, 0, 44100)
40:07:810 user_main    I[SCESAS]: HLE\sceSas.cpp:506 sceSasSetGrain(08a86780, 256)
40:07:811 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 314=sceKernelCreateThread(name=CRI Atom Sound Output, entry=089127b8, prio=20, stacksize=2048)
40:07:811 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=314, argSize=4, argPtr=0bfff320)
40:07:822 user_main    E[UTIL]: HLE\sceUtility.cpp:221 sceUtilityLoadModule(768): already loaded
40:07:822 user_main    E[UTIL]: HLE\sceUtility.cpp:221 sceUtilityLoadModule(770): already loaded
40:07:823 user_main    I[ME]: HLE\sceAtrac.cpp:1497 sceAtracReinit(0, 3)
40:07:827 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0891da70 to block at 088b7f1c
40:07:850 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0891b30c to block at 088b7f1c
40:07:860 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0892c764 to block at 088b7f1c
40:07:861 user_main    E[UTIL]: HLE\sceUtility.cpp:221 sceUtilityLoadModule(768): already loaded
40:07:861 user_main    E[UTIL]: HLE\sceUtility.cpp:221 sceUtilityLoadModule(770): already loaded
40:07:861 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 322=sceKernelCreateThread(name=CRI Atom Atrac Decode, entry=089127b8, prio=20, stacksize=2048)
40:07:861 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=322, argSize=4, argPtr=0bfff390)
40:07:864 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 08879ac0 to block at 088b7f1c
40:07:864 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2178 327=sceKernelCreateThread(name=LoaderThread, entry=08879a04, prio=1e, stacksize=16384)
40:07:864 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2277 sceKernelStartThread(thread=327, argSize=4, argPtr=08a2f9f0)
40:07:891 user_main    W[G3D]: Common\FramebufferCommon.cpp:679 Block transfer download 04044000 -> 041bffc0
40:09:162 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 08957ce8 to block at 088b7edc
40:09:162 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 08957db0 to block at 088b7f1c
40:09:163 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 08958c3c to block at 0895b3b8
40:09:164 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 08954218 to block at 088b7f1c
40:09:165 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 089545b8 to block at 088b7edc
40:09:165 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 089545ec to block at 088b7edc
40:09:165 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 089545ac to block at 088b7edc
40:09:166 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 08955f80 to block at 088b7edc
40:09:167 LoaderThread I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0895ccf8 to block at 088b7edc
40:10:966 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0889ca88 to block at 088b7f1c
40:10:966 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0889c528 to block at 088b7edc
40:10:967 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0889ce5c to block at 088b7f1c
40:10:967 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0889ce5c to block at 088b7f1c
40:10:967 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0889ce5c to block at 088b7f1c
40:10:967 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 089362c0 to block at 088b7f1c
40:11:027 user_main    I[UTIL]: Dialog\PSPSaveDialog.cpp:85 sceUtilitySavedataInitStart(08a2fd60) - SIZES (8)
40:11:027 user_main    I[UTIL]: Dialog\PSPSaveDialog.cpp:86 sceUtilitySavedataInitStart(08a2fd60) : Game key (hex): 11213203040703050708020A0C12013A
40:31:454 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 08880a9c to block at 088b7f1c
40:31:454 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 08880ad8 to block at 088b7f1c
40:31:850 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0889c750 to block at 088b7f1c
40:31:851 user_main    I[UTIL]: Dialog\PSPSaveDialog.cpp:85 sceUtilitySavedataInitStart(08a2fd60) - LIST (11)
40:31:851 user_main    I[UTIL]: Dialog\PSPSaveDialog.cpp:86 sceUtilitySavedataInitStart(08a2fd60) : Game key (hex): 11213203040703050708020A0C12013A
40:32:339 CRI Server M I[ME]: HLE\sceAtrac.cpp:549 0=sceAtracGetAtracID(4096)
40:32:339 CRI Server M I[ME]: HLE\sceAtrac.cpp:1821 sceAtracLowLevelInitDecoder(0, 0bfbc8b0)
40:32:339 CRI Server M I[ME]: HLE\sceAtrac.cpp:1830 Channels: 2 outputChannels: 2 bytesperFrame: 2e8
40:32:339 CRI Server M W[ME]: HLE\sceAtrac.cpp:1861 This is an atrac3+ stereo audio (low level)
40:35:820 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 088ba0a8 to block at 088b7edc
40:35:820 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 088b8dc0 to block at 088b7edc
40:35:821 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0889cd48 to block at 088b7f1c
40:36:006 user_main    I[UTIL]: Dialog\PSPSaveDialog.cpp:85 sceUtilitySavedataInitStart(08a2fd60) - LISTLOAD (4)
40:36:006 user_main    I[UTIL]: Dialog\PSPSaveDialog.cpp:86 sceUtilitySavedataInitStart(08a2fd60) : Game key (hex): 11213203040703050708020A0C12013A
40:38:789 idle0        I[UTIL]: Dialog\SavedataParam.cpp:580 Loading file with size 130976 in ms0:/PSP/SAVEDATA/NPJH50686DATA27/SECURE.BIN
40:40:194 CRI Server M I[ME]: HLE\sceAtrac.cpp:1084 sceAtracReleaseAtracID(0)
40:40:415 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0894ac8c to block at 088b7edc
40:40:415 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0894a5b4 to block at 088b7edc
40:40:415 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0894a5b4 to block at 088b7edc
40:40:415 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0894a5b4 to block at 088b7edc
40:40:416 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0894a5b4 to block at 088b7edc
40:40:416 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 08949568 to block at 088b7edc
40:41:597 user_main    I[HLE]: JitCommon\JitBlockCache.cpp:178 Adding proxy root 0894ef84 to block at 088b7f1c
40:42:655 user_main    W[JIT]: x86\Jit.cpp:335 Uneaten prefix at end of block: 0894ec9c
40:42:798 CRI Server M I[ME]: HLE\sceAtrac.cpp:549 0=sceAtracGetAtracID(4096)
40:42:798 CRI Server M I[ME]: HLE\sceAtrac.cpp:1821 sceAtracLowLevelInitDecoder(0, 0bfbc8b0)
40:42:798 CRI Server M I[ME]: HLE\sceAtrac.cpp:1830 Channels: 2 outputChannels: 2 bytesperFrame: 2e8
40:42:798 CRI Server M W[ME]: HLE\sceAtrac.cpp:1861 This is an atrac3+ stereo audio (low level)
40:57:931 CRI Server M I[G3D]: Directx9\TextureCacheDX9.cpp:113 Texture cached cleared from 31 textures
40:57:931 CRI Server M I[SCEGE]: Directx9\FramebufferDX9.cpp:1225 Destroying FBO for 00044000 : 480 x 272 x 1
40:57:931 CRI Server M I[SCEGE]: Directx9\FramebufferDX9.cpp:1225 Destroying FBO for 00000000 : 480 x 272 x 1
40:57:932 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 272: Thread "idle0": pc= 08000000 sp= 083fff00  READY     (wt=0 wid=0 wv= 00000000 )
40:57:932 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 273: Thread "idle1": pc= 08000000 sp= 083fef00  READY     (wt=0 wid=0 wv= 00000000 )
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 274: Module "Digimon": name=Digimon gp=00000000 entry=088b63b8
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 276: Thread "user_main": pc= 088a9080 sp= 0bfff640   WAIT    (wt=12 wid=1 wv= 00000000 )
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 277: MemoryPart "UserSbrk": MemPart: 08a88000 - 08ae8a00	size: 00060a00
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 278: CallBack "exit": thread=276, argument= 00000000
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 279: FPL "heap": -
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 280: LwMutex "heap": -
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 281: LwMutex "LoaderMutex": -
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 282: LwMutex "CriCsPsp": -
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 283: EventFlag "CriCond": init=00000000 cur=00000000 numwait=0
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 284: Thread "CRI FS File Access 0": pc= 0890d71c sp= 0bfbfa70   WAIT    (wt=4 wid=283 wv= 00000000 )
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 285: CallBack "crifsioutil_PowerCallback": thread=284, argument= 00000000
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 286: CallBack "crifsioutil_MsCallback": thread=284, argument= 00000000
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 287: LwMutex "CriCsPsp": -
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 288: EventFlag "CriCond": init=00000000 cur=00000000 numwait=0
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 289: Thread "CRI FS Memory File System": pc= 0890d71c sp= 0bfbea70   WAIT    (wt=4 wid=288 wv= 00000000 )
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 290: LwMutex "CriCsPsp": -
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 291: EventFlag "CriCond": init=00000000 cur=00000000 numwait=0
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 292: Thread "CRI FS Data Decompression 0": pc= 0890d71c sp= 0bfbda70   WAIT    (wt=4 wid=291 wv= 00000000 )
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 293: LwMutex "CriCsPsp": -
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 294: LwMutex "CriCsPsp": -
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 295: LwMutex "CriCsPsp": -
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 296: LwMutex "CriCsPsp": -
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 297: LwMutex "CriCsPsp": -
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 298: LwMutex "CriCsPsp": -
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 299: LwMutex "CriCsPsp": -
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 300: LwMutex "CriCsPsp": -
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 301: LwMutex "CriCsPsp": -
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 302: LwMutex "CriCsPsp": -
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 303: LwMutex "CriCsPsp": -
40:57:933 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 304: LwMutex "CriCsPsp": -
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 305: Thread "CRI Server Manager": pc= 08912974 sp= 0bfbca70 RUN      (wt=0 wid=0 wv= 00000000 )
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 307: OpenFile "disc0:/PSP_GAME/USRDIR/FILEDATA.CPK": Seekpos: 25031d80
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 308: LwMutex "LoaderMutex": -
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 309: EventFlag "LoaderEvFlag": init=00000000 cur=00000000 numwait=0
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 310: Thread "LoaderThread": pc= 088058ac sp= 0bfbaaa0   WAIT    (wt=1 wid=0 wv= 00000000 )
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 311: EventFlag "SceGuSignal": init=00000001 cur=00000001 numwait=0
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 312: LwMutex "CriCsPsp": -
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 313: LwMutex "CriCsPsp": -
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 314: Thread "CRI Atom Sound Output": pc= 088dc478 sp= 0bfb6a70   WAIT    (wt=10 wid=9 wv= 00000100 )
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 315: LwMutex "CriCsPsp": -
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 316: LwMutex "CriCsPsp": -
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 317: LwMutex "CriCsPsp": -
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 318: LwMutex "CriCsPsp": -
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 319: LwMutex "CriCsPsp": -
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 320: LwMutex "CriCsPsp": -
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 321: EventFlag "CriCond": init=00000000 cur=00000000 numwait=0
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 322: Thread "CRI Atom Atrac Decode": pc= 0890d71c sp= 0bfb6270   WAIT    (wt=4 wid=321 wv= 00000000 )
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 323: LwMutex "CriCsPsp": -
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 324: LwMutex "CriCsPsp": -
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 325: LwMutex "LoaderMutex2": -
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 326: EventFlag "LoaderEvFlag": init=00000000 cur=00000000 numwait=0
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:516 KO 327: Thread "LoaderThread": pc= 08879a1c sp= 0bfb5aa0   WAIT    (wt=1 wid=0 wv= 00000000 )
40:57:934 CRI Server M I[KERNEL]: HLE\sceKernel.cpp:162 Shutting down kernel - 54 kernel objects alive
40:57:963 Config.cpp:885 I[LOAD]: Config saved: C:\Users\Roxas\Downloads\ppsspp\memstick/PSP/SYSTEM/ppsspp.ini
40:57:967 Config.cpp:897 I[LOAD]: Controller config saved: C:\Users\Roxas\Downloads\ppsspp\memstick/PSP/SYSTEM/controls.ini
40:58:019 Config.cpp:885 I[LOAD]: Config saved: C:\Users\Roxas\Downloads\ppsspp\memstick/PSP/SYSTEM/ppsspp.ini
40:58:023 Config.cpp:897 I[LOAD]: Controller config saved: C:\Users\Roxas\Downloads\ppsspp\memstick/PSP/SYSTEM/controls.ini
````

**Comment by thedax** [comment]
@Blutgang: Is it safe to say your issue was fixed then, since you closed this? Just curious.

**Comment by Blutgang** [comment]
@thedax Hi. I've decided to close the issue since I've received a slightly newer (but still old) computer that doesn't have this issue. The issued wasn't fixed on the older computer.
