### ISSUE TITLE
Pangya 1.0.1 Issues

### ISSUE THREAD

**Issue by Xaelath** [hrydgard/ppsspp#7588]
1) A Bug occur whenever finished the game, attempt to pressing x wont work.
Somewhat fixed in PPSSPP v0.9.9-52-g3bab63d git.

2) Changing costume in will crash the game, Solution : Turning off Software Skinning will fix the problem.

3) In 1st Episode Cecilia Storyline in the 5th story after finishing the conversation pressing start button will crash the ppsspp. Tried turning off Hardware transform still didnt work.

**Comment by hrydgard** [comment]
I numbered your issues.

2) has been fixed in master, so try the latest development builds. http://buildbot.orphis.net/ppsspp/

Possibly this fix may have worked around the other issues too, can you test?

**Comment by sum2012** [comment]
let me watch this issue

**Comment by Xaelath** [comment]
1) Issues 1 fixed. but i didnt try other mode rather than tournaments.
2) Fixed. Thank you.
3) Still occured. Crashed.
Tested on PPSSPP v.1.0.1-159-gdad8f5c x64
Heres my log
https://www.dropbox.com/s/jnl0c1jncjovb5o/ppsspplog.txt?dl=0
I cant upload it here. only a pic allowed.
Crash occur in the end of the log where error started

**Comment by hrydgard** [comment]
@sum2012 , just click the Subscribe button to the right

@Xaelath , alright, thanks for testing. 3 is a bit worrying of course. Got a savegame or savestate before the crash?

**Comment by sum2012** [comment]
@hrydgard 
last time I pressed the button ,will receive all issue notifications

**Comment by Bigpet** [comment]
@sum2012  not the "watch" button at the top, but the "subscribe" button on the side

**Comment by unknownbrackets** [comment]
There's two.  The button at the top (watch) which subscribes to all (I am subscribed to all, for example, which means that @unknownbrackets makes no difference, I see everything.)

On the right, lower down, there's another button.  That button is dedicated to just this one issue.  For example, if I click it, it says "You're ignoring this thread."  That means I won't get notifications for this issue anymore, but I will for all others.

Now I've clicked it again and I'm subscribed to the thread (even if I unsub from all issues for ppsspp.)

Anyway, back to our regularly scheduled issuing... isn't this a duplicate probably?  There's like 3 other issues about levels crashing.

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets ,ok I try again,I press issue  subscribes  in 7587

**Comment by sum2012** [comment]
@Xaelath 
Can you load a savegame or savestate in
http://drive.google.com ? Thanks

**Comment by hrydgard** [comment]
The remaining issue 3) indeed seems quite likely to be the same or related to the other Pangya crashes like #6682 and #6057, so I don't think we need to have this one open as well. There seems to be something wrong with the memory allocator it uses (a "VPL" object), although I don't know what the problem might be..

**Comment by unknownbrackets** [comment]
AFAIK the game was at one point verified to mis-free VPL allocations in a way that needed behavior very precisely matching a real PSP's behavior.

That is, it relied on double-frees not being a huge problem with large allocated buffers due to the round-robin nature of the PSP's VPL allocator.  There are extensive tests on this alloactor and the behavior is matched pretty precisely (but I'm not sure if there may be game-specific hacks in the kernel.)

Not only does it rely upon that, but it also frees a variety of pointers even when they are not currently allocated.  This causes PPSSPP to log a lot of warnings which are largely (or wholly?) spurious.

This definitely makes it hard to tell what problems are coming from VPL allocations and what problems aren't.

-[Unknown]

**Comment by daniel229** [comment]
Change to FuncReplacements = False in PPSSPP.ini,then it won't crash,just a lot of invalid addresses,and the level still can be finished.

**Comment by Xaelath** [comment]
@daniel229 yeah it works but Theres a huge slowdown or fps drop on the loading tho.
heres the save state
https://docs.google.com/file/d/0B_0saQEB0kYKTmhOaExsOExMMm8/edit

**Comment by Xaelath** [comment]
Well i run a test for the quest then the issues continue
![ulus10438_00000](https://cloud.githubusercontent.com/assets/4243587/6649999/8ca3e9ca-ca2e-11e4-8722-0026d5e677ff.jpg)
