### ISSUE TITLE
Dead to Rights - Reckoning : Restart At Last Checkpoint - out game

### ISSUE THREAD

**Issue by n1dminhd** [hrydgard/ppsspp#8109]
Windows 7 64 bit
PPSSPP v1.1.1-103-g05687e6
I Play and  characters in the game Die, I choose "Restart At Last Checkpoint" --> out game
![ulus10023_00000](https://cloud.githubusercontent.com/assets/4449742/10725953/5f364902-7c02-11e5-8bb8-1bf4ad672854.jpg)

**Comment by unknownbrackets** [comment]
Can you provide a log?  Ideally debug - you can run "DebugLog.bat" iirc.

-[Unknown]

**Comment by n1dminhd** [comment]
Is file ppsspplog.ini? It is the 460mb, ultra ini files

**Comment by unknownbrackets** [comment]
I recommend you:

1. Delete the file first.
2. Play for the minimum amount of time necessary to get to the issue.

Since this probably requires playing for a bit to die, it might be best to create a savestate near death (ideally BEFORE you die), and then do the two steps above (loading the savestate for step 2.)

A 460MB log file will be pretty hard for me to glean useful data out of, so the smaller it is (while still fully covering the problem area) the better.

-[Unknown]

**Comment by n1dminhd** [comment]
now, it is 327MB

**Comment by n1dminhd** [comment]
Yes, I did save state and now it's just 33.6mb, it ok ?

**Comment by unknownbrackets** [comment]
Yeah, that should be workable.

-[Unknown]

**Comment by n1dminhd** [comment]
Now, it is 3.56mb, I let the character die, then to the Game Over screen, I save state, it ok?

**Comment by n1dminhd** [comment]
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/71526/ppsspplog.txt)

**Comment by unknownbrackets** [comment]
Hmm, I don't see anything alarming in this log.  You selected "Restart" near the end, right?

I see it playing music and rendering stuff like normal.  Near the end, it started rendering something new and compiled a few new shaders.  Hmm.

-[Unknown]

**Comment by n1dminhd** [comment]
Yes, I choose the first " Restart at Last Checkpoint "

**Comment by n1dminhd** [comment]
For sure, I tried again
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/71608/ppsspplog.txt)

**Comment by unknownbrackets** [comment]
Hmm.  It's hard to tell.  Now that I look again, I see it's checking the end flag:

ffffefe8=sceSasGetEndFlag(08daa900)

Maybe it's waiting for the rest to finish.  It sets volumes for all the ones not ended yet, though, I think... but I don't see it setting the voices in this log.

How big is the log if you do the following:

1. Don't use any savestate.
2. Before starting the game, go into Settings -> Tools -> Developer Tools -> Logging Channels.
3. Click "Toggle All" to turn all logging off.
4. Check sceSas (it's on the left in the middle.)  Click the checkmark, not "sceSas".
5. Hit Back a bunch of times, and start the game.

This will log only sceSas, so it will hopefully not be too long of a log to get in and get killed quickly.  This will let me see more info about those voices, in case that is the cause.

-[Unknown]

**Comment by n1dminhd** [comment]
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/72040/ppsspplog.txt)
When I play from the beginning, errors appear
When I use the save (gamefaq), and played last mission, there is no error, still "Checkpoint Restart at Last" normal

**Comment by unknownbrackets** [comment]
Darn, seems like those voices are set to looping, so that's probably not the issue... hmm.

So just to be clear, when you press circle or cross on that screen, nothing happens, and you can no longer move the cursor?  Does the screen go black, or anything?  Does PPSSPP crash?

-[Unknown]

**Comment by daniel229** [comment]
It seems works fine for me from new game.Is it the game ID ULUS10023?

**Comment by n1dminhd** [comment]
@unknownbrackets 
PPSSPP crash

**Comment by n1dminhd** [comment]
@daniel229 
![menu_00000](https://cloud.githubusercontent.com/assets/4449742/12005267/42ea3aaa-abce-11e5-868c-cd88b25810a7.jpg)

**Comment by n1dminhd** [comment]
Oh, PPSSPP v1.1.1-440-g7eb662f has a fix
Thanks, Very Good
I will test more

**Comment by n1dminhd** [comment]
I still do not understand
But, I've been tried
- ppsspp-v1.1.1-373-g4c0051d
- ppsspp-v1.1.1-392-g63e749d
Totally normal

**Comment by unknownbrackets** [comment]
Hmm, I'm not sure what's wrong there.  But it sounds like it's been fixed in the latest git build?

-[Unknown]

**Comment by n1dminhd** [comment]
Yes
Now, I try
v1.1.1-440-g7eb662f
v1.1.1-373-g4c0051d
v1.1.1-392-g63e749d
all ok
But yesterday it was still crash
A miracle ?????

**Comment by unknownbrackets** [comment]
It's possible it was even savedata related, and changed once you used a newer build, so now certain old builds work?  I'm not sure.

But it sounds like this works in the latest version, so I'm closing.

-[Unknown]
