### ISSUE TITLE
Toukiden Kiwami and Peace Walker atrac not working properly

### ISSUE THREAD

**Issue by daniel229** [hrydgard/ppsspp#8186]
also happen in demo.

Since https://github.com/hrydgard/ppsspp/pull/8105

This cutscene
![01](https://cloud.githubusercontent.com/assets/3481559/11014304/5161cb40-856b-11e5-8f02-37829e09687e.png)

**Comment by unknownbrackets** [comment]
This isn't the same thing as #6511?

-[Unknown]

**Comment by daniel229** [comment]
It's different.in https://github.com/hrydgard/ppsspp/issues/6511 that cuscene is fine.

**Comment by daniel229** [comment]
Toukiden Kiwami missing bgm,also happen in demo.

**Comment by daniel229** [comment]
Peace Walker freezing in prologue chapter.
![01](https://cloud.githubusercontent.com/assets/3481559/11018160/ded19502-85f5-11e5-8f93-9fd94654246b.png)

The log looks normal.
```
48:57:027 Main         I[ME]: HLE\sceAtrac.cpp:1694 2=sceAtracSetDataAndGetID(08c32584, 0000ffac)
48:57:027 Main         W[ME]: HLE\sceAtrac.cpp:1570 This is an atrac3 mono audio
48:57:027 Main         W[ME]: HLE\sceAtrac.cpp:1826 UNIMPL sceAtracIsSecondBufferNeeded(2)
48:57:028 snd_thread_m I[ME]: HLE\sceAtrac.cpp:1426 sceAtracResetPlayPosition(2, 0, 0, 0)
```

**Comment by unknownbrackets** [comment]
Since the same pull?  Can you check which commit?

I'm improving the remaining frame value now, but for streaming data it's involving a lot of changes...

-[Unknown]

**Comment by daniel229** [comment]
Yes,the same pull.
Peace Walker is broken by https://github.com/unknownbrackets/ppsspp/commit/5cc13c45f481197a0b67d1d43e21c5471ddfd97d

**Comment by unknownbrackets** [comment]
Okay, I assume the bufferState for all of these is likely a streaming value...

You can try this, which so far seems like an improvement for non-streaming buffers:
https://github.com/hrydgard/ppsspp/compare/master...unknownbrackets:atrac-remaining?expand=1

But I doubt it will help these games yet until I finish...

-[Unknown]

**Comment by daniel229** [comment]
Not help above games.

**Comment by daniel229** [comment]
but help https://github.com/hrydgard/ppsspp/issues/6370

```
34:05:560 ATRAC3 play  W[ME]: HLE\sceAtrac.cpp:1702 This is an atrac3+ stereo audio
34:05:561 ATRAC3 play  E[ME]: HLE\sceAtrac.cpp:1404 sceAtracGetSecondBufferInfo(0, 09fbe764, 09fbe760)
34:05:570 user_main    W[FileSys]: FileSystems\ISOFileSystem.cpp:571 Reading beyond end of file, clamping size 118784 to 117824
34:05:573 user_main    I[G3D]: GLES\ShaderManager.cpp:153 Linked shader: vs 16 fs 25
34:09:166 user_main    I[UTIL]: Dialog\PSPSaveDialog.cpp:85 sceUtilitySavedataInitStart(09b0f388) - LIST (11)
34:09:166 user_main    I[UTIL]: Dialog\PSPSaveDialog.cpp:86 sceUtilitySavedataInitStart(09b0f388) : Game key (hex): 0001020304050607080900010203040
34:09:185 user_main    E[KERNEL]: HLE\sceKernelThread.cpp:2732 800201a1=sceKernelDeleteCallback(0): bad cbId
```

**Comment by daniel229** [comment]
Also helps https://github.com/hrydgard/ppsspp/issues/6587

**Comment by daniel229** [comment]
atrac-remaining branch breaks atrac-remaining Prince of Persia Boukyaku no Suna

**Comment by unknownbrackets** [comment]
I just pushed a new one, can you try it now?  I've fixed some more things.

-[Unknown]

**Comment by daniel229** [comment]
Yeah, the Prince of Persia Boukyaku no Suna is fixed,other thing is the same.

**Comment by unknownbrackets** [comment]
So all the games in this issue are still not working?  5cc13c45f481197a0b67d1d43e21c5471ddfd97d should've been two commits, because I also changed the remaining frame logic there - it was definitely wrong before, because "decodePos" is in samples, and "size" is in encoded bytes.

Grr...

-[Unknown]

**Comment by daniel229** [comment]
Harukanaru Toki No Naka de series missing bgm.

**Comment by LunaMoo** [comment]
I think this wasn't fully fixed, Toukiden Kiwami still doesn't have music. Here's a link to the demo: http://www.mediafire.com/download/zhm70e0e9mwexgq/TK+1st+Demo.7z

BGM should already play on the "press start button" screen, but it's missing everywhere.

**Comment by unknownbrackets** [comment]
Okay, I'll reopen since other games may still have issues, but Sol Trigger's problems were fixed.

-[Unknown]

**Comment by daniel229** [comment]
In Peace Walker,the voice is good now.But sseing this error
```
51:02:168 Main         W[ME]: HLE\sceAtrac.cpp:1682 This is an atrac3 mono audio
51:02:168 Main         W[ME]: HLE\sceAtrac.cpp:1941 UNIMPL sceAtracIsSecondBufferNeeded(2)
51:02:169 snd_thread_m E[ME]: HLE\sceAtrac.cpp:1501 80630016=sceAtracResetPlayPosition(2, 0, 0, 0): first byte count not in valid range
```

Harukanaru Toki No Naka de is still missing BGM.
```
55:39:723              I[ME]: HLE\sceAtrac.cpp:1832 0=sceAtracSetHalfwayBufferAndGetID(09c2cc80, 00010000, 00033000)
55:39:723              W[ME]: HLE\sceAtrac.cpp:1696 This is an atrac3+ stereo audio
55:39:724              W[ME]: HLE\sceAtrac.cpp:1941 UNIMPL sceAtracIsSecondBufferNeeded(0)
55:39:724              I[ME]: HLE\sceAtrac.cpp:1480 sceAtracReleaseAtracID(0)
```

when it is working
```
56:15:687              I[ME]: HLE\sceAtrac.cpp:1623 0=sceAtracSetHalfwayBufferAndGetID(09c2cc80, 00010000, 00033000)
56:15:687              W[ME]: HLE\sceAtrac.cpp:1490 This is an atrac3+ stereo audio
56:15:688              W[ME]: HLE\sceAtrac.cpp:1729 UNIMPL sceAtracIsSecondBufferNeeded(0)
```

**Comment by unknownbrackets** [comment]
Would it be possible to JpcspTrace Peace Walker to see how it calls sceAtracResetPlayPosition?  It looks like it's not calling sceAtracGetBufferInfoForReseting or sceAtracGetBufferInfoForResetting first, so maybe that error is actually correct.  If it's a streaming buffer, it seems like a seek to 0 won't be allowed without writing some bytes.

Sounds like Harukanaru Toki No Naka and Toukiden Kiwami have a similar issue, probably.

-[Unknown]

**Comment by daniel229** [comment]
JPCSPTRACE
```
07:38:08.315364 snd_thread_main - -> sceAtracResetPlayPosition 0x2, 0x0, 0x0, 0x0 = 0x0
```

**Comment by unknownbrackets** [comment]
Hmm, this isn't my version that logs in and out, right?  Because that one always logs `= 0x0` in `->`.

In that case, it would seem like we're getting the buffer state wrong...

-[Unknown]

**Comment by daniel229** [comment]
It should be your version.

**Comment by unknownbrackets** [comment]
Oh okay, there are two lines that say sceAtracResetPlayPosition, the second line has the return value.  It's like this:

time threadname -> hleFunctionName arg1, arg2(inputValue), arg3 = 0x0
time threadname <- hleFunctionName arg1, arg2(outputValue), arg3 = returnValue

So the first line always says 0x0.  Sorry, I was lazy, it should just omit it entirely.

-[Unknown]

**Comment by daniel229** [comment]
I don't see the second for sceAtracResetPlayPosition
```
08:06:37.215010 SceDialogmainGraphics - -> sceKernelCreateThread 0x08415538('ScePafJob'), 0x840F2F8, 52, 0x4000, 0x100000, 0x87FEE10 = 0x0
08:06:37.215144 SceDialogmainGraphics - <- sceKernelCreateThread 0x08415538('ScePafJob'), 0x840F2F8, 52, 0x4000, 0x100000, 0x87FEE10 = 0x4230443
08:06:37.227051 SceDialogmainGraphics - -> sceKernelCreateThread 0x08415538('ScePafJob'), 0x840F2F8, 52, 0x4000, 0x100000, 0x87FEE20 = 0x0
08:06:37.227200 SceDialogmainGraphics - <- sceKernelCreateThread 0x08415538('ScePafJob'), 0x840F2F8, 52, 0x4000, 0x100000, 0x87FEE20 = 0x423DA49
08:06:42.935813 Main - -> sceKernelCreateThread 0x08BACF78('pspfont_queue'), 0x8A99F34, 64, 0x1000, 0x0, 0x0 = 0x0
08:06:42.935971 Main - <- sceKernelCreateThread 0x08BACF78('pspfont_queue'), 0x8A99F34, 64, 0x1000, 0x0, 0x0 = 0x419330D
08:06:48.908664 snd_thread_main - -> sceAtracResetPlayPosition 0x2, 0x0, 0x0, 0x0 = 0x0
```
