### ISSUE TITLE
Dissidia and Dissidia012 Final Fantasy Graphical Issue on K1Tablet on Newest PPSSPP GOLD

### ISSUE THREAD

**Issue by Steve00011** [hrydgard/ppsspp#8610]
Hello. I found an Issue after updating the ppsspp GOLD version via google play to the newest version right now. When I play Final Fantasy Dissidia or Dissidia012 then all I can see is the menu and a dark background instead of characters or the map I'm currently in. (See attached pictures) I play on the NVIDIA Shield K1 Tablet with latest android OS 6.0 .  I deleted the ppsspp gold apk, and downloaded an older build from november 215 and there the games worked again (see also the second picture from the working game). On my other device the Galaxy Note 4 with android os 5.1.1 thee ppssppgold play store apk is corectly working. Only on the tablet both dissidia games have now this issue after the latest update. Just want to let you know.
![screenshot_20160225-172355](https://cloud.githubusercontent.com/assets/5366390/13327004/68567dea-dbe8-11e5-86fa-7fdb632bafbd.png)
![screenshot_20160225-172829](https://cloud.githubusercontent.com/assets/5366390/13327023/77897ede-dbe8-11e5-816f-1ae137a40cdd.png)
![screenshot_20160225-054300](https://cloud.githubusercontent.com/assets/5366390/13327098/ca926e1a-dbe8-11e5-9621-bf84a908248f.png)
![screenshot_20160225-054318](https://cloud.githubusercontent.com/assets/5366390/13327156/f7bf50c4-dbe8-11e5-9047-148de3815b27.png)

**Comment by hrydgard** [comment]
I think this is related to another Shield Tablet specific problem in Jeanne d'Arc that has been reported. I don't really understand what's going on here, the game works on all the other Shield devices too..

**Comment by Steve00011** [comment]
I do'nt know if this is any help but, I tried now allmost 12 different build versions from your website and it works PERFECT till build number: 1.1.1 from 11.27.2015 (see screenshot; it's the one with the WHITE MARKED Download button)  on every other buid above that one, the Dissidia games does'nt work anymore. Maybe this can be helpfull to find the problem faster.
![screenshot_20160225-225630](https://cloud.githubusercontent.com/assets/5366390/13339656/a0a1b470-dc2a-11e5-8c33-c7967ea68376.png)

**Comment by hrydgard** [comment]
So it's this: https://github.com/hrydgard/ppsspp/pull/8258

@unknownbrackets  We might want to blacklist PackFramebufferAsync on these devices?

**Comment by unknownbrackets** [comment]
Well, a call to `PackFramebufferAsync_` should just hit this path on a GLES device:

https://github.com/unknownbrackets/ppsspp/blob/308a9481693fce0f59f738762002a5fa5ef4ef4e/GPU/GLES/Framebuffer.cpp#L1562

This device will have IsGLES right?  The next possibility (since this should be GLES3) is that it's actually from setting the stride:

https://github.com/hrydgard/ppsspp/pull/8258/files#diff-29313f9f6ed28d0e24e6dac4e0db8933R1538

-[Unknown]

**Comment by hrydgard** [comment]
I tried disabling that on mobile nVidia, let's see.... @Steve00011  ?

**Comment by sum2012** [comment]
@hrydgard The buildbot of Android still not recover

**Comment by hrydgard** [comment]
@sum2012 indeed, I've contacted Orphis.

**Comment by sum2012** [comment]
@hrydgard Thanks,I see it now
@Steve00011  Do  v1.2.1-18-g88f25fd fixed ?

**Comment by Steve00011** [comment]
@sum2012 Just tried v1.2.1-18-g88f25fd and... No; it still has the same issue

**Comment by appletonoutcast** [comment]
Hey,

Second Shield K1 user here, mirroring the problems reported. Tried with the latest build available, v1.2.1-31-g9bde45d, and can confirm the same issue is occuring. Some more screens to compare. 
![2016-03-04 08 00 03](https://cloud.githubusercontent.com/assets/17637936/13521349/6398f4d4-e1ad-11e5-849e-865890d4b9eb.png)
![2016-03-04 07 46 30](https://cloud.githubusercontent.com/assets/17637936/13521350/63998818-e1ad-11e5-8fb1-819758d41857.png)

**Comment by unknownbrackets** [comment]
This could be somehow related to #8623.  There was an uninitialized value that might've caused odd behavior.  But, even with that I'm still reproducing...

I'm able to reproduce this on a SHIELD TV even with all the `PackFramebufferAsync_` calls commented out, and also the `glPixelStorei` calls.  More importantly, I went back to 01669cbd92a56d565e9769ad789de742ac8780c3, and it doesn't work for me there either.

So this was either introduced earlier than #8258, or otherwise was caused by a driver change.

-[Unknown]

**Comment by unknownbrackets** [comment]
481be1cd34e6a46cc940f4c6b150c3ef2a1d9086 "broke" this.  Enabling "GPU_SUPPORTS_DUALSOURCE_BLEND" or "REPLACE_ALPHA_DUALSOURCE" makes it malfunction.

I think this might simply be a driver bug.

-[Unknown]

**Comment by Steve00011** [comment]
@unknownbrackets  so... This means, you're able to fix this little problem?

**Comment by hrydgard** [comment]
This should be fixed now, right?

**Comment by appletonoutcast** [comment]
Just downloaded and tested with the latest build. Partially fixed. As you can see, the models are appearing now, but the arena and background appear to be missing still.

![screenshot_20160314-092736](https://cloud.githubusercontent.com/assets/17637936/13747653/4b3442b4-e9c7-11e5-842c-aa00dc2ef7bc.png)

**Comment by Steve00011** [comment]
appletonoutcast is right. Same on my Shield Tab.

**Comment by Steve00011** [comment]
Any fixes now for the shield k1?

**Comment by hrydgard** [comment]
Still an issue?

**Comment by appletonoutcast** [comment]
Tested with the latest build available, 1.2.2-916. Issue appears to be resolved on an initial look!

**Comment by hrydgard** [comment]
Thanks! Pretty sure this was the "dual source alpha" thing on X1/K1 that we worked around..
