### ISSUE TITLE
Enabling IR Interpreter makes my games break

### ISSUE THREAD

**Issue by thedarkskinnedbrit** [hrydgard/ppsspp#8839]
https://imgur.com/a/JS0Ei It causes loading screens to clip, and assets of the game glitch out of wack

**Comment by hrydgard** [comment]
The IR interpreter is quite new and still has some bugs, but it does work fine in quite a few games.

What game is that?

**Comment by thedarkskinnedbrit** [comment]
Patapon 3, it does the same in 2 and 1.

**Comment by hrydgard** [comment]
Should be fixed with that, please re-test.

**Comment by thedarkskinnedbrit** [comment]
Still having this problem, should i redownload the Rom file?

**Comment by hrydgard** [comment]
Did you test with the latest from the buildbot?

http://buildbot.orphis.net/ppsspp/

**Comment by thedarkskinnedbrit** [comment]
Yeah its working now :)

**Comment by Alien1204** [comment]
IR only works well on IOS ??? Some games error(force close when loading stages, cant load save data) when i using it on android devices ...

**Comment by unknownbrackets** [comment]
The IR interpreter is the same on all platforms.  It's likely those issues would affect iOS too, but make sure you're using the latest git build.

-[Unknown]
