### ISSUE TITLE
1.3.0 last-minute regressions?

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#8966]
Release is planned to be in one week, on Sept 17 or 18.

Any **regressions** remaining? Otherwise we're ready. ~~#8965~~ has been merged and confirmed working.

~~#8970~~

**Comment by Fadi5555** [comment]
@hrydgard hi there. If you ask me about my real hope for this new version of this AMAZING project.
Is to fix micro stutter that happens every 3-4 seconds on iOS devices. This is really annoying issue and make your playing being fun at all. Sorry to said that many times also because of all people who I knew them complaining about that issue as well.

So if you don't mind please try to fix this annoying issue. We'll be more than grateful.
We all counting on you. Thanks for everything you have done on this project to make it shine.

**Comment by hrydgard** [comment]
We don't do official iOS releases so that's a separate issue. However I did just find something strange that may be related to that issue. Stay tuned

**Comment by unknownbrackets** [comment]
Can we please not release v1.3.0 with crippled logging / debugging capabilities?

Or are you going to make sure to plaster instructions everywhere on how to report bugs properly with graphics logging so we can know when FBOs or other errors are occurring since logs won't include it?

I really don't want a stable release that everyone will be reporting issues with and uploading logs from to have logs that will be broken in ways I'll definitely forget.  Unless we feel like there are no more bugs that need to be fixed?

-[Unknown]

**Comment by Fadi5555** [comment]
@unknownbrackets thank you so much for your politeness. I got your point. You mean you shouldn't release the new version of ppsspp which is 1.3.0 until you fixing the all issues who people reporting about them. I'm one of them. That's nice idea. After fixing all known issues you can release the stable version 1.3.0.
Thank you for this idea. You can't imagine how bad issue we got it in iOS devices if you can help @hrydgard to fix this issue we'll be thankful because of your amazing knowledge.
So hopefully it could fixed and other one on other platforms as well before releasing v1.3.0
Thank you so much

**Comment by hrydgard** [comment]
@Fadi5555  no [unknown] was disapproving of my "fix" which isn't a good one. better coming up.

**Comment by hrydgard** [comment]
Better log fix merged. Now let's get back to regressions. Only one I know of is FIFA perf regression...

**Comment by Fadi5555** [comment]
@hrydgard just quick report. I just tested new version of ppsspp 1.2.2-953 which is contain your recent commit (Fix backwards "gfxLog" logic. Strange. May help #8941) but unfortunately it doesn't fix that stutter. I appreciated what you have done so far to fix this annoying issue. I hope you have ideas to deal with this issue. Thanks a lot.

**Comment by unknownbrackets** [comment]
Does anyone have FIFA?  What we need is a profile.

One can create a profile using e.g.:
```sh
# With ab.sh
./ab.sh HEADLESS=0 ANDROID_NDK_PROFILER=1 NDK_DEBUG=0

# Using ant
ant debug -Dndkbuildopt="HEADLESS=0 ANDROID_NDK_PROFILER=1 NDK_DEBUG=0 APP_ABI=armeabi-v7a -j7"
adb shell am force-stop org.ppsspp.ppsspp
adb install -r bin/PPSSPP-debug.apk
```

Then run FIFA and go through the slow parts for a while.  After that:

```sh
adb pull /sdcard/gmon.out
$NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gprof obj/local/armeabi-v7a/ppsspp/libppsspp_jni.so -q -p > prof.txt
```

Most ideal would be a before and after to see why it's different...

-[Unknown]

**Comment by Anuskuss** [comment]
@hrydgard Can you give the translators some time before releasing this? Mainly because this is a stable release and there might be some people which will use this for a long time and it would be sad to not have everything translated in it.

#### Missing things in `en_US.ini`
- Tools -> Developer tools -> Texture Replacement
- Tools -> Developer tools -> Texture Replacement -> Save new textures
- Tools -> Developer tools -> Texture Replacement -> Replace textures
- Tools -> Developer tools -> Texture Replacement -> Create/Open textures.ini file for current game
- Tools -> Remote disc streaming
- Tools -> Remote disc streaming -> Browse Games
- Tools -> Remote disc streaming -> Share Games (Server)
- System -> Memory Stick inserted
- System -> Record Display
- System -> Use Lossless Video Coded (FFV1)
- System -> Record Audio
- #8913 (shouldn't be hardcoded)

**Comment by hrydgard** [comment]
@Anuskuss well, they've got a week... Also, translations could have been submitted any time, we do have a builtbot, etc.

**Comment by unknownbrackets** [comment]
What part of #8913 is hardcoded?

-[Unknown]

**Comment by sum2012** [comment]
I think that need #8912 need fix

**Comment by sum2012** [comment]
How about #8846 ? although need rebased

**Comment by sum2012** [comment]
Need fix #8969 although not  regression

**Comment by LunaMoo** [comment]
Another regression #8970

**Comment by zminhquanz** [comment]
i think that need #7740 need fix

**Comment by unknownbrackets** [comment]
No, #7740 is not a regression and was already an issue in v1.2.x and v1.1.x.

This is open source, so you're free to work on it and try to fix it.  I'm sure we'd be happy to accept a good fix - if it looks safe enough and you manage to find a fix soon enough, making it into v1.3.0 is definitely possible.

-[Unknown]

**Comment by zminhquanz** [comment]
what about Multithreading

**Comment by unknownbrackets** [comment]
We're also happy to accept pull requests for multithreading improvements that seem sound.  But they won't make us wait more months to release v1.3.0.

-[Unknown]

**Comment by zminhquanz** [comment]
and are you interesting about make UMD video like JPCSP ??

**Comment by unknownbrackets** [comment]
I'm going to start deleting feature request replies.  That's not what this issue is for, why don't you post on the forum instead?

-[Unknown]

**Comment by Anuskuss** [comment]
@hrydgard 
Well, the keys are missing.

@unknownbrackets 
```cpp
settingInfo_->Show(gr->T("RenderingMode NonBuffered Tip", "Faster, but nothing may draw in some games"), e.v);
```

It outputs this default message and isn't reading from the .ini file, is it?

**Comment by unknownbrackets** [comment]
It is reading from the ini file.  Use `RenderingMode NonBuffered Tip = Foo`.  Those are exactly the keys.

-[Unknown]

**Comment by Anuskuss** [comment]
But shouldn't it then output a variable instead of text?

**Comment by unknownbrackets** [comment]
No, if the key is not found in the ini file, it uses the default value.  If it is found in the ini file, it uses that value.

This is used here too, for example:
https://github.com/hrydgard/ppsspp/blob/b06359edd182456c4b107b00d6424b52b0193a99/UI/GameSettingsScreen.cpp#L1175

Spanish already has a translation:
https://github.com/hrydgard/ppsspp-lang/blob/da3f290a4626d4f1596ca35201ada164e0caa7ae/es_ES.ini#L394

-[Unknown]

**Comment by Anuskuss** [comment]
Well okay, my bad. I didn't assume there **should** be a default value but rather it would read from `en_US.ini` if a translation can't be found.

So will `en_US.ini` get updated or are the translators suppost to dig through the code, find the specific key and then translate it?

**Comment by hrydgard** [comment]
The latter. I know our translation system isn't great...  Been meaning to find something else, preferably something with online editing etc.

**Comment by sum2012** [comment]
While I do translate zh_CN and zh_TW , I also update en_us.ini

**Comment by hrydgard** [comment]
Thanks @sum2012

**Comment by sum2012** [comment]
@Anuskuss 
I just translate finish chinese,I also update  en_us.ini
Please check to translate your lang.
https://github.com/hrydgard/ppsspp-lang/commit/b5257e03e8c57d2cde98fe49f006554ef04705e4
https://github.com/hrydgard/ppsspp-lang/commit/cdf4a8df9556e4c261e2e9260b9810ae426f67bf

**Comment by Anuskuss** [comment]
@hrydgard One more thing, what does **Load language ini** actually do? Since I click it, but it seems like nothing's happening.

**Comment by gannon345** [comment]
There seems to have been a regression in the UI as of latest builds, at least for Android. Tapping "settings" in the main menu doesn't actually tap settings, it taps the game furthest to the right in the games list. Seems the touch is all shifted to the left, as none of the menu items on the right are working.

Selecting items with a controller still works normally, and the settings and all games in the list are selectable that way. It's only the touch UI that's behaving abnormally.

**Comment by unknownbrackets** [comment]
What's the most recent git build (from the downloads page) that works properly, and the first one that doesn't work properly?  If you know that 1.2.2 works and the latest git build doesn't, you can try half way in between.  If it works half way, try half way newer, otherwise try halfway older.

Going by halves you can find the cause in 10 or probably less checks.  It may also help to say what device you're using, since I wasn't seeing this problem.

-[Unknown]

**Comment by sum2012** [comment]
My friend have samsung s7
Play God eater 2 1.0 pop up with black screen with "WARNING:Battery save mode is on"
then the game cannot run.Can disable the code for 1.3 ?
![1](https://cloud.githubusercontent.com/assets/2177532/18510878/082fdf46-7ab3-11e6-83ae-2eb017cb8426.jpg)

**Comment by hrydgard** [comment]
That's just a warning, it has nothing to do with the game not working.

That's the danger of showing warnings, people will associate them with all kinds of failures that happen simultaneously...

**Comment by sum2012** [comment]
@hrydgard ok,I will try to explain to him

**Comment by hrydgard** [comment]
But yeah, this is probably a bug of some sort, but unlikely related to the battery.

**Comment by Fadi5555** [comment]
@hrydgard sorry to said that many times.
If you fixing all the issues here for people who ask you to fix it. Then if you have a free time please try on my issue here https://github.com/hrydgard/ppsspp/issues/8941
I'll be patient. Take your time to see what's wrong and fixing it. That's all my request from you.
Thanks...

**Comment by hrydgard** [comment]
Please stop nagging, and especially in this thread. I have no more ideas of what the cause might be and I have no way to reproduce the error or investigate currently, so there's not much more I can do.

If you could figure out how to run the app through Xcode Profiler, that could help. Also make really sure that the builds you are using are "release" builds and not "debug" builds.

**Comment by Fadi5555** [comment]
@hrydgard thank you for this reply.

**Comment by gannon345** [comment]
Not sure. I was previously on build 678, but after installing the new
builds, the regression even exists with that one after uninstalling and
reinstalling the older version.

**Comment by unknownbrackets** [comment]
Hmm, try removing the PSP/SYSTEM/ppsspp.ini file from your device - maybe it has to do with some configuration?  I'm not sure what it could be...

-[Unknown]

**Comment by gannon345** [comment]
I'll check. Will I lose any game saves in doing that?

**Comment by gannon345** [comment]
Tested it, no change. I even went as far as to back up the entire system
folder, remove the entire folder, then uninstall PPSSPP and reinstall the
older version (tried build 658, known working on my Shield K1 previously).
Same issue. Does PPSSPP save data anywhere besides the PSP folder under
internal storage main path?

**Comment by gannon345** [comment]
Shit, I figured it out and it's all my fault. /facepalm


Apparently, PPSSPP is not playing nice with screen/DPI scaling with the
Nvidia app optimizer. It was all screwy because I had PPSSPP running in
720p (1280x800) as native, instead of the native res of 1920x200. Odd that
it previously worked, but got screwy after updating. But either way,
consider this an odd one-off case, but probably not an actual issue.

**Comment by sum2012** [comment]
@hrydgard Can you help to update UI of font atlas ?
![screenshot_20160915-172150](https://cloud.githubusercontent.com/assets/2177532/18545683/bfb9fe9e-7b6c-11e6-9e0e-28b351e1cce4.jpg)

Cannot see font "些" in
https://github.com/hrydgard/ppsspp-lang/blob/master/zh_TW.ini#L390

**Comment by hrydgard** [comment]
@sum2012  Font atlas updated :)

**Comment by sum2012** [comment]
@hrydgard Thanks,font fixed

**Comment by hrydgard** [comment]
Time's up.
