### ISSUE TITLE
Kosmodrones v1.02 (homebrew) missing ingame music

### ISSUE THREAD

**Issue by benderscruffy** [hrydgard/ppsspp#9067]
v1.3-98-g492bda6
missing ingame music
http://www.kosmodrones.com/downloads/Kosmodrones_v102.zip
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/528844/ppsspplog.zip)

**Comment by hrydgard** [comment]
```
53:37:431 user_main    I[ME]: HLE\sceAudiocodec.cpp:87 sceAudiocodecInit(08abf4c0, 4097 (AT3))
53:37:431 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:1975 319=sceKernelCreateThread(Pge_Atrac3, 0881e690, 0000000e, 4096, 80000000, 00000000)
53:37:431 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2064 0=sceKernelStartThread(319, 0, 00000000)
53:37:465 Pge_Atrac3   I[ME]: HW\MediaEngine.cpp:86 FF: Unknown extradata size 0.
53:37:465 Pge_Atrac3   E[ME]: HW\SimpleAudioDec.cpp:107 Failed to open codec: retval = -22
53:37:465 Pge_Atrac3   E[ME]: HW\SimpleAudioDec.cpp:196 Error decoding Audio frame (0 bytes): -22 (ffffffea)
53:37:473 user_main    I[SCEGE]: Common\FramebufferCommon.cpp:416 Creating FBO for 00000000 : 480 x 272 x 3
53:37:480 Pge_Atrac3   E[ME]: HW\SimpleAudioDec.cpp:196 Error decoding Audio frame (0 bytes): -22 (ffffffea)
```

Seems we are passing some data to FFMPEG that it doesn't like. Strange, though, it seems to be regular at3 files looking in the zip...

**Comment by benderscruffy** [comment]
still happens in v1.9.3-164-g0a5ec4838

**Comment by benderscruffy** [comment]
PPSSPP v1.13.1-162-gc3324c872
still the same problem

**Comment by FATCatAndroid12** [comment]
Doesnt fixed via https://github.com/hrydgard/ppsspp/pull/20098

**Comment by hrydgard** [comment]
Yup, I know. That's why it's in the corresponding category in #20125.

I'm gonna tackle this one soon, it's not gonna be super difficult.

**Comment by hrydgard** [comment]
This is not yet fixed, as far as I know. Don't just silently close stuff, even if you reported it.

**Comment by hrydgard** [comment]
#20246 will finally fix this.
