### ISSUE TITLE
Gripshift Glitch flickering

### ISSUE THREAD

**Issue by mrcmunir** [hrydgard/ppsspp#9320]
BAD
![screenshot_224](https://cloud.githubusercontent.com/assets/1274014/23079301/a11900fc-f54c-11e6-8e35-58d4c614016f.png)

Passes in DX9 / OpenGL and DX11 (untested Vulkan)

But if we paused the emulator and continued the graphs are shown okay?

Ok
![screenshot_225](https://cloud.githubusercontent.com/assets/1274014/23079302/a11bd9f8-f54c-11e6-91a7-51a257937692.png)

Maybe broken some configuration?

**Comment by mrcmunir** [comment]
After some hours This bug always happen I tested 0.9.9.1 and higher so never working fine?.

Only working with Buffer effect and need Resume emulator for fix flickering

**Comment by hrydgard** [comment]
Yeah, I think this has always been broken. We are creating one of the two framebuffers too small, I think. Not quite sure why...

**Comment by unknownbrackets** [comment]
Could you try exporting a GE debugger dump on PC?

To do this, open the game and select Debug -> GE debugger..., then when it's displaying the scene, press Record in the top right.  After a second or so, it'll finish and save a trace of the drawing activity.

After that, check the memstick/PSP/SYSTEM/DUMP folder and it'll have created a file named something like "ULES12345_0000.ppdmp".  You can zip that and then drag and drop it into a reply here.

-[Unknown]

**Comment by mrcmunir** [comment]
[ULES00177_0001.zip](https://github.com/hrydgard/ppsspp/files/2300482/ULES00177_0001.zip)

done, if you need anything else let me know

**Comment by unknownbrackets** [comment]
Hm - I see it specifically drawing the black, from a texture.  This might just be a missing memcpy detection?

-[Unknown]

**Comment by benderscruffy01** [comment]
still happens
![gripshift](https://user-images.githubusercontent.com/48821663/54875962-07ac0480-4e43-11e9-9c5d-b8eb209d973f.PNG)
[DUMP.ZIP](https://github.com/hrydgard/ppsspp/files/3000104/DUMP.ZIP)

**Comment by mrcmunir** [comment]
it's fixed Tested with all backend DX9, DX11 , Opengl , Vulkan and Software renderer can't reproduced now 1.12 not sure what revision what fixed this but hey nice weird bug 👍

**Comment by Gamemulatorer** [comment]
I discover a new issue on this game
after finishing the level and then click next level the game is freeze and cannot proceed.
@mrcmunir can you reproduce this on your pc/android?
