### ISSUE TITLE
How to disable "Running slow: try frameskip, sound is choppy when slow "?

### ISSUE THREAD

**Issue by leoxxx** [hrydgard/ppsspp#9531]
It display in v1.4 and later version,when I playing game sometime.But I don't feel lag. It seems to display only once until restart game.
It don't display in v1.3.(v1.3.1xx,not test later vertion.)
I tested Win-32 version.Not sure, if the same as Android and Win-64 version.
Then,how to disable it?

**Comment by ijoinit** [comment]
Try edit psp/system/ppsspp.ini,set it like this HideSlowWarnings = True

**Comment by leoxxx** [comment]
THX.I'll try it.

**Comment by hrydgard** [comment]
Well, this is working as intended, so that people will try the frameskipping option.

**Comment by hrydgard** [comment]
Though if it's happening even though it's not running slowly, that might be a bug.

**Comment by leoxxx** [comment]
It doesn't display after I edit the .ini file.

**Comment by leoxxx** [comment]
It's not available in v1.4-20 after editing .ini file.

**Comment by hrydgard** [comment]
Fixed an issue where this showed up when it shouldn't. closing for now.

**Comment by Octavio1994** [comment]
> Try edit psp/system/ppsspp.ini,set it like this HideSlowWarnings = True

Thanks this helped me

**Comment by jcchikikomori** [comment]
> Though if it's happening even though it's not running slowly, that might be a bug.

IDK if it's possible. When i am playing Wipeout Pure, i turn frameskip on by 2, set CPU clock, sound is good, but still shows message
