### ISSUE TITLE
Qt does not request newer GL contexts (prevents HW tessellation)

### ISSUE THREAD

**Issue by Sunderland93** [hrydgard/ppsspp#9559]
Hi. A HW Tessellation option is uncheckable in Qt interface, but in SDL it works fine:

![2017-04-05 13-45-24](https://cloud.githubusercontent.com/assets/11344982/24691361/f92cba50-1a0d-11e7-8bdf-1f71c246af89.png)

![2017-04-05 13-45-43](https://cloud.githubusercontent.com/assets/11344982/24691381/13286580-1a0e-11e7-8a16-c0f77e1e0ed1.png)

OS: GNU/Linux (Debian 8, 9, Kubuntu 16.04), driver Nvidia 375.39

**Comment by mrcmunir** [comment]
I think is related Qt build need fix issue Opengl string 0.0. https://github.com/hrydgard/ppsspp/issues/9270

If fix that Opengl string in Qt build will fix hw tesselation too.

**Comment by unknownbrackets** [comment]
Does this still happen in the latest git build?

-[Unknown]

**Comment by mrcmunir** [comment]
It's fixed yet for mesa3d needed change to 3.3COMPAT profile in Qt build.

export MESA_GL_VERSION_OVERRIDE=3.3COMPAT or higher.

**Comment by unknownbrackets** [comment]
I think we fixed something related to that for it to create a profile better, but I might be wrong.  Is everything working fine now?

-[Unknown]

**Comment by mrcmunir** [comment]
@unknownbrackets not fixed yet for mesa3d  starting by default Opengl 3.0.0 and 1.30 so why are blacklist and needed force context to run (Mininum required to run correctly are Opengl 3.3 core and higher.)
![Captura de 2019-08-17 21-05-11](https://user-images.githubusercontent.com/1274014/63216378-6c3e6780-c134-11e9-8c44-e18ae8c445be.png)
![Captura de 2019-08-17 21-02-42](https://user-images.githubusercontent.com/1274014/63216379-6c3e6780-c134-11e9-9b93-f1a689117d98.png)



 .

**Comment by unknownbrackets** [comment]
Oh, I thought we were getting the new GL API version by using a core profile now (I remember we made some fixes to that, including to the way we handled EGL and SDL.)

Does MESA_GL_VERSION_OVERRIDE=3.3FC work?  That should be more along the lines of what we want.

I guess something is wrong with how GL is being init in Qt still.  Does it work fine when just using SDL?

-[Unknown]

**Comment by mrcmunir** [comment]
@unknownbrackets with SDL2 it works well for a long time without problem there (This running under Ivy bridge are support Opengl 4.2 Context)
![Captura de 2019-08-17 22-17-54](https://user-images.githubusercontent.com/1274014/63216900-05717c00-c13d-11e9-84b7-7472c931e5ef.png)


With MESA_GL_VERSION_OVERRIDE =3.3FC are working fine tested it with the current 19.x branch .
No needed compatibility context  in the pass I use compatibility profile due some problem when non run compatibility context for >3.0

So maybe are wrong in the initialization with Qt that something is needed to force the core?
