### ISSUE TITLE
ppsspp uwp launches save state menu by pressing X on the xbox controller

### ISSUE THREAD

**Issue by MysteriousHercules** [hrydgard/ppsspp#9789]
Everytime the button b is pressed on the xbox controller, the save state menu is loaded. I know that this menu is supposed to be called by left trigger or home button.

**Comment by WodsonKun** [comment]
@MysteriousHercules Can you compile PPSSPP in ARM for me? I want use it on my Lumia

**Comment by WodsonKun** [comment]
Just auto-config the controller in Control Mapping settings

**Comment by MysteriousHercules** [comment]
That was old, I already fixed it

**Comment by unknownbrackets** [comment]
Okay, closing - sounds like this was a configuration mistake.  Reply with more information if that's not correct.

-[Unknown]

**Comment by izenn** [comment]
i can confirm that this is still an issue after auto-configing the controller.  where in the code would i find the definition of this function?
