### ISSUE TITLE
Vulkan: Simpsons graphics problems on Mali (S7 Edge Exynos) and other GPUs

### ISSUE THREAD

**Issue by oli0371** [hrydgard/ppsspp#9830]
I have issue with some games like simpson the movie game using vulkan api the texture appear grey and the character black ppsspp version i use is 1.4.2-225

**Comment by brujo5** [comment]
Some instructions are not implemented in vulkan yet.

**Comment by unknownbrackets** [comment]
Does this work now?

-[Unknown]

**Comment by brujo5** [comment]
Nope 

This game require slow effects set ON and i think  Vulcan not implemeted this yet same as in dbz tenkiachi tag team.
Latest build Vulcan 
![screenshot_20171107-101925](https://user-images.githubusercontent.com/4172898/32507891-f1d05824-c3a5-11e7-92f6-bc00586b5942.jpg)

Latest build Opengl
![screenshot_20171107-102144](https://user-images.githubusercontent.com/4172898/32507946-0c0c4dc4-c3a6-11e7-862d-0b1a5e306bbb.jpg)

**Comment by hrydgard** [comment]
Interestingly, MotoGP has similar looking problems on Vulkan, and not just on mobile.

**Comment by brujo5** [comment]
@hrydgard 
This on latest Vulcan fixes with slow effects ON
![screenshot_20171110-095353](https://user-images.githubusercontent.com/4172898/32669519-0f7fbeb4-c5fe-11e7-9976-2bd6548f8fd6.jpg)

**Comment by hrydgard** [comment]
How is this now? The recent stencil fix might have helped this.

**Comment by brujo5** [comment]
Still the same with vulkan
![screenshot_20171113-080956](https://user-images.githubusercontent.com/4172898/32732581-46197246-c84a-11e7-9257-1d9e1ff9288d.jpg)

With opengl work great

**Comment by oli0371** [comment]
For me the game work now without graphical issue.. maybe because i use custom rom with latest mali driver

**Comment by hrydgard** [comment]
Let's hear from the others before we close, but it does seem like a driver issue.

**Comment by Blacob777** [comment]
opengl and vulkan with graphicals bugs on adreno

**Comment by brujo5** [comment]
Fixed with opengl in latest build thx @hrydgard 

![screenshot_20180212-090412](https://user-images.githubusercontent.com/4172898/36106373-6351a280-0fd4-11e8-9cdc-3331943a64ce.jpg)

**Comment by hrydgard** [comment]
That's actually a little surprising, I wonder what fixed it :) Oh well. Should really await results from Mali too, but meh, let's re-open if it is still an issue.

**Comment by unknownbrackets** [comment]
Does it also work in Vulkan?

-[Unknown]

**Comment by hrydgard** [comment]
Good point.

**Comment by brujo5** [comment]
@unknownbrackets 

Always work fine with Vulkan, the problem was with opengl but now its fixed in recent build

**Comment by hrydgard** [comment]
As far as I can tell from the old screenshots above, Vulkan was never perfect on Exynos, just a bit better...

**Comment by brujo5** [comment]
![screenshot_20180212-104027](https://user-images.githubusercontent.com/4172898/36110820-413b67fa-0fe1-11e8-892e-2735ec0460a8.png)
Now with vulkan

**Comment by oli0371** [comment]
The issue is fix for me on latest version

**Comment by hrydgard** [comment]
Interesting, could be the depth/discard thing we fixed...

**Comment by Deivmsr** [comment]
This problem still exists on Vulkan in a Mali G71 GPU.
![Screenshot_20190809-131325_PPSSPP](https://user-images.githubusercontent.com/40547165/62796506-7367d480-baa7-11e9-8796-ef0cec485754.jpg)

In OpenGL:
![Screenshot_20190809-130944_PPSSPP](https://user-images.githubusercontent.com/40547165/62796543-88dcfe80-baa7-11e9-8493-f09d77a0909f.jpg)

**Comment by Panderner** [comment]
In latest build the lines are fixed but there's still a line but for far places

OpenGL:
![Screenshot_2021-01-29-17-47-54-276_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/106259455-39b9f900-625a-11eb-8728-37cd31ac7070.jpg)

Vulkan:
![Screenshot_2021-01-29-17-46-29-047_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/106259466-3e7ead00-625a-11eb-97c0-aabc3e5c17c7.jpg)

And here's a bug for nearest place:
![Screenshot_2021-01-29-17-49-29-545_org ppsspp ppsspp](https://user-images.githubusercontent.com/37503397/106259558-63732000-625a-11eb-9b42-651b175dfe46.jpg)

**Comment by Gamemulatorer** [comment]
The graphics of this game on vulkan mali gpu still no improvement.
![Screenshot_2021-09-23-00-18-52-577_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/134382855-4cae947c-2f45-4487-ba71-892786bc6ca7.jpg)
[recording.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/7212343/recording.ppdmp.zip)

OpenGL is still better on this game.
![Screenshot_2021-09-23-00-21-42-461_org ppsspp ppsspp](https://user-images.githubusercontent.com/37603562/134383052-5ddf1b8e-caee-43d2-b37c-745f5adb40f9.jpg)

**Comment by Gamemulatorer** [comment]
This issue can be fixed via https://github.com/hrydgard/ppsspp/pull/15611

**Comment by Gamemulatorer** [comment]
> Vulkan
> And here's a bug for nearest place:
> 
>  latest.mp4

Those moving lines in the character can be workaround by disabling **Hardware Transform** in the graphics setting.

**Comment by hrydgard** [comment]
Hm, that's interesting...

**Comment by Gamemulatorer** [comment]
This game now is crashing on mali gpu vulkan using the recently build.
![Screenshot_20221113-224704](https://user-images.githubusercontent.com/37603562/201527872-4a11c25c-41fb-4b16-adeb-a038909b10b2.png)

**Comment by Gamemulatorer** [comment]
```
de0  x29 0000007a273060b0
11-13 22:46:56.845 21691 21691 F DEBUG   :     lr  0000007d4ccb0148  sp  0000007a27306010  pc  0000007d4ccb0178  pst 0000000000000000
11-13 22:46:56.940 21691 21691 F DEBUG   : backtrace:
11-13 22:46:56.940 21691 21691 F DEBUG   :       #00 pc 000000000004e178  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: ddedea5a1d1071f97c5321841b6be985)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #01 pc 0000000000552798  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+2260) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #02 pc 0000000000013990  /system/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+76) (BuildId: 40363036c1f5a305d00fe1d058a86ccb)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #03 pc 0000000000006e58  /system/lib64/liblog.so (__android_log_assert+336) (BuildId: 21b21988978dd909085438079c351e51)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #04 pc 00000000007543a8  /data/app/~~pHqjiwAUMA0VzMDVn4FD-Q==/org.ppsspp.ppsspp-ak5CATYS0Elm8dK6T73vEw==/lib/arm64/libppsspp_jni.so (HandleAssert(char const*, char const*, int, char const*, char const*, ...)+280) (BuildId: 3ed4c4cb7b415e6b9556cc3378f510144e0b52e6)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #05 pc 0000000000731b04  /data/app/~~pHqjiwAUMA0VzMDVn4FD-Q==/org.ppsspp.ppsspp-ak5CATYS0Elm8dK6T73vEw==/lib/arm64/libppsspp_jni.so (VulkanRenderManager::BeginFrame(bool, bool)+272) (BuildId: 3ed4c4cb7b415e6b9556cc3378f510144e0b52e6)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #06 pc 0000000000c538a8  /data/app/~~pHqjiwAUMA0VzMDVn4FD-Q==/org.ppsspp.ppsspp-ak5CATYS0Elm8dK6T73vEw==/lib/arm64/libppsspp_jni.so (Draw::VKContext::BeginFrame()+40) (BuildId: 3ed4c4cb7b415e6b9556cc3378f510144e0b52e6)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #07 pc 0000000000777f10  /data/app/~~pHqjiwAUMA0VzMDVn4FD-Q==/org.ppsspp.ppsspp-ak5CATYS0Elm8dK6T73vEw==/lib/arm64/libppsspp_jni.so (EmuScreen::preRender()+52) (BuildId: 3ed4c4cb7b415e6b9556cc3378f510144e0b52e6)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #08 pc 0000000000c5caf4  /data/app/~~pHqjiwAUMA0VzMDVn4FD-Q==/org.ppsspp.ppsspp-ak5CATYS0Elm8dK6T73vEw==/lib/arm64/libppsspp_jni.so (ScreenManager::render()+192) (BuildId: 3ed4c4cb7b415e6b9556cc3378f510144e0b52e6)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #09 pc 000000000076e9a0  /data/app/~~pHqjiwAUMA0VzMDVn4FD-Q==/org.ppsspp.ppsspp-ak5CATYS0Elm8dK6T73vEw==/lib/arm64/libppsspp_jni.so (NativeRender(GraphicsContext*)+736) (BuildId: 3ed4c4cb7b415e6b9556cc3378f510144e0b52e6)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #10 pc 00000000007671ac  /data/app/~~pHqjiwAUMA0VzMDVn4FD-Q==/org.ppsspp.ppsspp-ak5CATYS0Elm8dK6T73vEw==/lib/arm64/libppsspp_jni.so (Java_org_ppsspp_ppsspp_NativeActivity_runEGLRenderLoop+772) (BuildId: 3ed4c4cb7b415e6b9556cc3378f510144e0b52e6)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #11 pc 0000000000009198  /data/app/~~pHqjiwAUMA0VzMDVn4FD-Q==/org.ppsspp.ppsspp-ak5CATYS0Elm8dK6T73vEw==/oat/arm64/base.odex (art_jni_trampoline+152)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #12 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #13 pc 00000000001a8a6c  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #14 pc 00000000003165ec  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #15 pc 000000000030c6b0  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+912) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #16 pc 0000000000676218  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtualQuick+668) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #17 pc 0000000000131594  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual_quick+20) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #18 pc 000000000010695c  /data/app/~~pHqjiwAUMA0VzMDVn4FD-Q==/org.ppsspp.ppsspp-ak5CATYS0Elm8dK6T73vEw==/oat/arm64/base.vdex (org.ppsspp.ppsspp.NativeActivity$1.run+68)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #19 pc 0000000000303e34  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.14481107443624448449)+268) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #20 pc 000000000065e5a4  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+760) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #21 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #22 pc 000000000015aaf8  /apex/com.android.art/javalib/arm64/boot.oat (java.lang.Thread.run+72) (BuildId: 3d2be9b2804151ac6900742f9d5f5df45401930e)
11-13 22:46:56.940 21691 21691 F DEBUG   :       #23 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:46:56.941 21691 21691 F DEBUG   :       #24 pc 00000000001a8a6c  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:46:56.941 21691 21691 F DEBUG   :       #25 pc 000000000054a470  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:46:56.941 21691 21691 F DEBUG   :       #26 pc 0000000000598bcc  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1288) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:46:56.941 21691 21691 F DEBUG   :       #27 pc 00000000000af97c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: ddedea5a1d1071f97c5321841b6be985)
11-13 22:46:56.941 21691 21691 F DEBUG   :       #28 pc 00000000000500d0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: ddedea5a1d1071f97c5321841b6be985)
--------- beginning of main
11-13 22:48:32.700 22322 22322 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-13 22:48:32.700 22322 22322 F DEBUG   : Native Crash TIME: 1650247
11-13 22:48:32.700 22322 22322 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-13 22:48:32.700 22322 22322 F DEBUG   : Build fingerprint: 'realme/RMX3261/RMX3261:11/RP1A.201005.001/1662134708000:user/release-keys'
11-13 22:48:32.700 22322 22322 F DEBUG   : Revision: '0'
11-13 22:48:32.700 22322 22322 F DEBUG   : ABI: 'arm64'
11-13 22:48:32.700 22322 22322 F DEBUG   : Timestamp: 2022-11-13 22:48:32+0800
11-13 22:48:32.700 22322 22322 F DEBUG   : pid: 22216, tid: 22281, name: AndroidRender  >>> org.ppsspp.ppsspp <<<
11-13 22:48:32.700 22322 22322 F DEBUG   : uid: 10216
11-13 22:48:32.700 22322 22322 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
11-13 22:48:32.700 22322 22322 F DEBUG   : Abort message: '(VulkanRenderManager.cpp:BeginFrame:606) Critical: [false] Device lost in vkWaitForFences'
11-13 22:48:32.700 22322 22322 F DEBUG   :     x0  0000000000000000  x1  0000000000005709  x2  0000000000000006  x3  0000007a31dfb030
11-13 22:48:32.700 22322 22322 F DEBUG   :     x4  0000007d52f37000  x5  0000007d52f37000  x6  0000007d52f37000  x7  00000000000c95d2
11-13 22:48:32.700 22322 22322 F DEBUG   :     x8  00000000000000f0  x9  0000007d4cc82840  x10 ffffff80fffffbdf  x11 0000000000000001
11-13 22:48:32.700 22322 22322 F DEBUG   :     x12 00000000eabca151  x13 e59a00000012810c  x14 0025317764746080  x15 00002bea7cebc7dc
11-13 22:48:32.700 22322 22322 F DEBUG   :     x16 0000007d4cd1ac80  x17 0000007d4ccfc420  x18 0000007a532dc584  x19 00000000000056c8
11-13 22:48:32.700 22322 22322 F DEBUG   :     x20 0000000000005709  x21 00000000ffffffff  x22 0000007abbfba37f  x23 000000000000000b
11-13 22:48:32.700 22322 22322 F DEBUG   :     x24 0000007abbf9a0b7  x25 0000000000000001  x26 0000007abbfb10e1  x27 0000007abc5a9000
11-13 22:48:32.700 22322 22322 F DEBUG   :     x28 b400007adc611de0  x29 0000007a31dfb0b0
11-13 22:48:32.700 22322 22322 F DEBUG   :     lr  0000007d4ccb0148  sp  0000007a31dfb010  pc  0000007d4ccb0178  pst 0000000000000000
11-13 22:48:32.793 22322 22322 F DEBUG   : backtrace:
11-13 22:48:32.793 22322 22322 F DEBUG   :       #00 pc 000000000004e178  /apex/com.android.runtime/lib64/bionic/libc.so (abort+168) (BuildId: ddedea5a1d1071f97c5321841b6be985)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #01 pc 0000000000552798  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+2260) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #02 pc 0000000000013990  /system/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+76) (BuildId: 40363036c1f5a305d00fe1d058a86ccb)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #03 pc 0000000000006e58  /system/lib64/liblog.so (__android_log_assert+336) (BuildId: 21b21988978dd909085438079c351e51)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #04 pc 00000000007543a8  /data/app/~~pHqjiwAUMA0VzMDVn4FD-Q==/org.ppsspp.ppsspp-ak5CATYS0Elm8dK6T73vEw==/lib/arm64/libppsspp_jni.so (HandleAssert(char const*, char const*, int, char const*, char const*, ...)+280) (BuildId: 3ed4c4cb7b415e6b9556cc3378f510144e0b52e6)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #05 pc 0000000000731b04  /data/app/~~pHqjiwAUMA0VzMDVn4FD-Q==/org.ppsspp.ppsspp-ak5CATYS0Elm8dK6T73vEw==/lib/arm64/libppsspp_jni.so (VulkanRenderManager::BeginFrame(bool, bool)+272) (BuildId: 3ed4c4cb7b415e6b9556cc3378f510144e0b52e6)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #06 pc 0000000000c538a8  /data/app/~~pHqjiwAUMA0VzMDVn4FD-Q==/org.ppsspp.ppsspp-ak5CATYS0Elm8dK6T73vEw==/lib/arm64/libppsspp_jni.so (Draw::VKContext::BeginFrame()+40) (BuildId: 3ed4c4cb7b415e6b9556cc3378f510144e0b52e6)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #07 pc 0000000000777f10  /data/app/~~pHqjiwAUMA0VzMDVn4FD-Q==/org.ppsspp.ppsspp-ak5CATYS0Elm8dK6T73vEw==/lib/arm64/libppsspp_jni.so (EmuScreen::preRender()+52) (BuildId: 3ed4c4cb7b415e6b9556cc3378f510144e0b52e6)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #08 pc 0000000000c5caf4  /data/app/~~pHqjiwAUMA0VzMDVn4FD-Q==/org.ppsspp.ppsspp-ak5CATYS0Elm8dK6T73vEw==/lib/arm64/libppsspp_jni.so (ScreenManager::render()+192) (BuildId: 3ed4c4cb7b415e6b9556cc3378f510144e0b52e6)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #09 pc 000000000076e9a0  /data/app/~~pHqjiwAUMA0VzMDVn4FD-Q==/org.ppsspp.ppsspp-ak5CATYS0Elm8dK6T73vEw==/lib/arm64/libppsspp_jni.so (NativeRender(GraphicsContext*)+736) (BuildId: 3ed4c4cb7b415e6b9556cc3378f510144e0b52e6)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #10 pc 00000000007671ac  /data/app/~~pHqjiwAUMA0VzMDVn4FD-Q==/org.ppsspp.ppsspp-ak5CATYS0Elm8dK6T73vEw==/lib/arm64/libppsspp_jni.so (Java_org_ppsspp_ppsspp_NativeActivity_runEGLRenderLoop+772) (BuildId: 3ed4c4cb7b415e6b9556cc3378f510144e0b52e6)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #11 pc 0000000000009198  /data/app/~~pHqjiwAUMA0VzMDVn4FD-Q==/org.ppsspp.ppsspp-ak5CATYS0Elm8dK6T73vEw==/oat/arm64/base.odex (art_jni_trampoline+152)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #12 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #13 pc 00000000001a8a6c  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #14 pc 00000000003165ec  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #15 pc 000000000030c6b0  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+912) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #16 pc 0000000000676218  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtualQuick+668) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #17 pc 0000000000131594  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual_quick+20) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #18 pc 000000000010695c  /data/app/~~pHqjiwAUMA0VzMDVn4FD-Q==/org.ppsspp.ppsspp-ak5CATYS0Elm8dK6T73vEw==/oat/arm64/base.vdex (org.ppsspp.ppsspp.NativeActivity$1.run+68)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #19 pc 0000000000303e34  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.14481107443624448449)+268) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #20 pc 000000000065e5a4  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+760) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #21 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #22 pc 000000000015aaf8  /apex/com.android.art/javalib/arm64/boot.oat (java.lang.Thread.run+72) (BuildId: 3d2be9b2804151ac6900742f9d5f5df45401930e)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #23 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #24 pc 00000000001a8a6c  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #25 pc 000000000054a470  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #26 pc 0000000000598bcc  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1288) (BuildId: 79991d5a5ba026c69376ba7be4e58e38)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #27 pc 00000000000af97c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: ddedea5a1d1071f97c5321841b6be985)
11-13 22:48:32.793 22322 22322 F DEBUG   :       #28 pc 00000000000500d0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: ddedea5a1d1071f97c5321841b6be985)
11-13 22:48:33.020 22216 22216 I PPSSPPNativeActivity: onPause
11-13 22:48:33.023 22216 22216 I PPSSPPNativeActivity: Joining render thread...
11-13 22:48:33.024 22216 22216 I PPSSPPNativeActivity: exitEGLRenderLoop
11-13 22:48:33.167 22216 22281 I DEBUG   : Crash thread undumpable
```

**Comment by unknownbrackets** [comment]
Does turning off the geometry shader option or hardware transform help?

-[Unknown]

**Comment by Gamemulatorer** [comment]
> Does turning off the geometry shader option or hardware transform help?
> 
> -[Unknown]

Turning off both doesn't help.

**Comment by Gamemulatorer** [comment]
> > Vulkan
> > And here's a bug for nearest place:
> > latest.mp4
> 
> Those moving lines in the character can be workaround by disabling **Hardware Transform** in the graphics setting.

Can also reproduce this issue on my vivo y11 with snapdragon 439 cpu adreno 505 gpu.

https://user-images.githubusercontent.com/37603562/206867764-5736fe2a-88bd-475d-ad54-a753c2e119cc.mp4
